### ISSUE TITLE
The application could not be installed: INSTALL_FAILED_INVALID_APK

### ISSUE THREAD

**Issue by lucav90** [AndreyPavlenko/Fermata#10]
Hi,

when i build and try to run/debug on device i have this error:

Installation did not succeed.
The application could not be installed: INSTALL_FAILED_INVALID_APK

what is the problem?

thanks

**Comment by AndreyPavlenko** [comment]
How do you build the apk?

**Comment by lucav90** [comment]
Hi,

i have resolve setting (on manifest) 

android:extractNativeLibs="true"
