### ISSUE TITLE
Issue when phone disconnects mid drive

### ISSUE THREAD

**Issue by jgush** [AndreyPavlenko/Fermata#100]
All I see is a blank blue screen with the audio continuing but no video. I can't choose another video or change from YouTube to file folder all It shows is play/pause skip forward or back . How can I restart the app or navigate anywhere else after disconnecting and reconnecting without restarting the entire car stereo (my stereo has no power off function have to turn ignition off and open door to turn off power completely)

**Comment by jgush** [comment]
![20211209_095152](https://user-images.githubusercontent.com/51218422/145440347-2fe20912-d576-4628-8540-89bada838982.jpg)
Pressing button in bottom right does nothing

**Comment by AndreyPavlenko** [comment]
What do you mean by "when phone disconnects mid drive"?
Have you tried the middle, play/pause, button long press? It should stop the playback.

**Comment by jgush** [comment]
My deck has bad connection so sometimes Android auto gets disconnected while driving so I unplug cord and plug back in and the audio resumes but no video

**Comment by jgush** [comment]
No video and no way to go back to main window

**Comment by jgush** [comment]
Main screen of formata that is

**Comment by jgush** [comment]
When audio resumes all I see is blue screen with status bar etc shown above

**Comment by AndreyPavlenko** [comment]
Try the play/pause button long press.

**Comment by jgush** [comment]
Ok will try on drive home from work in 2 hours

**Comment by jgush** [comment]
Update tried long push on pause /play all that happened is audio stopped and I lost the in app pause play and skip buttons 
![Uploading 20211209_170204.jpg…]()

**Comment by jgush** [comment]
Round button has no arrow and does nothing still

**Comment by AndreyPavlenko** [comment]
I don't see the last image.
Can you exit to the home screen when pressing the round button in the bottom left corner?

**Comment by jgush** [comment]
No the round button does nothing when pressed. I can move it around but it doesn't do anything 
![Uploading 20211209_170204.jpg…]()

**Comment by jgush** [comment]
![20211209_170204](https://user-images.githubusercontent.com/51218422/145584575-73208782-00ca-4a7c-92ee-995d4a8a1e70.jpg)

**Comment by jgush** [comment]
This is screen after long press on pause/play

**Comment by jgush** [comment]
No idea how to get video displayed again

**Comment by AndreyPavlenko** [comment]
The round button in the bottom left corner, the AA home button.

**Comment by jgush** [comment]
It goes back to AA and if I go back to Fermata it shows same.blue screen no video until I turn truck off and on again

**Comment by jgush** [comment]
How do I get video back ?

**Comment by jgush** [comment]
I used car stream until Dec AA patch and carstream would resume video when unplugged and plugged back in . Fermata is blue screen

**Comment by AndreyPavlenko** [comment]
Have you tried to disconnect phone from USB? It should restart the app.

**Comment by jgush** [comment]
Yes that is how I get blue screen to.begin with. My USB cable disconnects and stops AA I unplug USB and reconnect and AA starts and audio resumes but blue screen for video

**Comment by jgush** [comment]
How to get rid of blue screen when reconnecting USB is my question

**Comment by jgush** [comment]
Main screen in fermata

**Comment by AndreyPavlenko** [comment]
I'll try to fix, if I could reproduce the issue. In my case, when I unplug/plug the cable, it restarts the program.

**Comment by jgush** [comment]
Yeah it doesn't restart fermata . My nav etc all resumes and YouTube resumes immediately just no video display only.bkue screen

**Comment by jgush** [comment]
Glad to donate If you can find fix

**Comment by AndreyPavlenko** [comment]
Could you please send me the log /mnt/sdcard/Android/data/me.aap.fermata.auto..../files/Fermata.log ?

**Comment by jgush** [comment]
I can send that after work when I can connect to pc

**Comment by AndreyPavlenko** [comment]
Could you please check this https://github.com/AndreyPavlenko/Fermata/releases/tag/test version?
