### ISSUE TITLE
M3U8 List - not showing channel Logo 

### ISSUE THREAD

**Issue by sherere** [AndreyPavlenko/Fermata#102]
Gi guys,

My M3U8 file comes with this LINE
#EXTINF:-1 tvg-chno="638" tvg-logo="http://www.site.com/picon/1_0_19_27E_16_8_FFFF0000_0_0_0.png" tvg-id="1:0:19:27E:16:8:FFFF0000:0:0:0:" tvg-name="A&E HD",A&E HD

I thik it worked til version 1.8.6. After that i cant load TV Channel logos.

Can any one help me?

Thanks

**Comment by AndreyPavlenko** [comment]
Is this "http://www.site.com/picon/1_0_19_27E_16_8_FFFF0000_0_0_0.png" url is exatcly what you have in m3u or you've changed the host name?

**Comment by Patriot26rus** [comment]
Тут версия fermata ни при чем, каналы еще и пропадают, если Вы не знали и даже с избранного, плейлисты все пиратские, они переодически меняются, их также провайдеры блокируют, плейлисты только покупать, если влом постоянно искать каналы))))

**Comment by sherere** [comment]
> Is this "http://www.site.com/picon/1_0_19_27E_16_8_FFFF0000_0_0_0.png" url is exatcly what you have in m3u or you've changed the host name?

I've changed because it is my personal site.

Complete example from my m3u file:
`#EXTM3U 
#EXTVLCOPT--http-reconnect=true
#EXTINF:-1 tvg-chno="638" tvg-logo="http://link.to.logo/picon/1_0_19_27E_16_8_FFFF0000_0_0_0.png" tvg-id="1:0:19:27E:16:8:FFFF0000:0:0:0:" tvg-name="A&E HD",A&E HD
#EXTVLCOPT:program=638
http://link.to.stream/1:0:19:27E:16:8:FFFF0000:0:0:0:`

if u need a real link from logo url, i can send u in private, ok?

> Тут версия fermata ни при чем, каналы еще и пропадают, если Вы не знали и даже с избранного, плейлисты все пиратские, они переодически меняются, их также провайдеры блокируют, плейлисты только покупать, если влом постоянно искать каналы))))

Nope, its not a pirated tv...


thanks!!

**Comment by AndreyPavlenko** [comment]
> if u need a real link from logo url, i can send u in private, ok?

Please, send me the link, I'll check.

**Comment by sherere** [comment]
> Please, send me the link, I'll check.

Sent to u in XDA private msg ok?

Thx!

**Comment by AndreyPavlenko** [comment]
Could you please check this https://github.com/AndreyPavlenko/Fermata/releases/tag/test version?

**Comment by sherere** [comment]
It worked like a charm!!!

Many thanks!!
![Screenshot_20211213-204152_Fermata Auto](https://user-images.githubusercontent.com/86202900/145906611-ead1207e-7100-4bf7-9ad9-f0c2e4dfb0a7.jpg)
