### ISSUE TITLE
Fermata license

### ISSUE THREAD

**Issue by moneytoo** [AndreyPavlenko/Fermata#11]
Hi,

Can you please clarify on under what license is the Fermata source code? Ideally even pick and include one in this repo. I'm asking because I'm trying to include your app (link to this repo) in a list of FOOS Android apps at https://github.com/offa/android-foss but that actually requires to know the license.

Thanks

**Comment by AndreyPavlenko** [comment]
Added license file 2c758961aca0a0c10a1f7faa453f1cd352d703a5
