### ISSUE TITLE
[REQUEST] Fermata auto and Fermata Control as one app

### ISSUE THREAD

**Issue by malebuffy** [AndreyPavlenko/Fermata#112]
I have split screen android auto on an Audi A6 4G with modded gal.json, where I can have two applications at the same time.
![20211220_084627](https://user-images.githubusercontent.com/23300461/146803490-ecab2011-eea5-4ee5-8e2b-92bd6e1bf1db.jpg)
The problem is that Fermata Auto only plays on the big left part. When I try to switch, only Fermata control plays at the right side which doesn't have video.
![20211220_084610](https://user-images.githubusercontent.com/23300461/146803701-33acda86-7435-4f41-bc61-445152229c3a.jpg)
Is there a possibility to fuse the two applications in one like spotify? You see Spotify is only one applications,  but can be shown also in the left and at the right side.
![20211220_084723](https://user-images.githubusercontent.com/23300461/146803878-e64581ff-824e-4780-b344-5553a3ab6197.jpg)
![20211220_084710](https://user-images.githubusercontent.com/23300461/146803897-31ae9239-ae82-446f-8dee-52f959bbd5ce.jpg)

Target is to have large part as navigation, and small part as small video screen.

Thanks for considering.

**Comment by AndreyPavlenko** [comment]
Unfortunately no. Control is just a workaround, that is used to enable the steering wheel buttons.

**Comment by EdmiltonJr** [comment]
Can you tell us where we get information on how to make Android Auto look like this, with both apps on the screen in the foreground, @malebuffy ?

**Comment by malebuffy** [comment]
Look at this article 

Basically you have to edit the gal.json file in the MIB2 device.

I did that by installing MIB2 Toolbox (https://github.com/jilleb/mib2-toolbox), patching AA with it and editing the Backup file the patch creates, according to the above link (change DPI to 103). Then restoring from Backup which copies the edited file back to the system.
Done
