### ISSUE TITLE
Voice search on YouTube??

### ISSUE THREAD

**Issue by Jotay2k** [AndreyPavlenko/Fermata#114]
In the 1.8.8 versión, while driving, u can touch the search Button then the voice "icon" display on the center of the screen and u can Talk to do the search.
But on the new versión 1.8.10, the voice control dissapear? I have accepted all permissions and nothing happens.... What i'm doing wrong?
Thanks and keep making it posible.

**Comment by AndreyPavlenko** [comment]
I'll check, but it should work. If it doesn't, you may use the floating button and the prev/next steering wheel buttons (should be enabled in settings).

**Comment by ertmuirm** [comment]
I'm on 1.8.10 and the voice search works for me when pressing the search button on the YouTube web app, but does not work when using the floating button / prev / next controls (despite it being enabled in settings)

For steering wheel controls to activate voice, do we need Fermata Control app installed?

**Comment by AndreyPavlenko** [comment]
Yes, you need the Fermata Control app for the steering wheel controls.
Long press on the floating button should activate the voice control. Make sure that you have granted the audio record permission. Try to disable/enable the voice control.

**Comment by ertmuirm** [comment]
Thank you! I tried it with the Fermata Control app and it works well. (Long press for voice control via the AA HU screen still doesn't work.)

However, at the start of each drive, I need to open the Control app before AA directs the Media Control Intents to it (default seems to be YouTube Music which I use in the car too). I wonder if this is normal behavior?

When Fermata Control is installed, it also takes the place of the "background app" in the app switcher icon on the navigation bar. Fermata Auto no longer appears. So if one wants to toggle between say Maps and Fermata Auto, it is not possible to do this without going back to the AA app drawer each time

**Comment by AndreyPavlenko** [comment]
The floating button long press should also work. Have you tried on phone?

The control app should be started automatically, when you start Fermata Auto.

**Comment by ertmuirm** [comment]
Yes, tried on the phone but the floating button does not work either (whether with AA on or off)

So far, the control app needs to be selected in the app menu for the steering buttons to work. I will try manually launching FermataMediaServiceControl service via am startservice when AA starts to see if the control app works upon startup ...

**Comment by AndreyPavlenko** [comment]
What happens on the floating button long press? Could you please record a video?

**Comment by ertmuirm** [comment]
nothing happens ... it just defaults to whatever function the floating button was representing at that time upon "button up" action. can try to record a video later but honestly it won't show anything more than what I am describing above

**Comment by AndreyPavlenko** [comment]
The default action is to show menu, if the voice control action is not enabled in settings.

**Comment by ertmuirm** [comment]
This problem seems to be fixed on 1.8.11, thanks!
