### ISSUE TITLE
Keeps crashing since one UI 4.0 update

### ISSUE THREAD

**Issue by Digilydeez** [AndreyPavlenko/Fermata#115]
Fermata auto keeps crashing since I did the samsung one UI 4.0 update on my phone. I can run the app on my phone no problem but when I plug it in my car it wont even open. What can I do to fix that?

**Comment by AndreyPavlenko** [comment]
Have you updated to Android 12? The only solution - downgrade AA to 6.9.

**Comment by Digilydeez** [comment]
It worked thank you!

**Comment by AndreyPavlenko** [comment]
Duplicate of #113
