### ISSUE TITLE
Disable fullscreen 

### ISSUE THREAD

**Issue by BenjaminKobjolke** [AndreyPavlenko/Fermata#116]
Is there a way to disable fullscreen? 
I want to keep my android button bar at the bottom visible while a video is playing.

**Comment by AndreyPavlenko** [comment]
Try to press the up arrow button in the bottom left corner, while playing a video.

**Comment by BenjaminKobjolke** [comment]
This will show a row with icon-buttons.
But still won't show the android navigation bar.
![20220110_Fermata](https://user-images.githubusercontent.com/5636473/148791297-9360ff7b-b39b-4034-b35b-de210591b021.jpg)

**Comment by AndreyPavlenko** [comment]
Added option "Show system bars on video touch" to Settings > Video.

**Comment by BenjaminKobjolke** [comment]
Thanks a lot! This is my favourite videoplayer and this makes it even better.
