### ISSUE TITLE
Netflix Fehlermeldung

### ISSUE THREAD

**Issue by Knarf1607** [AndreyPavlenko/Fermata#117]
Netflix funktioniert mit Anmeldung und Trailer. Beim Starten des Files kommt Fehler netflix m7121 1331.
Laut Netflix soll es ein Problem des Browsers sein. 
Verwendet Fermata die aktuellste HTML Version ?
Gruß Frank

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/37#issuecomment-920165923
