### ISSUE TITLE
Youtube controls on cars without touchscreen

### ISSUE THREAD

**Issue by tackletackle1** [AndreyPavlenko/Fermata#12]
Hi.
First of all I must say I really like your app. Now for the problem.
I have 2020 Mazda 3 without touchscreen. Youtube works as intended but it does not highlight where the "cursor" is currently. So using youtube becomes a guessing game. Could you add some kind of highlight on currently selected option in browser similar to hover highlight option in CSS. Also as far as I can tell my car control wheel works as intended for navigating your app. It is just that everything looks the same on youtube so you can't know which link you are selecting. If you need someone to test it I'm in.
Ty

**Comment by AndreyPavlenko** [comment]
Actually Youtube is just a web page http://m.youtube.com in the built-in browser. This is not a Youtube app.

**Comment by GZusTT** [comment]
Hey, I'm having the same issue. I know it's a web page however, is there some way for us to identify where the cursor is. Without a touch screen we have to use the knobs to move and guess which item is selected. It'll be really helpful if we can know where we're  at when browsing

**Comment by Alejandro2454** [comment]
Hola Andrey,  para quienes no tenemos pantalla táctil y solo usamos la
rueda de control seria excelente acceder al cursor
Saludos
Alejandro

**Comment by SBachman** [comment]
> 
I also think that's what they meant.

I have a Mazda as well and they completely disable the touchscreen with android auto. When trying to use fermata you can't see what your selection is which makes it near impossible to use and navigate.

**Comment by AndreyPavlenko** [comment]
Try this version - https://github.com/AndreyPavlenko/Fermata/releases/tag/1.9.4

**Comment by ikt32** [comment]
Sadly, even with 1.9.4, there is no indicator of the current selection. The controls do seem to work as I can scroll and get videos to play, but I don't see what I'm doing.

**Comment by ikt32** [comment]
@AndreyPavlenko 
Thanks for looking into it :)
It seems like I still cannot see a cursor or selection indicator. Pressing the `Back` just moves focus from Fermata Auto to Android Auto's bottom taskbar itself.

What setup/vehicle was this update developed for/tested on?

**Comment by AndreyPavlenko** [comment]
Make sure D-pad navigation is enabled in settings. I tested on emulator only, but several users confirmed it to work on real devices.

**Comment by ahhl** [comment]
i can confirmed the cursor works on merz gla2022.
but after awhile of using it, i cant exit to other main menu such as tv or play list etc even after pressing back button many times

it works to select utube. but fast scrolling doest work if i press hold the dail.

**Comment by SBachman** [comment]
At least the dial in my Mazda, both YouTube and browser don't show any indicator when the setting is on

**Comment by AndreyPavlenko** [comment]
> but after awhile of using it, i cant exit to other main menu such as tv or play list etc even after pressing back button many times

The first "back" button press shows the cursor. The second press should acts as the normal "back" button press.

**Comment by AndreyPavlenko** [comment]
> At least the dial in my Mazda, both YouTube and browser don't show any indicator when the setting is on

Could you send me the log after using dpad /sdcard/Android/data/me.aap.fermata.auto.dear.google.why/files/Fermata.log?

**Comment by ahhl** [comment]
> > but after awhile of using it, i cant exit to other main menu such as tv or play list etc even after pressing back button many times
> 
> The first "back" button press shows the cursor. The second press should acts as the normal "back" button press.

not working even after pressing many times.
