### ISSUE TITLE
Fermata Auto keeps crashing

### ISSUE THREAD

**Issue by ChrisAlexRoss** [AndreyPavlenko/Fermata#124]
I have installed using AAAD and KingInstaller and Fermata Auto still crashes in Android Auto. It works on the phone just fine, but doesn't work in the car.

**Comment by AndreyPavlenko** [comment]
Do you have Android 12?

**Comment by mrventerj** [comment]
@AndreyPavlenko , Hello!  I have the same problem, I do indeed have Android 12, I have also tried to use the new version, using King installer. Fermata still crashes in android auto.

**Comment by AndreyPavlenko** [comment]
There is a separate thread for Android 12 issues - https://github.com/AndreyPavlenko/Fermata/discussions/121

**Comment by mrventerj** [comment]
@AndreyPavlenko Thank you and for all the work you put into this app.

**Comment by ChrisAlexRoss** [comment]
Thank you! Your app is awesome
