### ISSUE TITLE
IPTV list not showing anymore

### ISSUE THREAD

**Issue by cruzer619** [AndreyPavlenko/Fermata#125]
i've been using IPTV for awhile on Fermata Auto.  after upgrading to 1.8.11 my iptv channel list disappeared.  now only shows channels: 0 groups: 0.  using  this https://iptv-org.github.io/iptv/countries/us.m3u.  I tried clearing cache first.. then I cleared data.  Still shows 0.  i've also tried reinstalling app and still same issue.  Please advise.

NOTE: and also all other functionality works fine.  youtube, file/web browser.

**Comment by podimonanil** [comment]
For me too...
My IPTV playlists are gone...

**Comment by AndreyPavlenko** [comment]
This https://iptv-org.github.io/iptv/countries/us.m3u playlist has an empty tvg-url:
#EXTM3U **x-tvg-url=""**
The parser fails to process the empty url. I'll fix the parser to ignore empty urls.

As a workaround, you may save the playlist in a file, remove the **x-tvg-url=""** tag and add this file to the app as a TV source.

**Comment by cruzer619** [comment]
Thanks updated the file manually workaround working great.. thanks..

**Comment by princepeace** [comment]
Hi, similar issue now occurring in version 1.9

**Comment by jtestacc1** [comment]
Latest version, but cannot upload a list, I tried using a manual file but no luck.

**Comment by AndreyPavlenko** [comment]
Could you send me the file?

**Comment by senthilkumar910** [comment]
Hi
