### ISSUE TITLE
White screen on YouTube 

### ISSUE THREAD

**Issue by majstermsi** [AndreyPavlenko/Fermata#129]
On 1.8.11 YouTube is corupted ... White screen after few movie clips. Good job with resume Play after for example reverse camera.

**Comment by MickLesk** [comment]
Android 12?

Update Android Auto...
https://android-auto.de.uptodown.com/android

**Comment by langka774** [comment]
Got the same issue. After a few playback, fullscreen went blank/black. The whole player become unusable, it cannot even show the setting and media control button

**Comment by majstermsi** [comment]
Like on moovie
https://youtu.be/hMCnyuX__rc

**Comment by majstermsi** [comment]
I have never had this issue im earlier builds. However this build fixed auto resume . IT is good direction.

**Comment by AndreyPavlenko** [comment]
Could you send me the log file /mnt/sdcard/Android/data/me.aap.fermata.auto/files/Fermata.log?

**Comment by majstermsi** [comment]
IT is ... Empty.
![Uploading IMG_20220210_002246.jpg…]()

**Comment by majstermsi** [comment]
[Fermata.log](https://github.com/AndreyPavlenko/Fermata/files/8036855/Fermata.log)

**Comment by majstermsi** [comment]
it is probably from last sesion ...

**Comment by majstermsi** [comment]
mayby this one is better.
[Fermata.log](https://github.com/AndreyPavlenko/Fermata/files/8036879/Fermata.log)

**Comment by majstermsi** [comment]
IT is always when minimalising fermata.

**Comment by majstermsi** [comment]
![Uploading IMG_20220210_004741__01.jpg…]()

**Comment by majstermsi** [comment]
![Uploading IMG_20220210_004741__01.jpg…]()

**Comment by majstermsi** [comment]
When I AM skipping tracks on YouTube IT is ok however just minimalising fermata issue is cery fast visible

**Comment by majstermsi** [comment]
https://youtu.be/3trts2zHcj8
Maybe Control...

**Comment by AndreyPavlenko** [comment]
What's your AA version?

**Comment by majstermsi** [comment]
7.3.620504

**Comment by majstermsi** [comment]
On 7.2 the same. I can try 6.9...

**Comment by majstermsi** [comment]
6.9 IT is forbiden. After 6.9 when connect to car IT is updating to 7.2

**Comment by majstermsi** [comment]
Issue is 1000% when fermata is just turning minimalised so even when rear cam is switched on when driving in back.

**Comment by AndreyPavlenko** [comment]
Seems I've reproduced the issue, but currently I don't understand why it's happening.

**Comment by majstermsi** [comment]
Hmm  if you need more tests I can provide. On 1.8.10 IT was ok however auto resume didnt work.

**Comment by AndreyPavlenko** [comment]
Seems this issue is AA specific. Can you reproduce the issue on the phone? Hide/show the app and press next.

**Comment by majstermsi** [comment]
Rock solid stable on phone oneplus 8t

**Comment by AndreyPavlenko** [comment]
I'm unable to reproduce on the tphone. Are you connected to AA?

**Comment by apollotsantos** [comment]
I am also having this problem. Galaxy note 9 on Android 10.

**Comment by KobyPitz** [comment]
Have the same issue.
Android version 12.
Galaxy s21+
Fermata:  1.8.11 (189)

Any solution?

**Comment by KobyPitz** [comment]
> Android 12?
> 
> Update Android Auto... https://android-auto.de.uptodown.com/android

Doesn't help

**Comment by KobyPitz** [comment]
Downgrading Fermata to version 1.8.10 fixes the issue.

**Comment by langka774** [comment]
> Downgrading Fermata to version 1.8.10 fixes the issue.

Can't downgrade. I'm using AAAD for Fermata installation. Is there a workaround?

**Comment by KobyPitz** [comment]
> > Downgrading Fermata to version 1.8.10 fixes the issue.
> 
> Can't downgrade. I'm using AAAD for Fermata installation. Is there a workaround?

Uninstall current versions of Fermata and Controller. Download version 1.8.10 and install the apps by using Kinginstaller https://www.terabox.com/web/share/link?surl=ubOyWVRjNrAh8ISOvvJzTg
You don't need AAAD at all.

**Comment by gokselerman** [comment]
In the 1.8.11 version, I solved the white screen problem during the part change on Youtube by installing the 1.8.10 version.

Android Auto 7.8.622514
Samsung S20 Fe Android 12

**Comment by mohellebi-mounir** [comment]
On 1.8.9. white screen after 3 or 4 youtube videos on a playlist. Nothing to do to fix untill unplug/plug data cable.

**Comment by zerro4cool** [comment]
I investigated a little and concluded that the problem with the white screen appears only when the parking sensors detect something (popup window from car soft appear). After that, only 2-3 videos are still working

**Comment by mohellebi-mounir** [comment]
Hi,

Even on the road without parking sensors, the white screen appear after 3
or 4 videos.

I think it has nothing to do with parking sensors even doors sensors.

Best regards,

Le dim. 25 déc. 2022 à 07:35, zerro4cool ***@***.***> a
écrit :
