### ISSUE TITLE
Landscape controls

### ISSUE THREAD

**Issue by JetsonQC** [AndreyPavlenko/Fermata#13]
Firstly, I want to say that Fermata Auto is the best App since a long time. Using the rooted version and it's awesome (for audio only and video too).
Only thing that could be improved would be to have the possibility to move the control bars (both control and menu bar) to the side on landscape screen (especially on Android Auto screen).
And again, fantastic app!

**Comment by AndreyPavlenko** [comment]
Added to my TODO list. Will implement when I have time.
Btw, there is an option to hide the menu and top bar - click on the arrow near the playback timer.

**Comment by JetsonQC** [comment]
Thanks for your hard work.
I know I can hide it but, especially while driving, it's difficult to use it when it's hidden (click to show and use).
I'm sad I can't help with coding as I don't know Android coding at all.
Thanks again!
