### ISSUE TITLE
Shuffle Issues?

### ISSUE THREAD

**Issue by Bumcha** [AndreyPavlenko/Fermata#132]
Shuffle forward works but repeates a lot of the same songs or videos.

And when you go back it should play the last but it also shuffles back.

**Comment by AndreyPavlenko** [comment]
The same song is repeated when all other songs in the same folder have been played.
Yes, go back does not play previous.

**Comment by lprawita** [comment]
Somehow, it repeats the same songs again and again. I have 1500++ files inside ONE folder. It seems to play the last files a lot (e.g. it plays files beginning with letter Z more than others, strange but true).

**Comment by AndreyPavlenko** [comment]
Should be fixed by #52
