### ISSUE TITLE
How to handle the case that PORT and SHARE are not specified in SMB? 

### ISSUE THREAD

**Issue by NanyangTaiji** [AndreyPavlenko/Fermata#133]

**Comment by AndreyPavlenko** [comment]
Port is optional. Share is the shared folder name.

**Comment by NanyangTaiji** [comment]
What happens if all the smb drive is shared? No specific folder(s)?

**Comment by AndreyPavlenko** [comment]
Each share is identified by a name. You must have specified the name, when creating the share.

**Comment by NanyangTaiji** [comment]
Can I make the "share“ optional? No shares are specified in all my organization. Check Android VLC player, only "user name" and "password" are needed.

**Comment by AndreyPavlenko** [comment]
VLC queries the server for the publicly visible share names and then you select the required share. Fermata does not have this functionality, thus you have to enter the share name manually.
Actually, the server is not required to return the list of shares. My server is configured to do not list the share names and VLC does not see any folder, until I specify the share name explicitly.

**Comment by NanyangTaiji** [comment]
I attach several portable drives to my router, which is identifed as LINKSYS30944. In VLC and other apps, LINKSYS30944 is shown. After clicking it, all the volume names of the portable drives are shown.

**Comment by AndreyPavlenko** [comment]
What is the error?
I think, you should check the share name in the router configuration.

**Comment by AndreyPavlenko** [comment]
JCifs is just a java library that implements the CIFS/SMB protocol. This app uses smbj.
