### ISSUE TITLE
Nice project, but for mts/m2ts type of video, exoplayer plays without sound, vlc does.

### ISSUE THREAD

**Issue by NanyangTaiji** [AndreyPavlenko/Fermata#134]
mts/m2ts audio codec is AC3, which is included in ffmpeg extension. Just wonder why it does not work.

Please verify with the following two clips:
https://we.tl/t-RM6TKf1JN2
https://we.tl/t-0FrOmwzgXe

**Comment by AndreyPavlenko** [comment]
Seems this format is not supported by ExoPlayer https://github.com/google/ExoPlayer/issues/1488
