### ISSUE TITLE
Scrolling control is so hard on YouTube. 

### ISSUE THREAD

**Issue by svenedik** [AndreyPavlenko/Fermata#136]
This is a great app for android auto. Thank you for your all efforts.

I have a problem with the YoutTube tab. My problem is scrolling...
Scrolling control is so hard on YouTube. Because when I drag my finger to scroll down, it clicks where I lifted my finger. 

Could you add the page up/down buttons for scrolling on the YouTube tab?

**Comment by AndreyPavlenko** [comment]
I don't have this issue on my device, scrolling works properly.

**Comment by svenedik** [comment]
I will share a video about my problem reason.
