### ISSUE TITLE
enable getting player app via fDroid or direct apk download

### ISSUE THREAD

**Issue by TheOtherDoctor** [AndreyPavlenko/Fermata#14]
As far as I can see, currently the only way to get the player is via Google Play store, where it can be downloaded for free.
Consequently, users of degoogled Systems or alternative ROMs are excluded from using it.

Please enable getting the app via fDroid, or referring to another source to download the apk directly.

**Comment by Alejandro2454** [comment]
Estimado,
Aquí tienes los enlaces
Saludos
https://github.com/AndreyPavlenko/Fermata/tags

**Comment by TheOtherDoctor** [comment]
Thanks a lot for the hint, I guess it is common that packages can be found under tags... didn't know.
