### ISSUE TITLE
YouTube and Web browser is not work on new AA

### ISSUE THREAD

**Issue by antony85** [AndreyPavlenko/Fermata#147]
YouTube and Web browser is not work on new AA

 Fermata app on New AA cannot find out YouTube and Web browser function button

**Comment by AndreyPavlenko** [comment]
Have you installed the app with KingInstaller?

**Comment by antony85** [comment]
I  installed the app with AAAD
mush be installed the app with KingInstaller?
Or need root ?

**Comment by AndreyPavlenko** [comment]
AAAD should also work. Have you enabled unknown sources in AA settings? Are you sure you start Fermata Auto but not Fermata Control? Make sure that youtube and web browser addons are enabled in settings.

**Comment by jaylex32** [comment]
Yeah the new AA broke the button functions you can't press any of the buttons,a work around to use YouTube is to change the settings to open YouTube at start.

**Comment by jaylex32** [comment]
The APK that is post it in here doesn't show in android auto?

**Comment by antony85** [comment]
I have reinstall now is work thx

**Comment by OvchiyantS** [comment]
Cant see Youtube and Browser buttons in AA 
Installed Fermata trough KingInstaller
Version Fermata 1.9.9

**Comment by AndreyPavlenko** [comment]
For Android 14 see here - https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by MICHAIL974** [comment]
Не вижу кнопок Youtube и браузера в AA, Видео тоже нет только звук,Версия Фермата 1.9.9, после подключения AA Wireless нет никаких изменений. Разработчик включен, все разрешения есть. SAMSUNG A55, Android 15. Это можно решить?
