### ISSUE TITLE
Can't run fermata auto in the background 

### ISSUE THREAD

**Issue by Oumanek** [AndreyPavlenko/Fermata#148]
Can't use fermata control
Can't run fermata auto in the background

**Comment by Salafi83** [comment]
I have the same issue.

**Comment by AndreyPavlenko** [comment]
Please, provide more details. Fermata Auto works in background, except Youtube.

**Comment by Oumanek** [comment]
You are right I am talking about YouTube
So I can't to just audio from YT in tha background
Thanks for your respond

**Comment by saveplayer89** [comment]
Do reftour money if services can’t work till now one day not worked yet
