### ISSUE TITLE
youtube playback in background?

### ISSUE THREAD

**Issue by DirtYiCE** [AndreyPavlenko/Fermata#15]
When starting a youtube video, the playback automatically stops when Fermata goes to the background (I open home screen or switch to an another app) and the notification disappears. When I go back to Fermata and click on play, it start to play the video from the beginning. Stopping the playback might make sense for videos, but it's pretty annoying when I just want to listen to some music. (However, normal video continues to play in the background).
Interestingly, when using Android Auto, youtube continues to play in the background if I switch to a different app (at least in the desktop head unit emulator). If I disconnect the auto, the playback stops but the notification remains. If I click on the play button in notification, it actually starts to play in the background, but this makes the app completely buggy and I can't use the UI until I force stop the app.

**Comment by AndreyPavlenko** [comment]
The app had been banned from Google Play due to this background playback. I had too remove this functionality, but, seems, some bugs are remaining.

**Comment by DirtYiCE** [comment]
Oh, so it's a "feature". It apparently works fine if I downgrade to 1.7.0.
I didn't even knew this app was on play store. So unauthorized android auto usage is ok, but god forbid from playing a youtube video in the background? Google is weird as always.
