### ISSUE TITLE
Hide unused buttons / Change order

### ISSUE THREAD

**Issue by daloes** [AndreyPavlenko/Fermata#159]
I was wondering if it would be possible to add capability to hide buttons on menubar (folder, favorites, playlists).
There is already possibility to hide YT, TV and browser buttons in addons

Given that I do not use playlists and Folders they just take valuable space and the buttons I do use (browser, tv) are hidden behind the menu button. Or maybe changing the order would also work as that would hide those extra buttons under menu

**Comment by AndreyPavlenko** [comment]
You can change the order - long press on a button.

**Comment by daloes** [comment]
Why didn't I think of trying that 🤦‍♂️ 
Thanks a lot keep up the great work!
