### ISSUE TITLE
Can't Add folder from "content" path 

### ISSUE THREAD

**Issue by FastenM** [AndreyPavlenko/Fermata#162]
Every time i try to add a folder from the "content" path 
The built in "google files" app opens up for a second but then closes right after.

**i'm doing this from the phone not the car screen.

**Comment by AndreyPavlenko** [comment]
This "google files" app is the system app and I don't have much control over it. Have you tried the same on a different device?

**Comment by FastenM** [comment]
No, i only have 1 device

**Comment by FastenM** [comment]
> This "google files" app is the system app and I don't have much control over it. Have you tried the same on a different device?

I dont know what to do, ive even already cleared the data of the app, uninstalled and reinstalled fermata auto and whenever i try adding something from the "content" folder the internal google files app loads for a second and shuts itself down, i also have the issue when trying to import settings or export settings, 

Just to note when it does load for a second its already loaded on a specific file path (whatsapp media) and not the home screen path (internal storage main list of folders)

Any help?
