### ISSUE TITLE
Adding new files.

### ISSUE THREAD

**Issue by Wolfers77** [AndreyPavlenko/Fermata#163]
I go to add files from my camera  files, dcim, and when I do it will add the folder name but with no files in it.

**Comment by Wolfers77** [comment]
I have jpeg. And mp4 files in there

**Comment by AndreyPavlenko** [comment]
Jpeg files are filtered out, but mp4 files should be listed in the folder.

**Comment by Wolfers77** [comment]
Ok, well just one more quick question since your answering back nice and quick, what is the difference between your app through Google app store compared to your app through AAAD?

**Comment by AndreyPavlenko** [comment]
The Google Play version does not support video in Android Auto.

**Comment by Wolfers77** [comment]
Ok so I have to delete my download from Google play and somehow get your other version.

**Comment by Wolfers77** [comment]
Ok, well thanks, I'll have to see how I can get the one not from playstore.

**Comment by Wolfers77** [comment]
Anyone know how??

**Comment by AndreyPavlenko** [comment]
https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/

**Comment by Wolfers77** [comment]
When I got the one from playstore I downloaded it,  opened it and when I went to my android auto it was on there as an app. Now when I downloaded the new one from the link you sent and downloaded the manual version apk, opened it, went to my android auto it's not there. What the hell am I doing wrond?

**Comment by AndreyPavlenko** [comment]
It's not sufficient to just install the apk. Please, read the instruction. Use KingInstaller to install the apk and enable unknown sources in the AA settings.

**Comment by Alejandro2454** [comment]
Debes desintalar y luego instalar  usando Kinginstaller

**Comment by Wolfers77** [comment]
I'm really having a brainfart sry, the arm.apk or arm64.apk

**Comment by Wolfers77** [comment]
Sry disregard that ,my bad, I know
