### ISSUE TITLE
Hello shuffle while watching video problem 

### ISSUE THREAD

**Issue by kerembakal401** [AndreyPavlenko/Fermata#17]
Hello shuffle while watching video problem ?

Although shuffle is turned on when watching videos, it plays the same videos in shuffle every time.  It starts to become annoying after a certain period of time.  I would be grateful if you could solve this problem.

**Comment by AndreyPavlenko** [comment]
The shuffle option does not change the files order in the list, but it plays files in a random order. Alternatively, you may try the random sort option in the top right corner.
