### ISSUE TITLE
switching music with the keys on the steering wheel

### ISSUE THREAD

**Issue by YRka150** [AndreyPavlenko/Fermata#172]
Good afternoon!
Tell me, please, why is it impossible to switch the music with the keys on the steering wheel, but it is only possible to switch the volume?
Добрый день!
Подскажите, пожалуйста, почему невозможно клавишами на руле переключить музыку, а только возможно переключать громкость?

**Comment by AndreyPavlenko** [comment]
You need to install Fermata control.
