### ISSUE TITLE
Amazon prime not load video in web browser

### ISSUE THREAD

**Issue by KinG-InFeT** [AndreyPavlenko/Fermata#173]
Hi,

Amazon prima video not load into webbrowser.

Thie is error out:

Pagina web non disponibile
Impossibile caricare la pagina web all'indirizzo intent://app.primevideo.com/watch?gti=amzn1.dv.gti.0aac578c-537a-ab6b-8706-52eb1caaa5e1&time=163&territory=IT&ref_=atv_dp_atf_prime_sd_mv_resume_t1A3AAAAAA0wg0#Intent;scheme=https;package=com.amazon.avod.thirdpartyclient;end perché:

net::ERR_UNKNOWN_URL_SCHEME

**Comment by AndreyPavlenko** [comment]
Works on the latest version.
