### ISSUE TITLE
Fermata Auto no longer on screen

### ISSUE THREAD

**Issue by wydget** [AndreyPavlenko/Fermata#178]
Hello, as of today I can no longer see the icon for Fermata Auto. Fermata control is still there.

**Comment by miikew** [comment]
i also cannot see Fermata on app list for enabling in the car

**Comment by lazarevski** [comment]
The issue for me was that my Samsung Galaxy phone automatically disabled the app (due to not being used for X amount of time).

**Comment by miikew** [comment]
i still cannot see Fermata Auto in app list, i have NORD2 with latest upgrades, what to do ? pls help me

**Comment by shimritmalka** [comment]
I cant see the app on android auto. I have oneplus 9rt. How can I solve this problem?

**Comment by AndreyPavlenko** [comment]
The only solution is described here - https://github.com/AndreyPavlenko/Fermata/discussions/122#discussioncomment-4307775
