### ISSUE TITLE
Search button not working

### ISSUE THREAD

**Issue by Kobolkob** [AndreyPavlenko/Fermata#18]
Hi, when I try to search something in web browser pressing the search button, the google page doesn't show any result, showing the home page. The only way go search something is by using the voice search function.

Android auto version: 6.1.610544-release
Fermata auto patched with AA AIO TWEAKER v. 3.1

Any idea? 
Thanks.

**Comment by AndreyPavlenko** [comment]
It works for me.

**Comment by Kobolkob** [comment]
I already had this issue with carstream (tried version 2.0.4 and 2.0.5)...

**Comment by Kobolkob** [comment]
Maybe it van be a patched app problemi.. What version of AA AIO TWEAKER have you installed?

**Comment by AndreyPavlenko** [comment]
3.2.

**Comment by Kobolkob** [comment]
Thanks, i've tried with 3.2, but no luck...
