### ISSUE TITLE
m3u8 IPTV links

### ISSUE THREAD

**Issue by ayoung10** [AndreyPavlenko/Fermata#181]
Does the app support m3u8 IPTV links?
Specifically trying to get this one to load: https://npc.cdn.7livecloud.io/hls/live/BRI1/masterSD.m3u8

It just shows 0 channels and 0 groups.

Thanks

**Comment by AndreyPavlenko** [comment]
Sorry, but I don't have access to this url.

**Comment by ayoung10** [comment]
I think you might need to be in Australia for the link to work, could that be part of it?

**Comment by AndreyPavlenko** [comment]
Could you download the list and attach it here?

**Comment by ayoung10** [comment]
[https___npc.cdn.7livecloud.io_hls_live_BRI1_masterSD.zip](https://github.com/AndreyPavlenko/Fermata/files/9173023/https___npc.cdn.7livecloud.io_hls_live_BRI1_masterSD.zip)
Hope this works

**Comment by AndreyPavlenko** [comment]
It's not a play list. Just open it in a text editor. Please, refer to this https://en.wikipedia.org/wiki/M3U article for the playlist format description.
