### ISSUE TITLE
Fermata Auto stfp does not follow symlinks

### ISSUE THREAD

**Issue by rossowl** [AndreyPavlenko/Fermata#183]
I have estabilished connection to my nas via vpn and sftp, but folders are empty, because they are symlinks to disks.

**Comment by rossowl** [comment]
> I have estabilished connection to my nas via vpn and sftp, but folders are empty, because they are symlinks to disks.

Maybe in other words: folders in root are not symlinks, but folders inside folders are symlinks.

**Comment by AndreyPavlenko** [comment]
There is no such option on the client side.
