### ISSUE TITLE
Problem signing within web browser

### ISSUE THREAD

**Issue by ahhl** [AndreyPavlenko/Fermata#187]
I cannot sign in from car screen on web browser.  Not problem if I sign in from handphone

**Comment by AndreyPavlenko** [comment]
Have you tried switching to desktop mode?

**Comment by ahhl** [comment]
i tried just now ,enable desktop mode, still cannot type anything. the cursor just blinking there

**Comment by TheLegendMH12** [comment]
Yeah funny you bring this up bcuz a few months ago this exact thing was happening to me whenever I was trying to log in to certain accounts websites like  prime video, hulu, and Disney plus just to name a few. Does anyone know if this has gotten fixed yet or is this problem still occurring? I haven't been back to check it

**Comment by matzefirst** [comment]
I can sign in, but i must insert login and password every time. Is there a way to get autofill or someting like this? So when i come back to a page username and password get in automatically

**Comment by TheLegendMH12** [comment]
If there is I don't know how too and don't think it has been fixed yet. There are a lot of issues and bugs going on with this entire system man I've just about fucking had it with this crap. Don't think I can take much more.

**Comment by ahhl** [comment]
i can't sign in at all. the box just empty even after i type in names.
but if i run from hp the open up AA, it works

**Comment by ahhl** [comment]
i hope this still in the list.🙏 nothing appear on the screen whether use the phone keyboard or onscreen keybord

**Comment by ahhl** [comment]
still not fully ok. watch this video
https://youtu.be/ujNppeSl7TI?feature=shared

and for login to google account, this the problem
![IMG_20240113_170743](https://github.com/AndreyPavlenko/Fermata/assets/34929912/b67eee63-6477-4f9d-ace5-88632a2d5dac)
