### ISSUE TITLE
Support for m3u links instead of files?

### ISSUE THREAD

**Issue by malebuffy** [AndreyPavlenko/Fermata#19]
I am using a link  for my iptv player apps. On FernataAuto there is support for local files,Google drives,  ftp etc.  but not for links.

https://raw.githubusercontent.com/free-greek-iptv/greek-iptv/master/android.m3u

Since this link is always updated due to changes of sources, this will solve the downloading of the file every now and then. Any plans to support m3u links instead of files?

**Comment by AndreyPavlenko** [comment]
Yes, I've this feature in my todo list.

**Comment by AndreyPavlenko** [comment]
Implemented in [v1.7.5](https://github.com/AndreyPavlenko/Fermata/releases/tag/v1.7.5).
