### ISSUE TITLE
jpeg and mkv

### ISSUE THREAD

**Issue by nellobnn** [AndreyPavlenko/Fermata#2]
Andrey your app is very interesting and useful.
Some question:
I use m3u file and i have seen that if i use stream on live channel i can see the video but if i open a vod stream file (mp4 or mkv) i listen only audio (fermata shows audio icon). If I open local mp4 files I can see them.
Moreover it is not able to view photo format (es. jpeg). Fermat considers it as folder
It is possible to introduce this features?
Thank a lot

**Comment by AndreyPavlenko** [comment]
The first issue to be fixed.
Photos are not supported and should not be even listed in the player, neither as a folder nor as a file.
Can you see jpeg files (as folders) in the player?

**Comment by nellobnn** [comment]
Photos are seen as in attacched files. I can click on and I see a void folder...
![Screenshot_20200401-235423](https://user-images.githubusercontent.com/32793682/78190482-60f63d00-7474-11ea-8404-04db546a1134.jpg)
![Screenshot_20200401-235417](https://user-images.githubusercontent.com/32793682/78190484-62276a00-7474-11ea-9f9e-9565d29a9d4c.jpg)

**Comment by AndreyPavlenko** [comment]
Hm... for some reason, on your device, photos are considered as empty folders. I'm not able to reproduce this, on my device, photos are considered as files and are filtered out.

**Comment by nellobnn** [comment]
I found out why ... the folder is there with another jpeg file inside. My mistake.
My compliments for the app. I think that the control apk that allows to use without touch (with wheel streering) is an added value

**Comment by AndreyPavlenko** [comment]
Oh... it's rather a workaround than an added value. I didn't find a better solution for integration with Android Auto media buttons.
