### ISSUE TITLE
Voice control

### ISSUE THREAD

**Issue by rifuribe** [AndreyPavlenko/Fermata#20]
Please add voice searching command

**Comment by AndreyPavlenko** [comment]
There is integration with Google assistant, but, unfortunately, the assistant doesn't work very well for me. Try to configure assistant as described here - https://support.google.com/assistant/answer/7539710 .

**Comment by rifuribe** [comment]
> There is integration with Google assistant, but, unfortunately, the assistant doesn't work very well for me. Try to configure assistant as described here - https://support.google.com/assistant/answer/7539710 .

**Comment by rifuribe** [comment]
Google assistant integration works with the original Youtube using chromecast on any tv but it doesn't work yet with Fermata 😢

**Comment by AndreyPavlenko** [comment]
Google assistant has a very limited functionality in Android Auto. It's not a TV. Besides, Youtube in Fermata is just a web page, it's not a Youtube app. To be honest, I don't know how to integrate google assistant with youtube web page.
