### ISSUE TITLE
Error in ExoPlayer dependencies when trying to "compile" version 1.9.0

### ISSUE THREAD

**Issue by pepsik-kiev** [AndreyPavlenko/Fermata#204]
./gradlew packageAutoReleaseUniversalApk -PABI=arm64-v8a -PAPP_ID=me.aap.fermata.auto.dear.google.why

> Configure project :exoplayer
WARNING:abiFilters should not be declared in dynamic-features. Dynamic-features use the abiFilters declared in the application module.
Disabling ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM option because this is a dynamic-feature module. Dynamic-feature module is not supported by ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM yet.
Disabling ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM option because this is a dynamic-feature module. Dynamic-feature module is not supported by ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM yet.

FAILURE: Build failed with an exception.

* Where:
Script '/Fermata/depends/ExoPlayer/publish.gradle' line: 27

* What went wrong:
A problem occurred configuring project ':exoplayer-extension-cast'.
> Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

**Comment by AndreyPavlenko** [comment]
Try this:

echo > depends/ExoPlayer/publish.gradle

**Comment by pepsik-kiev** [comment]
Thx ! Works ...
