### ISSUE TITLE
Fermata Auto

### ISSUE THREAD

**Issue by Gabripaul** [AndreyPavlenko/Fermata#21]
Ho provato a visionare canali tv con file 3mu si sente ma il video non funziona, file 3mu sono acquistate, con aplicazia VLC funziona, Ce qualqe bug.Grazie

**Comment by AndreyPavlenko** [comment]
Open your m3u in a text editor and add this #EXT-X-MEDIA:TYPE=VIDEO tag:

#EXTM3U
#EXT-X-MEDIA:TYPE=VIDEO

**Comment by Gabripaul** [comment]
Non funziona neanche così, non lo so perché.

Il Lun 19 Apr 2021, 09:45 Andrey ***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
Please send me the list by email.

**Comment by Gabripaul** [comment]
http://besstavb.eu:8008/get.php?username=Paul_Gabriel&password=nuTZZTwM&type=m3u_plus&output=ts

Il Lun 19 Apr 2021, 09:45 Andrey ***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
For M3U urls there is support in the latest (1.7.6) version. You don't need to use files, Just add the url: Add Folder > M3U Playlist and check the Video playlist checkbox.

**Comment by Gabripaul** [comment]
Mi lo fai tu perfavore.

Il Lun 19 Apr 2021, 11:24 Andrey ***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
Install this version - https://github.com/AndreyPavlenko/Fermata/releases/tag/v1.7.6

**Comment by Gabripaul** [comment]
Ho questa versione già installata

Il Lun 19 Apr 2021, 11:42 Andrey ***@***.***> ha scritto:

**Comment by Gabripaul** [comment]
Forse riesci tu ha preparare il Files e mi lo mandi Grazie.

Il Lun 19 Apr 2021, 11:43 gabriel paul ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
Click on the Add folder button and select M3U Playlist

**Comment by Gabripaul** [comment]
Ho provato ,si sente ma non si vede

Il Lun 19 Apr 2021, 11:45 Andrey ***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
Have you checked the "Video playlist" checkbox when you added the URL?

**Comment by Gabripaul** [comment]
S, i ho fatto tutto,non funziona

Il Lun 19 Apr 2021, 12:11 Andrey ***@***.***> ha scritto:

**Comment by Gabripaul** [comment]
Con VLC funziona tutto

Il Lun 19 Apr 2021, 12:18 gabriel paul ***@***.***> ha
scritto:

**Comment by Gabripaul** [comment]
Grazie,  sono riuscito con playlist  Sei grande

Il Lun 19 Apr 2021, 12:23 gabriel paul ***@***.***> ha
scritto:

**Comment by Gabripaul** [comment]
Ciao scusa per il disturbo, c'è un problema con la applicazione, quando lo
chiudo di tuto poi non si apre più  devo cancellare i dati e rifare tutto
da zero.

Il Lun 19 Apr 2021, 13:40 Andrey ***@***.***> ha scritto:
