### ISSUE TITLE
Not working on Android 12

### ISSUE THREAD

**Issue by yashn3232** [AndreyPavlenko/Fermata#213]
Fermata auto is not working on oneplus android 12 fermata auto is not showing on car screen only fermata control is available on car screen Android auto version
Android Auto: 8.5.624594-release

**Comment by AndreyPavlenko** [comment]
Currently, this is the only solution for OnePlus - https://github.com/AndreyPavlenko/Fermata/discussions/122#discussioncomment-4307775
