### ISSUE TITLE
Fermata Auto not showing up anymore in Android Auto all of a sudden

### ISSUE THREAD

**Issue by Cr4z33** [AndreyPavlenko/Fermata#214]
Yesterday I've noticed that all of a sudden the app doesn't show up anymore into Android Auto, the same applies in the apps selection into AA smartphone settings (only Fermata Control is still there).

Can I do anything or did Google change something?

**Comment by daloes** [comment]
This happens to me from time to time. Just reinstall via aaad and it will reapper. Also check in AA on phone if it is not unchecked in menu list

**Comment by Cr4z33** [comment]
Thanks, using AAAD to reinstall worked now and I've got Fermata Auto showing up again in AA!

Strange to say that normal APK installation didn't make the trick... 🤔

**Comment by Cr4z33** [comment]
Me again.

This time uninstalling and reinstalling again (after disappearing from AA) didn't do the trick.

There's no way now to see Fermata Auto in AA.

**Comment by AndreyPavlenko** [comment]
Have you tried this installer https://github.com/fcaronte/KingInstaller/releases/tag/1.2 ?

**Comment by Cr4z33** [comment]
You did it again lol... worked at first try (although I wasn't aware of that app) thanks!

**Comment by AndreyPavlenko** [comment]
Thanks to @fcaronte !

**Comment by backslashV** [comment]
King installer, aaease, aaad no longer work. Tried with v1.8x and 1.9x of fermata with v9.1 and v9.3 of android auto.
