### ISSUE TITLE
m3u IPTV links

### ISSUE THREAD

**Issue by otromen02** [AndreyPavlenko/Fermata#216]
Hi,

Some IPTV link are not loading. Attached is the M3u file. The first link works, but the 2nd one didn't load. I tried using other IPTV app, no issue for both links. (OTT Navigator)

[IPTV.zip](https://github.com/AndreyPavlenko/Fermata/files/10370906/IPTV.zip)

**Comment by AndreyPavlenko** [comment]
I checked with the PC version of VLC and the second link does not work either. The server rejects connections.
If OTT Navigator works for you, then changing the user agent might help, but I don't know the UA string for OTT Navigator.
