### ISSUE TITLE
1.9.0 lost voice input 

### ISSUE THREAD

**Issue by sargenthp** [AndreyPavlenko/Fermata#219]
Am I missing something?  I cannot find a way to enable voice input again.  Now I just get a box to tell me the keyboard cannot show unless in park.

**Comment by sargenthp** [comment]
Found it within the Android app, not within AA.  Sorry.

**Comment by sargenthp** [comment]
Nope...  Condition still exists.  I can now use voice in YouTube, but unable to use it within the web browser.

**Comment by AndreyPavlenko** [comment]
Try the following voice commands:
find in browser "some query"
open in browser "bookmark name'

**Comment by AndreyPavlenko** [comment]
In the Settings > Voice control check the Floating button option.
