### ISSUE TITLE
Fermata error

### ISSUE THREAD

**Issue by AndresR85** [AndreyPavlenko/Fermata#22]
Hola buenas tardes,  al momento de ejecutar android auto la aplicación no aparece , en el teléfono funciona muy bien, pero en Android auto no aparece disponible.

**Comment by AndreyPavlenko** [comment]
Hello. How did you install the app?

**Comment by AndresR85** [comment]
Si, instale la aplicación

Get Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by AndresR85** [comment]
Sucede lo siguiente,  la aplicación en el teléfono abre y funciona muy bien pero al conectar el dispositivo para ejecutar Android Auto la app no aparece

Get Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Alejandro2454** [comment]
Hola, ¿Andrés, eres latinoamericano? ¿Eres root?

**Comment by AndresR85** [comment]
Hola , si soy de Colombia, no soy usuario Root

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alejandro2454** [comment]
Debes ser root. Sin embargo, existe una app. No root que usa fermata en
android auto.

**Comment by AndresR85** [comment]
Qye aplicación es?

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AndresR85** [comment]
Ya que descargue la app AAAD Y luego fermata

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alejandro2454** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.youtube.com/watch%3Fv%3DYwTUCiSJYUA&ved=2ahUKEwihns2Dr7HwAhU4qJUCHUEYAEAQ3e4CMAF6BAgDEAw&usg=AOvVaw3i_1cVOMINt8WN6uetTk4a

**Comment by AndresR85** [comment]
Ya realicé la descarga pero no tengo opción de descargar fermata auto hasta dentro de 30 días , me podría brindar opción para poder descargar la app. Le agradezco.  Muchas gracias

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
