### ISSUE TITLE
[Feature Request] Allow to force dpi / resolution to get fullscreen

### ISSUE THREAD

**Issue by aoterolorenzo** [AndreyPavlenko/Fermata#221]
As I understood, some apps from the typical AA boxes (like AAWireless) have the ability to make their applications force the dpi / resolution in order to be able to obtain the whole panel for them. Seems that AA would detect as the application doesn't fit the 3-way splitted screen and gives it the entire screen, just as a Bootstrap grid.

Also, in Android Auto developer options we have the ability to configure it to let applications negotiate the resolution (and idk if the fit).

I'm aware that the kind of AA boxes above mentioned is probably rooted and with several access to all that features, so I can't say easily if this is possible to implement, but it seems it would be a nice-to-have feature.

**Comment by aoterolorenzo** [comment]
Any plans on implement this feature @AndreyPavlenko ?

**Comment by aoterolorenzo** [comment]
![IMG_20230214_230100](https://user-images.githubusercontent.com/7276373/219423202-58ffc269-b8e4-46cd-933f-f765835d1a53.jpg)

Here is just an example. The Waze app is always staying in the screen. Can't find a way of getting real Fullscreen

Please could you tell if there is a way or if it could be implemented? @AndreyPavlenko

**Comment by AndreyPavlenko** [comment]
Currently, I don't know how to implement it.

**Comment by AndreyPavlenko** [comment]
Currently AA allows full screen only for the navigation apps.
