### ISSUE TITLE
Background Card behind the video file

### ISSUE THREAD

**Issue by italoboy** [AndreyPavlenko/Fermata#224]
![IMG_20230210_160503](https://user-images.githubusercontent.com/61342502/218248848-961f828e-0a49-4279-af55-036f5dcd10e4.jpg)

Looks like it is not possible to remove?!

**Comment by AndreyPavlenko** [comment]
Never seen such an issue. Is this card there only when playing video?

**Comment by italoboy** [comment]
It is there when playing any video file. Not on my phone but on my car screen.

**Comment by italoboy** [comment]
It is music player (card) of coolwalk, how to fix this?!

**Comment by italoboy** [comment]
Any update to fix this ?;

**Comment by AndreyPavlenko** [comment]
No updates. Unfortunately, I can't reproduce. Have you tried a different device, do you have the same issue?

**Comment by italoboy** [comment]
> No updates. Unfortunately, I can't reproduce. Have you tried a different device, do you have the same issue?

I've tried anything, this happens in coolwalk.

**Comment by AndreyPavlenko** [comment]
Fixed in 1.9.1.

**Comment by italoboy** [comment]
> Fixed in 1.9.1.

Great, tnx for fixing.
