### ISSUE TITLE
Fermata Auto Video Lagging

### ISSUE THREAD

**Issue by forenaite** [AndreyPavlenko/Fermata#225]
I noticed that android phones with Mediatek SoC have performance issues when playing videos with Fermata Auto.

Smartphones with Snapdragon do not seem to suffer from this problem.

I conducted a series of tests with several media files encoded with different codecs (h264, h265, hevc, dts, etc) and Full HD and HD resolutions, on mobile phones that have the following SoCs:

Mediatek Dimensity 8100-Ultra
Mediatek Dimensity 8100
Snapdragon 888
Snapdragon 845

I also tried all media engines available on Fermata Auto (Exoplayer, VLC and Mediaplayer).

In Snapdragon SoCs, all videos play without performance issues, and the multimedia center does not seem to suffer any kind of impact.

However, on Mediatek SoCs, after a few minutes playing videos, they start to lose frames and lag. The performance of the multimedia center is also compromised!

It seems that Mediatek chips are not as well optimized for video decoding as Snapdragon ones.

**Comment by AndreyPavlenko** [comment]
I can only recommend to try different video engines. By default, Fermata uses VLC.
