### ISSUE TITLE
Fermata TV at Android Auto only works with WiFi 

### ISSUE THREAD

**Issue by PoPeYe2000** [AndreyPavlenko/Fermata#226]
Hello, I use Fermata Auto in my BMW with Android Auto Coolwalk. Everything works great, Music, YouTube... , except for the TV function. When I'm online at home via WiFi in the app on my mobile phone, it works great. As soon as I'm in the car or using the mobile data, it no longer works. Youtube and everything else works by using Mobile Data but not the TV function. Mobile Data Speed is the same like WiFi Speed. 
What could be the reason for this?

**Comment by AndreyPavlenko** [comment]
Have you tried a different TV provider?

**Comment by PoPeYe2000** [comment]
I'm afraid I don't quite understand. What I can say is that these channels in the m3u list are usually not freely available. What I have also read is that the router (fritz box) can process m3u files accordingly. It's curious, with WiFi all channels work, with 4g or Lte, i.e. mobile data from the mobile phone, no channel works.

**Comment by AndreyPavlenko** [comment]
Some IPTV providers only allow access to their content only from their own network, but block access from any other networks. Probably, this is your case.

**Comment by lolo564y** [comment]
Bonjour, 
J'ai le même problème ; ma liste m3u ne fonctionne qu'en wifi alors que ça fonctionnait avant ! Ne serait-ce pas depuis la mise à jour de fermata ?

**Comment by AndreyPavlenko** [comment]
> Bonjour,
> J'ai le même problème ; ma liste m3u ne fonctionne qu'en wifi alors que ça fonctionnait avant ! Ne serait-ce pas depuis la mise à jour de fermata ?

Have you tried any other app? Does it work over mobile network?

**Comment by lolo564y** [comment]
J'ai trouvé c'est mon opérateur mobile qui bloque l'accès car cela fonctionne quand je passe par un vpn

**Comment by PoPeYe2000** [comment]
Et y a-t-il alors une solution à ce problème ici ? J'aurai alors certainement le même problème.

**Comment by lolo564y** [comment]
2 solutions : soit utiliser un vpn soit utiliser l'application 1.1.1.1 warp

**Comment by PoPeYe2000** [comment]
Malheureusement, cela ne fonctionne pas non plus avec cette application ou avec un VPN. Peut-être est-ce dû au fait qu'il s'agit de chaînes privées allemandes. Normalement, on ne les trouve pas dans les listes M3u. Dommage que cela ne fonctionne pas.
