### ISSUE TITLE
fermata 1.7.7 freezed

### ISSUE THREAD

**Issue by argy85** [AndreyPavlenko/Fermata#23]
![Screenshot_2021-05-09-21-36-56-357_com google android feedback](https://user-images.githubusercontent.com/83923947/117584956-2bf4f900-b110-11eb-812d-8da008f3adac.jpg)
![Screenshot_2021-05-09-21-36-16-433_com google android feedback](https://user-images.githubusercontent.com/83923947/117584957-2c8d8f80-b110-11eb-8bce-025949f1a059.jpg)
![Screenshot_2021-05-09-21-33-59-958_com google android feedback](https://user-images.githubusercontent.com/83923947/117584958-2d262600-b110-11eb-91ca-ef20bd3a1296.jpg)
![Screenshot_2021-05-09-21-33-52-662_com google android feedback](https://user-images.githubusercontent.com/83923947/117584959-2dbebc80-b110-11eb-9a7b-b41ae44390b8.jpg)

thanks for your job, I have an issue with the app.
when open app it still freezed, what I can do?
I have installed it with AAAD

**Comment by AndreyPavlenko** [comment]
Hi. On what operations does it freeze? I'm unable to reproduce.

**Comment by AndreyPavlenko** [comment]
Please try the new version 1.7.8

**Comment by argy85** [comment]
i have installed new 1.7.8 and seems to be ok, many thanks
