### ISSUE TITLE
video scaling (fit) doesn't work once fullscreen is selected

### ISSUE THREAD

**Issue by 22marco77** [AndreyPavlenko/Fermata#230]
Hi, congratulations on your application, it's fantastic. I just have a small request to make if it's possible to fix it in your next update of the application.
When I resize the image, with any player set, the image remains in its original version and does not fit the screen, leaving the two black side bands in the classic 4:3 format without going to fullscreen when I select fit.
Car stop version 1.9.0.
Huamei Mate 20 pro smartphone
Operating system Emui 12 android 10.
Thanks for the time you dedicate to this wonderful application and consequently to the whole community.

**Comment by AndreyPavlenko** [comment]
Are you talking about video player or youtube? Could you please attach a screenshot?

**Comment by 22marco77** [comment]
> Are you talking about video player or youtube? Could you please attach a screenshot?

I haven't actually seen youtube, the problem for me comes with the .m3u file that allows me to see live free TV channels. Whatever choice I make to adapt the video, it always remains in the 4:3 format with the black side bands, while the application is seen in fullscreen. If you need screenshots I can do that and email them to you if that's okay with you.

**Comment by 22marco77** [comment]
of course thanks for the time you are giving me, trying to fix this bug. Thanks again.

**Comment by AndreyPavlenko** [comment]
> > Are you talking about video player or youtube? Could you please attach a screenshot?
> 
> I haven't actually seen youtube, the problem for me comes with the .m3u file that allows me to see live free TV channels. Whatever choice I make to adapt the video, it always remains in the 4:3 format with the black side bands, while the application is seen in fullscreen. If you need screenshots I can do that and email them to you if that's okay with you.

Have you tried to change the media engine?

**Comment by 22marco77** [comment]
![Screenshot_20230223-094542](https://user-images.githubusercontent.com/24650739/220864270-14bf2aee-072d-40a2-ba62-687425c9f1a4.jpg)

Yes I tried other players but does not edit the image you can see from the screenshot. The format does not fit, even

**Comment by 22marco77** [comment]
![Uploading Screenshot_20230223-101813.jpg…]()
![Uploading Screenshot_20230223-101807.jpg…]()

**Comment by AndreyPavlenko** [comment]
Which scaling method is currently selected?

**Comment by 22marco77** [comment]
> Which scaling method is currently selected?

Suitable, but any choice I make the image does not change and remains in the format you see in the photo.

**Comment by 22marco77** [comment]
Andrey Pavlenko I'm sorry if I bother you, did you have time to look for some solution to the problem?

**Comment by AndreyPavlenko** [comment]
Not yet, sorry.

**Comment by 22marco77** [comment]
> Not yet, sorry.

ok thanks, I will wait hopefully you can find a solution, if you need the video I can upload it. If I can help you can ask.

**Comment by AndreyPavlenko** [comment]
Sorry, but I'm unable to reproduce. Have you tried a different video?

**Comment by marco7722** [comment]
I tried several videos and players, but without success. I can not set the view in full screen both choosing suitable that 16;9, the image is always stuck in 4:3. I don't know what to feel anymore

**Comment by AndreyPavlenko** [comment]
While playing a video, click on three dots in the bottom right corner -> Video -> Scaling.

**Comment by marco7722** [comment]
I have already done this test without any result, the video does not go in full screen and does not fit the screen, the strange thing is that the application goes in full screen without problems, only the video playback remains in 4: 3

**Comment by marco7722** [comment]
The problem occurs both with videos saved on the phone's memory and in the free-to-air TV's m3u file

**Comment by AndreyPavlenko** [comment]
I'm unable to reproduce. All video scaling options work for me.

**Comment by 22marco77** [comment]
I downloaded the latest version, the problem for me remained, I do not understand why the application opens in full screen, YouTube goes in full screen even the browser, only the file m3u does not go ... You could try with the m3u file yourself and see if you have the same problem...  https://github.com/Tundrak/IPTV-Italia

**Comment by AndreyPavlenko** [comment]
Fill screen option is enabled:

![image](https://github.com/AndreyPavlenko/Fermata/assets/1067755/8ce7a7f7-0c3c-48c3-abc9-834047eddd88)

**Comment by 22marco77** [comment]
Then I really have no idea what it could be. I tried with oneplus 6 and I always have the same problem. Mha.. I give up

**Comment by 22marco77** [comment]
![Screenshot_20230521_210730_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/1c9014a8-bc9a-4589-ae21-bef09c7759fc)

![Screenshot_20230521_210725_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/9bc794f0-d546-45c6-b5e7-0cc1e8d0c2c2)
🏳️

**Comment by 22marco77** [comment]
I found, if you can say so, I problem, I do not have to use the appropriate voice (which in Italian means adapting the image to full screen. But it cuts, which here means making it smaller. So I did not use crop but only suitable or 16/9. Cmq with crop goes in full screen. Thank you and sorry for disturbing you. Congratulations again for the magnificent application very very TOP

**Comment by AndreyPavlenko** [comment]
Thanks!

**Comment by AndreyPavlenko** [comment]
Actually, with VLC engine, the native VLC scaling options are used. The image is cropped if the screen aspect ratio does not match the image aspect ratio. For example, the screen is 16:9 and the image 4:3.

**Comment by 22marco77** [comment]
In fact the screen is 16: 9 and as I see the images are sent to 4: 3 but if I use the same do on VLC I can stretch without cutting the image, do not ask me how it is possible because I do not have much Knowledge in this, but adapt the image to the screen without finding the headless actors in the foreground images. Can't make sure that the suitable option can fill the screen without any cropping

**Comment by AndreyPavlenko** [comment]
Stretching 4:3 to 16:9 is possible, but the image is also stretched:
![image](https://github.com/AndreyPavlenko/Fermata/assets/1067755/264d068e-51b8-4752-acd8-00195850ad36)
The fill screen option does not stretch the image but crops.

**Comment by 22marco77** [comment]
![Screenshot_20230522_145431_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/00e020e2-a3ed-4eca-ab2a-0283bf87f3f0)

Crop

![Screenshot_20230522_145419_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/410b41d9-02c3-423c-be34-41a9866af5ef)

16:9

![Screenshot_20230522_145409_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/a5b9977c-cc02-42ac-9355-6185a1ea3168)

Original

![Screenshot_20230522_145359_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/ef33c8f5-189f-4fd4-ac4a-92121b132754)

4:3

![Screenshot_20230522_145347_me.aap.fermata.auto.dear.google.why.jpg](https://github.com/AndreyPavlenko/Fermata/assets/24650739/ed7ca0e5-5e15-41db-9c3c-132ab9af0976)

Suitable

These are the various format
