### ISSUE TITLE
Dropped TS stream from M3U8 playlist causes app to freeze/become unresponsive

### ISSUE THREAD

**Issue by nabeelr** [AndreyPavlenko/Fermata#232]
When watching streamed content, if the stream drops or starts lagging, Fermata becomes unresponsive/freezes for long periods of time.

A good example of this is this stream: http://n1.klowdtv.net/live2/gsn_720p/chunks.m3u8 or https://cdn.klowdtv.net/803B48A/n1.klowdtv.net/live2/gsn_720p/playlist.m3u8

If watched for long enough, the stream will eventually drop momentarily which will make the app freeze.

**Comment by AndreyPavlenko** [comment]
This is a known issue for the VLC engine. Try changing the engine.
