### ISSUE TITLE
Fermata auto won't open and cause crach of other apps

### ISSUE THREAD

**Issue by Kandaraa** [AndreyPavlenko/Fermata#233]
Hello 

I've recently installed fermara auto using kinginstaller. My phone connect well with the car and everything works well. When i try to open fermata auto it's freeze for around 3 sec and go back to map with blank screen as shown in the image:
![Android-Auto-blank-white-screen](https://user-images.githubusercontent.com/72318499/221321713-fc96343d-ed34-44e8-be24-57600a95cdc4.jpg)

This effect still happen even i remove the usb cable and reconect again. To make map work again i need to remove the car from my android auto and re-paired again.

Could you please help me with the solution.  I realy like the app and i want to use it

Thanks

Kandara

**Comment by AndreyPavlenko** [comment]
Unable to reproduce.
