### ISSUE TITLE
AA Coolwalk breaks Fermata Control & Fermata Auto

### ISSUE THREAD

**Issue by xMrRose** [AndreyPavlenko/Fermata#235]
AA Coolwalk seems to break Fermata Control and Fermata Auto.
What I have noticed:

Fermata version: 1.9
AA version: 8.8.630424
Android: 13

1) Fermata Control cannot play any sound - it seems to be muted in AA
2) Fermata Auto works, for example with youtube site, when on fullscreen. When it is minimized with Coolwalk view, sound breaks as described in (1) Fermata Control cannot play anything.
3) When attempt to restore Fermata Auto, it restores, but current player (Youtube) seems to be buggy. menu bar dissappears, and there is no possibility to bring it back. In restored app Youtube play is not stable, sometimes video is crashed. Cannot back to the previous menu. The only thing that helps is to force restart the application.

**Comment by AndreyPavlenko** [comment]
2. is expected. Youtube restricts background playback.

**Comment by xMrRose** [comment]
I can provide a movie if you need it.
