### ISSUE TITLE
car screen problem

### ISSUE THREAD

**Issue by Tatanka79** [AndreyPavlenko/Fermata#236]
![IMG20230227131428~2](https://user-images.githubusercontent.com/126612551/221955954-c9633fba-c756-41ee-a40d-924b76ab1649.jpg)
Hi Andrey, I am contacting you if it is possible to solve this gap that is created on the screen when I connect the app. Thank you

**Comment by AndreyPavlenko** [comment]
Does this gap exist when the bottom control panel disappears? By default, it disappears in 5 seconds or on touch.

**Comment by Tatanka79** [comment]
> Does this gap exist when the bottom control panel disappears? By default, it disappears in 5 seconds or on touch.

That's right, it appears when the panel disappears. I have also seen that it is not possible to leave it permanently. I've tried all possible variations, but I can't get that band off.

**Comment by AndreyPavlenko** [comment]
I mean the panel with stop, fw/rw buttons. It should disappear in 5 seconds.

**Comment by Tatanka79** [comment]
> I mean the panel with stop, fw/rw buttons. It should disappear in 5 seconds.

Yes, that disappears and I'm left with even wider bandwidth.

**Comment by AndreyPavlenko** [comment]
Is this issue reproducible on the phone or AA only?

**Comment by Tatanka79** [comment]
> Is this issue reproducible on the phone or AA only?

I just tried the app. With AA no problem. I tell you what, with youtube, I don't have this problem. YouTube on the app FERMATA

**Comment by AndreyPavlenko** [comment]
> With AA no problem.

What do you mean? I see AA on the screenshot. Have you tried to play the same video on the phone, without connecting to AA? Do you have the gap?

**Comment by Tatanka79** [comment]
> > With AA no problem.
> 
> What do you mean? I see AA on the screenshot. Have you tried to play the same video on the phone, without connecting to AA? Do you have the gap?

Sorry, I expressed myself badly, no problem on the phone. The problem is on AA, that's where I have the bandwidth problem

**Comment by AndreyPavlenko** [comment]
Thanks. I'm unable to reproduce the issue, but I'll try a different device.

**Comment by Tatanka79** [comment]
> Thanks. I'm unable to reproduce the issue, but I'll try a different device.

it's probably the fault of the car, or rather the resolution of the car's screen.

**Comment by fcaronte** [comment]
> Thanks. I'm unable to reproduce the issue, but I'll try a different device.

Hi Andrey, practically Renault Captur has a vertical screen, and I found the setting for android emulator to try this strange layout, and yes seem on YouTube full screen have Black background, when on iptv stay transparent. Fermata auto theoretically start at full screen. I attach setup and a video to show result.![IMG_20230228_231419_735.jpg](https://user-images.githubusercontent.com/26366403/221994347-4f88b8c2-3aa7-4195-ac03-c0459b53368f.jpg)

https://user-images.githubusercontent.com/26366403/221994370-8218566b-df6c-4fb2-a090-542d98956f99.mp4

**Comment by AndreyPavlenko** [comment]
@fcaronte Thanks for the reproducer!

**Comment by fcaronte** [comment]
> @fcaronte Thanks for the reproducer!
i check and the bug is the same using local video file

**Comment by Tatanka79** [comment]
Hi Andrey, did you happen to have a look at the problem? Thank you
