### ISSUE TITLE
Регулировка качества видео

### ISSUE THREAD

**Issue by Grafden** [AndreyPavlenko/Fermata#24]
Не регулируется качество видео в Fermata auto в ютубе,всё время показывает авто 240. Подскажите как исправить?

**Comment by AndreyPavlenko** [comment]
![video_settings](https://user-images.githubusercontent.com/1067755/119632092-29d1b080-be19-11eb-9f28-975540f95d48.jpeg)

**Comment by Grafden** [comment]
В телефоне регулируется, а на магнитоле нет

**Comment by AndreyPavlenko** [comment]
Попробуйте выставить качество на телефоне и обновить страницу (свайп вниз) на магнитоле.

**Comment by Grafden** [comment]
Ок.попробую благодарю

**Comment by Grafden** [comment]
Установил другую версию 1.7.10 и всё заработало

**Comment by Grafden** [comment]
Добрый день,установил версию 1.8,подскажите пож.как включить IPTV?
