### ISSUE TITLE
Playback speed for individual tracks and folders

### ISSUE THREAD

**Issue by Vladi69** [AndreyPavlenko/Fermata#242]
I can not find the way to configure playback speed for individual tracks and folders. I tried everything, but it seems it doesn't work. I would like to have Music folder at 1.0x and all the rest at 1.5x.

Thx for your help!

**Comment by Vladi69** [comment]
This what I do, but it doesn't seem to work, it doesn't keep this configuration for folder and subfolders

**Comment by AndreyPavlenko** [comment]
It works for the current folder only.

**Comment by Vladi69** [comment]
Ok, this is an useful information, but it doesn't seem to keep the configuration to me. Anyway, I will keep it as it is, Fermata is a great app, one of my favorites
