### ISSUE TITLE
Actual full screen on wide displays?

### ISSUE THREAD

**Issue by cuetus** [AndreyPavlenko/Fermata#243]
Can't figure out how to make this reallly full screen. Can it be done? 

![IMG_20230315_175257_872~2](https://user-images.githubusercontent.com/147737/225367520-cee24d01-8b9c-4811-a22d-5466aac3e277.jpg)

**Comment by cuetus** [comment]
![IMG_20230315_180132_440](https://user-images.githubusercontent.com/147737/225369465-6682c4ab-9602-44c9-994d-ca9ded16b5f3.jpg)

**Comment by AndreyPavlenko** [comment]
Unfortunately, there is no solution yet.

**Comment by cuetus** [comment]
Ok. Seems that only apps somehow flagged as navigation can use the whole screen.
