### ISSUE TITLE
Fermata shortcut has disappeared after the update to 1.9.1 (213)

### ISSUE THREAD

**Issue by lopropio** [AndreyPavlenko/Fermata#244]
I'been using Fermata for more than 6 months without problems . I started with version 1.8.11 and i survived the update to 1.9.0 without issues. At the same time i did some AA Updates from 8.0.623343 until 8.9.630624 also without any problems. 
But today, after the Fermata Update to 1.9.1, i don't have a shurtcut to start Fermata Auto in AA, the Fermata Control shurtcut is however available.

Android version: 12.0
Android Auto: 8.9.630624
Installed files:  fermata-1.9.1-auto-universal-arm64.apk  and fermata-auto-control-1.9.1-release.apk 

What i have to do, to get the Fermata Auto shurtcut in AA? 
Thanks in advance

**Comment by AndreyPavlenko** [comment]
Try this installer - https://github.com/fcaronte/KingInstaller

**Comment by lopropio** [comment]
Thanks for the help Andrey, problem was fixed with it. You can drink later a nice coffee for it. ;)

**Comment by Marekor123** [comment]
Same thing happened to me.

**Comment by Marekor123** [comment]
After updating Pixel 7 with android 13 latest update, Fermata Auto 1.9.1 stop working in Android Auto.
Try every option and it won't show up in Launcher.

**Comment by AAMAA** [comment]
Same here, it totally disappeared.
I have tried many fixes by using installer and downgrading both Fermata and AA without any change, it's fully blocked.

**Comment by g9711566** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/267#issuecomment-1656375362
Try this method on your Pixel phones.
