### ISSUE TITLE
Option to disable automatic full screen

### ISSUE THREAD

**Issue by wepache** [AndreyPavlenko/Fermata#247]
I exclusivelu use Fermata Auto for YouTube. Is there an option to disable automatic full screen on videos? 

I like to what video suggestions are on the page. I also haven't found a button to exit full screen. I went through all the settings to see if there was a way to fix this. 

Am I missing something?

**Comment by AndreyPavlenko** [comment]
Long press on the play/pause button stops the playback and exists the full screen.
