### ISSUE TITLE
updating to the version 1.9.1 

### ISSUE THREAD

**Issue by AAMAA** [AndreyPavlenko/Fermata#248]
After updating to the latest version 1.9.1 the app not appear anymore in the android auto customize Launcher list (in the mobile it's working but not appear in the android Auto). I have tried many things, downgraded Fermata to many old Versions without any changes, also i have downgraded Fermata to old Versions also no changes.
I have installed Fermata from GitHub and also one time using the AAAD. No change
I'm using Google P6P.
Also i have tried to install it using King installer, unfortunately no changes.
Any help to solve this will appreciated.

**Comment by AndreyPavlenko** [comment]
Install the app, using this installer - https://github.com/fcaronte/KingInstaller/releases/tag/1.2

**Comment by AAMAA** [comment]
That's already has been done for more than 10 Times, with many different Versions.

**Comment by igi01** [comment]
I have Same problem with my pixel6

**Comment by lopropio** [comment]
As Andrey has posted here, please use the installer, to get the app icons showed in AA (customize launcher):
https://github.com/AndreyPavlenko/Fermata/issues/244#issuecomment-1470749680

**Comment by ItsYaBOYSATAN666** [comment]
Ya whatever that modded version of kinginstaller is does not work whatsoever. We need the o.g kinginstaller back on here. Luckily I saved the apk file of the o.g one but for others on here they need that original apk. I just factory reset my phone and tried using this modded version of kinginstaller and it didn't work at all then I remember I backed up the original kinginstaller and bam worked like a charm

**Comment by igi01** [comment]
> Ya whatever that modded version of kinginstaller is does not work whatsoever. We need the o.g kinginstaller back on here. Luckily I saved the apk file of the o.g one but for others on here they need that original apk. I just factory reset my phone and tried using this modded version of kinginstaller and it didn't work at all then I remember I backed up the original kinginstaller and bam worked like a charm

Can you Upload your Version?

**Comment by ItsYaBOYSATAN666** [comment]
Ya sorry I just saw your message on here my notifications weren't turned on

**Comment by ItsYaBOYSATAN666** [comment]
Crap it won't let me upload an apk file from my Google drive it's greyed out

**Comment by ItsYaBOYSATAN666** [comment]
I could send it to you on telegram or something like that or I could just be dumb and now know how this works on GitHub I'm new to GitHub I've only ever downloaded files off GitHub I've never sent or made anything before on here

**Comment by AAMAA** [comment]
> I could send it to you on telegram or something like that or I could just be dumb and now know how this works on GitHub I'm new to GitHub I've only ever downloaded files off GitHub I've never sent or made anything before on here

Good morning,
Could you please share your file on the drive.
There is an option allowed you to share only the file you want with Public.
Thanks a lot for that

**Comment by xecura** [comment]
> 

Can you send for me too..
Thanks

**Comment by ItsYaBOYSATAN666** [comment]
>@AAMAA wait like share it through Google drive and not on here you mean? Sorry I'm not the smartest when it comes to like different programs and shit lol I can see if I can make my apks public on drive for sure. If I figure it out do I just share the link on here to my drive? Again sorry I'm trying to learn more about tech and stuff which is why I have this GitHub account. I feel dumb tho compared to everyone in the GitHub community so please bear with me.

**Comment by ItsYaBOYSATAN666** [comment]
https://drive.google.com/drive/folders/1CjmkdmSScB9GPG45Vhn2kSLzffr7rtj9

**Comment by ItsYaBOYSATAN666** [comment]
https://drive.google.com/file/d/1SLFIh1WOurOQYYMuBSSVp52RXCtxE4xO/view?usp=drivesdk

**Comment by ItsYaBOYSATAN666** [comment]
Here you guys go remember to install it with your devices stock package installer and not a 3rd party jnstaller. I have found other downloaders won't work you have to use your devices package installer Incase anyone doesn't already know that. Sorry for the delay on posting it.

**Comment by ItsYaBOYSATAN666** [comment]
> > 
> 
> Can you send for me too..
> Thanks 

https://drive.google.com/file/d/1SLFIh1WOurOQYYMuBSSVp52RXCtxE4xO/view?usp=drivesdk

**Comment by AAMAA** [comment]
Thanks mate,
I have tried this but nothing changed on my Pixel 6 Pro.
Still Fermata not in the list.

**Comment by AAMAA** [comment]
> Here you guys go remember to install it with your devices stock package installer and not a 3rd party jnstaller. I have found other downloaders won't work you have to use your devices package installer Incase anyone doesn't already know that. Sorry for the delay on posting it.

Can you please confirm what AA version are you using.

**Comment by ItsYaBOYSATAN666** [comment]
> > Here you guys go remember to install it with your devices stock package installer and not a 3rd party jnstaller. I have found other downloaders won't work you have to use your devices package installer Incase anyone doesn't already know that. Sorry for the delay on posting it.
> 
> Can you please confirm what AA version are you using.

I'm on 9.1.6 so after installing king installer and once you load the files through king installer and what not when I tap install as king my phone always ask me what installer I want to use and I always click my phone's systems package installer then it asks me to let king installer install unknown sources and then it installs and so far on every single new version of Android auto that is released I've been able to run fermata on it. Although everytime my phone auto updates Android auto I have to uninstall fermata auto and control and reinstall in the way I just explained and it has worked everytime with this o.g kinginstaller. Are u remembering to uninstall fermata auto and control before trying to reinstall it?

**Comment by ItsYaBOYSATAN666** [comment]
> > Here you guys go remember to install it with your devices stock package installer and not a 3rd party jnstaller. I have found other downloaders won't work you have to use your devices package installer Incase anyone doesn't already know that. Sorry for the delay on posting it.
> 
> Can you please confirm what AA version are you using

If your doing everything right uninstalling reinstalling and everything I have a feeling it's cause u have a Google phone that it's not working I'm sure since it's a Google phone googles able to see all your 3rd party apps and because of AA being developed by Google and your phone being developed by Google and all the STUPID ASS safety features I'm sure it's harder to hide stuff from Google while having a Google phone only thing that makes sense to me cause I've had no issues on every version of AA so far. O one more thing i do is turn off usage and diagnostics in my Google account so they can't query all my 3rd party apps. Idk if that has made this possible for me but that is another thing I've done.

**Comment by ItsYaBOYSATAN666** [comment]
Hey maybe try uninstalling all the updates to your Android auto and go to apkmirror and reinstall the updates from apkmirror. Go into your Google account turn off usage and diagnostics uninstall fermata auto and control and then reinstall see if that heps.

**Comment by AAMAA** [comment]
Thanks guys for the following and support, unfortunately nothing changed, i think it's Google Pixel issue, the rooting is the only solution for this i think.

**Comment by AAMAA** [comment]
> > > Here you guys go remember to install it with your devices stock package installer and not a 3rd party jnstaller. I have found other downloaders won't work you have to use your devices package installer Incase anyone doesn't already know that. Sorry for the delay on posting it.
> > 
> > 
> > Can you please confirm what AA version are you using
> 
> If your doing everything right uninstalling reinstalling and everything I have a feeling it's cause u have a Google phone that it's not working I'm sure since it's a Google phone googles able to see all your 3rd party apps and because of AA being developed by Google and your phone being developed by Google and all the STUPID ASS safety features I'm sure it's harder to hide stuff from Google while having a Google phone only thing that makes sense to me cause I've had no issues on every version of AA so far. O one more thing i do is turn off usage and diagnostics in my Google account so they can't query all my 3rd party apps. Idk if that has made this possible for me but that is another thing I've done.

It's look like google issue, i will keep trying for a few days, if there no chance i will root the device to F**k google.
Thanks for your patience and help.
If i got something i will posted here.

**Comment by ItsYaBOYSATAN666** [comment]
> > > > Here you guys go remember to install it with your devices stock package installer and not a 3rd party jnstaller. I have found other downloaders won't work you have to use your devices package installer Incase anyone doesn't already know that. Sorry for the delay on posting it.
> > > 
> > > 
> > > Can you please confirm what AA version are you using
> > 
> > If your doing everything right uninstalling reinstalling and everything I have a feeling it's cause u have a Google phone that it's not working I'm sure since it's a Google phone googles able to see all your 3rd party apps and because of AA being developed by Google and your phone being developed by Google and all the STUPID ASS safety features I'm sure it's harder to hide stuff from Google while having a Google phone only thing that makes sense to me cause I've had no issues on every version of AA so far. O one more thing i do is turn off usage and diagnostics in my Google account so they can't query all my 3rd party apps. Idk if that has made this possible for me but that is another thing I've done.
> 
> It's look like google issue, i will keep trying for a few days, if there no chance i will root the device to F**k google.
> Thanks for your patience and help.
> If i got something i will posted here.

Shit that sucks man I was really hoping it was gonna work for ya. Mine as well root the phone if that's what's gonna make it work for you. I thought about rooting mine as well but I don't know how to do all that so I prob shouldn't lol. Just glad I'm still able to use fermata I've been hella worried about all the new updates each time they've updated AA. I thought I'd be screwed by now, I found fermata and how to use it back when AA was still in it's 6th version and I've been literally cringing on each AA update thinking it was gonna not work anymore but to my surprise here we are on version 9 and I'm still able to use fermata. I first had this app on my a51 but now I have a galaxy A53 that obviously is still allowing this to work for me.  I guess i should be thanking Samsung and of course Andry for the amazing app everyone is trying to keep being able to use. I dread the day it doesn't work for me anymore.

**Comment by LasGeo64** [comment]
I also suffered the same issue on my pixel 6 pro.😢

**Comment by ItsYaBOYSATAN666** [comment]
Man I just had my android auto updated again and low and behold mine still works I wonder if it's a phone issue with you guys who can't get it to work

**Comment by AAMAA** [comment]
> Man I just had my android auto updated again and low and behold mine still works I wonder if it's a phone issue with you guys who can't get it to work

Maybe it's related to the Pixel 6 system update.
For more than 2 months all was ok for me even with beta AA . But in that day i noted that there is a Fermata 1.9.1 version has been released, i decided to update to it. Then it's disappeared from AA app list.

**Comment by lbise** [comment]
I have the same issue with a Pixel 4. It looks like all Pixel models are concerned?

**Comment by igi01** [comment]
also other apps are concerned.
in xda developer screen2Auto thread someone suggested (https://forum.xda-developers.com/t/screen2auto-new-app-for-aa-smartphone-mirroring-only-for-root-devices.4062787/page-147#post-88392893):

"S2A appears to be the most restricted app.

To my knowledge following levels of restrictions/by-passes exist:
1. Developer mode + unknown sources need to be enabled in the AA app,
you can tap the Version number in the AA app a lot, to unlock the developer settings.
2. Apps need to be "installed as Google Play",
you can use KingInstaller to do so: https://github.com/fcaronte/KingInstaller
3. Apps need to be "whitelisted in phenotype.db",
you can use AA-AIO-Tweaker for this: https://github.com/shmykelsa/AA-Tweaker
4. Apps need Xposed module to spoof an additional "installed as Google Play" check,
you can use Android-Auto-XLauncher-Unlocked for this: https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked
5. Apps (for now only Screen2Auto to my knowledge) need their internal package name changed to something different,
you can use MT Manager for this: https://mt2.cn/download/

Open MT Manager => Open S2A.apk file => View => AndroidManifest.xml => String pool => Triple dot icon => Filter =>
Type the package name of the app (likely "ru.cvitnepei.neatruwtosceo" or "ru.inceptive.screentwoauto") => Ok
=> Select the found package name (likely "ru.cvitnepei.neatruwtosceo" or "ru.inceptive.screentwoauto")
=> Alter it to something unique, don't tell your unique package name online => Ok => Back arrow => Save and exit
=> Save AndroidManifest.xml modification + Auto sign => Ok

Open your package manager => Install modified / renamed S2A.apk"

i will try to rename package soon

**Comment by igi01** [comment]
Some people write in this thread point 2 and 5 is sufficient. No root needed for this

**Comment by AndreyPavlenko** [comment]
For rooted devices, there is an LSPosed module built into Fermata Auto. All you need is to just activate it.

**Comment by lbise** [comment]
Any news on this issue? Did someone manage to make it work? I'm sad to not have youtube in my car any more :D

**Comment by AAMAA** [comment]
> Some people write in this thread point 2 and 5 is sufficient. No root needed for this

Not help unfortunately.

**Comment by AAMAA** [comment]
> Any news on this issue? Did someone manage to make it work? I'm sad to not have youtube in my car any more :D

only rooting solve this for me.

**Comment by jappoman** [comment]
How is it possible that is a Pixel only problem when other apps like fermata control, cartube etc keeps showing and working? It has something to do with the update too.

**Comment by Kr1ptiq** [comment]
Same issue on a Pixel 5

**Comment by backslashV** [comment]
Even the root method doesn't work on Pixel 7. Tried the following
AA AIO Tweaker
Android Auto - XLauncher Unlocked
King installer
...

**Comment by backslashV** [comment]
> > Even the root method doesn't work on Pixel 7. Tried the following AA AIO Tweaker Android Auto - XLauncher Unlocked King installer ...
> 
> Try this - https://github.com/AndreyPavlenko/Fermata/discussions/122#discussioncomment-4307775

Thanks. v1.9.0 works as mentioned in that comment. I was trying with v1.9.2.

**Comment by AndreyPavlenko** [comment]
> Thanks. v1.9.0 works as mentioned in that comment. I was trying with v1.9.2.

1.9.2 should work either.

**Comment by synchronster** [comment]
Hi.  I'm also in the same boat with Fermata Auto not working when I updated to 1.9.2.  I uninstalled both FA and the control app.  Only FC appears in the AA customized launcher (installed ver. 1.8.11 for both from GitHub).  Also using Pixel6.  Please help.  I miss this app in my car so much.
