### ISSUE TITLE
Scaling issues (ESPN+)

### ISSUE THREAD

**Issue by prehprehpreh** [AndreyPavlenko/Fermata#249]
Scaling issues in specific website. (ESPN+)
The content is scaled too small and I can't hit the full screen button on the video player. Included pictures to show examples of how it looks in fermenta browser and my s22's chrome browser.
 Can't find anyway around it so far. Help? If I enter full screen in fermenta, the player gets a tiny bit bigger, but not big enough to show the Fullscreen button.

![Screenshot_20230331_024733_Fermata Auto](https://user-images.githubusercontent.com/46481726/229046036-d1528361-365b-4b63-b3ec-d220e46caf0d.jpg)

![Screenshot_20230331_024851_Chrome](https://user-images.githubusercontent.com/46481726/229046084-f0a54821-98dc-45b6-9da5-c640bd270f94.jpg)

**Comment by AndreyPavlenko** [comment]
Works for me on the latest version.
