### ISSUE TITLE
Issue while playing video through browser

### ISSUE THREAD

**Issue by varun1234567890123** [AndreyPavlenko/Fermata#25]
While i playing videos from brower i.e. say hotstar, then i lost touch control after going into full screen. Otherwise working fine. Secondly videos aren't playing from amazon prime video. Please give solution if possible.

**Comment by AndreyPavlenko** [comment]
What do you mean by "lost touch control"?
Can you play amazon videos in Chrome on the same device? If yes, try to change the User-Agent in Settings > Addons > Web browser.

**Comment by varun1234567890123** [comment]
Means once i go for full screen, i all the touch buttons i.e. 10s forward , 10s back, start, stop ....nothing works. Although videos continues fine. Only buttons works in full screen is a back button of the app.

**Comment by varun1234567890123** [comment]
And please share a mrthod to change web brower to google chrome.

**Comment by varun1234567890123** [comment]
![Screenshot_20210527-220901_Fermata Auto](https://user-images.githubusercontent.com/84924773/119864619-6d6f0c00-bf38-11eb-9869-f2fca8ac34f2.jpg)

Getting this while trying to play video from Amazon prime.However i don't get these three dots at right top corner in the browser.

**Comment by varun1234567890123** [comment]
![Screenshot_20210528-062109_Fermata Auto](https://user-images.githubusercontent.com/84924773/119914059-0f184c80-bf7d-11eb-895f-995778558dbb.jpg)

This is my user Agent....i changed it after reading a related topic from xda developers page.

**Comment by AndreyPavlenko** [comment]
I'll try to fix it in the next version.

**Comment by varun1234567890123** [comment]
Sure sir....by the way a big thanks for such an amazing application.

**Comment by AndreyPavlenko** [comment]
Try the new version https://github.com/AndreyPavlenko/Fermata/releases/tag/v1.8.0b
