### ISSUE TITLE
1.9.1 Video freezes >>1.9.0 rollback 

### ISSUE THREAD

**Issue by chavalino** [AndreyPavlenko/Fermata#250]
When playing video, it freezes after a few seconds. The app continues playing audio though, but the frame is frozen.
I didn't have this problem with 1.9.0.

**Comment by AndreyPavlenko** [comment]
Try changing the media engine. VLC is used by default.

**Comment by lopropio** [comment]
I did have the same issue as well, that's why I've downgraded to the 1.9.0 release.

**Comment by chavalino** [comment]
I tried other media engines Exo something and Mediaplayer, but it didn't help. 

Another strange behavior is that with 1.9.0 I could always start in video mode by default. Now with 1.9.1, Fermata starts in audio player mode by default and I can't force it to start in or change to video mode.

**Comment by chavalino** [comment]
After several attempts to use 1.9.1 I give up - video freezes.
I rolled back to 1.9.0 that works smoothly with default settings.
