### ISSUE TITLE
IPTV streams inconsistent 

### ISSUE THREAD

**Issue by plapic** [AndreyPavlenko/Fermata#252]
Using this example based of geo locked Australian TV channels for m3u8 https://i.mjh.nz/au/Adelaide/raw-tv.m3u8
and epg https://i.mjh.nz/au/Adelaide/epg.xml.gz
In going through the Adelaide group the first channel 7 will not load. Fifth channel will not play in AA. Twelveth channel ABC will play fine. These streams work perfectly in IPCarTV

**Comment by AndreyPavlenko** [comment]
I'm getting `HTTP error 403 Forbidden` error, when trying to play channels from this playlist.

**Comment by plapic** [comment]
Unless you are in Australia you will have to first use a vpn maybe AwardVPN to test any of these channels.

**Comment by plapic** [comment]
@AndreyPavlenko thanks for the 1.9.2 update. It appears this has resolved the problem. Good work.

**Comment by robi2420** [comment]
Hello friends, I would like to ask if anyone could help me find a link to the EPG for Slovakia or the Czech Republic, thank you.
