### ISSUE TITLE
Audio & video Out of sync

### ISSUE THREAD

**Issue by hmosquera1973** [AndreyPavlenko/Fermata#253]
Hello, I have a motorola edge 30, and when I try to put videos, randomly, I have micro pauses in the video, but not in the music, consequently I get out of sync audio with video.
(I have the videos stored in the internal memory of the phone)
I tried with version 1.90 and with 1.91 and in both cases the same thing happens to me.
Is there any way to fix it? thank you very much
(I using the last version of Android Auto)

**Comment by AndreyPavlenko** [comment]
Try changing the video engine (VLC is used by default).

**Comment by hmosquera1973** [comment]
> Try changing the video engine (VLC is used by default).

Hi Andrey, I tried other video engines, but the same error continues.
Any other alternative to solve the error?
thank you very much for your help

**Comment by AndreyPavlenko** [comment]
The problem could be with the USB cable. If nothing helps, you can configure the audio delay, but this option only works for VLC.
