### ISSUE TITLE
Feramta car no longer works with new phone in new car

### ISSUE THREAD

**Issue by PoPeYe2000** [AndreyPavlenko/Fermata#255]
Feramta Auto no longer works with new phone in new car.
I hang all data transferred from old phone to new phone (Samsung S22 Ultra to S23 Ultra). In addition, I got a new car, but android auto works without problems but feramta Auto just not. I am thinking of reinstalling everything again via King instaler. Does anyone have similar problems?

**Comment by AndreyPavlenko** [comment]
You need to install Fermata with King Installer.

**Comment by gaduaxe** [comment]
I had same problem with latest AA v9.1.6
Old AA version works fine, but after upgrade to AA v9.1.6 not working anymore
@AndreyPavlenko 

> You need to install Fermata with King Installer.

**Comment by jappoman** [comment]
@AndreyPavlenko 
Still no solution for pixel phones with newer AA?

**Comment by AndreyPavlenko** [comment]
The solution is either this https://github.com/fcaronte/KingInstaller/releases version of KingInstaller or, if it does not work, Magisk + LSPosed.

**Comment by jappoman** [comment]
> The solution is either this https://github.com/fcaronte/KingInstaller/releases version of KingInstaller or, if it does not work, Magisk + LSPosed.

is still not working. The problem is specific with this app btw, Fermata control works without issues. Is almost like the package name is blacklisted or something.

**Comment by AndreyPavlenko** [comment]
Fermata control works just because this is a standard AA media app. You can also install Fermata from google play and it should work in the same way.

**Comment by jappoman** [comment]
> Fermata control works just because this is a standard AA media app. You can also install Fermata from google play and it should work in the same way.

Fermata from the play store works but without special features lik Youtube etc, even if you enable that function from the phone. Your app was the best for that particular tasks, no other app works like yours...

**Comment by AndreyPavlenko** [comment]
Sure, because any AA media app from google play doesn't have a custom interface. What you see in AA is a standard AA media player. The media apps, like Fermata and any other media app from google play, just provide content to the AA media player. That's why you can see Fermata Control in AA, because it's a standard AA media app. For Fermata Auto additional tweaks are required and, for some reason, they do not work on some devices.

**Comment by jappoman** [comment]
> Sure, because any AA media app from google play doesn't have a custom interface. What you see in AA is a standard AA media player. The media apps, like Fermata and any other media app from google play, just provide content to the AA media player. That's why you can see Fermata Control in AA, because it's a standard AA media app. For Fermata Auto additional tweaks are required and, for some reason, they do not work on some devices.

Seems all pixel phones are affected, do you own one?

**Comment by AndreyPavlenko** [comment]
> Seems all pixel phones are affected, do you own one?

No, I don't have a pixel phone.
If KingInstaller does not work for you, then the only solution is Magisk + LSPosed.

**Comment by jappoman** [comment]
Sorry but i dont want to root the phone..

**Comment by Kr1ptiq** [comment]
Seems like he's abandoned Pixel phones. Such a shame

**Comment by g9711566** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/267#issuecomment-1656375362
I tried this method on Pixel 6a and Pixel 7a. It finaly worked!
