### ISSUE TITLE
Fermata control

### ISSUE THREAD

**Issue by RMMA1979** [AndreyPavlenko/Fermata#259]
De la nada me dejó de funcionar fermata control en Xiaomi , lo e usado por más de dos años y nunca tuve un problema hasta ahora ...alguna solución

**Comment by genilsonvp** [comment]
Boa noite

Há alguma solução para o Android 12 ?

Moto g30 edge não funciona o fermata auto controle, instala mas não funciona

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: RMMA1979 ***@***.***>
Sent: Friday, May 12, 2023 10:10:07 PM
To: AndreyPavlenko/Fermata ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndreyPavlenko/Fermata] Fermata control (Issue #259)


De la nada me dejó de funcionar fermata control en Xiaomi , lo e usado por más de dos años y nunca tuve un problema hasta ahora ...alguna solución
