### ISSUE TITLE
Web Browser version

### ISSUE THREAD

**Issue by oli80330** [AndreyPavlenko/Fermata#26]
Hello,
Thanks for this great app !

But the web brosser version is old, firefox 5.0, year 2011.

It's possible to upgrade for à new version ?
 because some websites no longer accept this version for online streaming.
For exemple : https://www.6play.fr/m6

**Comment by AndreyPavlenko** [comment]
Try to update the system WebView - https://play.google.com/store/apps/details?id=com.google.android.webview .
Also, you can change the User-Agent in Settings > Addons > Web Browser. Open this https://www.whatismybrowser.com/detect/what-is-my-user-agent url in any browser and copy the user agent string.

**Comment by oli80330** [comment]
Hello, webview is up to date.
Useragent  has been changed but videostreaming is still faulty on m6replay website "browser is too old, please update".

**Comment by AndreyPavlenko** [comment]
Does it work in Chrome on the same device? If yes, add the same user agent string as in Chrome.

**Comment by jespersday** [comment]
Hi Andrey.
I have same issue. Netflix works fine in my phone chrome browser, but not in Fermata browser. I am told  to fix the content setting, but i cannot access that in Fermata.
I have tried to update the user agent in add ons, but i doesnt work. Maybe I am doing it wrong.
Are you able to help me?
Thanks in advance.
BR Jespersday from Denmark

**Comment by AndreyPavlenko** [comment]
Unfortunately, Netflix does not work in WebView - https://github.com/AndreyPavlenko/Fermata/issues/37#issuecomment-920165923

**Comment by jespersday** [comment]
Thank you for your fast answer. 🙂
I guess it means that there is no way to get Netflix in my car with Fermata?
BR Jespersday

**Comment by AndreyPavlenko** [comment]
> I guess it means that there is no way to get Netflix in my car with Fermata?

Right.
