### ISSUE TITLE
tv list not working

### ISSUE THREAD

**Issue by Funkym77** [AndreyPavlenko/Fermata#261]
hello andrey

I enter my iptv address, but the tv list does not come. not working big problem

**Comment by AndreyPavlenko** [comment]
Have you tried to open the address in a web browser? Could you download the playlist?

**Comment by Funkym77** [comment]
I've done it with the channel list file. thanks. Andrey, when I say "fill your screen" in video scaling, I lose the image. in other options, the screen is a little small. I want to use the screen to the maximum, but I have this problem. The car is peugout 308 t9 case.

**Comment by AndreyPavlenko** [comment]
Fill screen scales the image proportionally. If the image dimensions are not proportional the screen dimensions, obviously, the image is cropped.

**Comment by Funkym77** [comment]
There is no problem on youtube. It fills pretty well. but "fill screen" doesn't work properly when watching ip tv from tv option or folder option. It enlarges the image too much and it gets lost.

**Comment by AndreyPavlenko** [comment]
Could you post a screenshot.

**Comment by thezuule** [comment]
I have a similar issue with the freely available PlutoTV repo at i.mjh.nz/PlutoTV/us.m3u8  

It works sometimes and sometimes not. Always seems to work in the app on my phone but in Android Auto it's sporadic. Sometimes opening Fermata Control or opening the app on my phone and just putting it to sleep seems to help. When it works it works perfectly, everything shows up, I get all my icons for channels and images for whatever show is playing. When it doesn't work it just shows the name of the channel as the name of the program airing. Icons for the channels work fine but that's the extent of the information available. Been an ongoing issue for a while.
