### ISSUE TITLE
ChatGPT throwing up a java error

### ISSUE THREAD

**Issue by thezuule** [AndreyPavlenko/Fermata#263]
![Screenshot_20230524-100731_Fermata Auto](https://github.com/AndreyPavlenko/Fermata/assets/134521050/5437fd4b-a5c6-41bd-8599-2b55472e1ee5)

Attention
Request failed: kava.io.IOException: Request Failed: Too Many Requests

This is the message I get whenever I try to prompt the AI. Added my ChatGPT API key correctly as far as I'm aware. Only on a free account. Is this error related to not having ChatGPT Plus or something of the sort?

**Comment by AndreyPavlenko** [comment]
I use the free trial key, but has never reached the request limit.

**Comment by thezuule** [comment]
I checked my account and my free trial credits have expired. Maybe a future release could have an error check there to let people know they don't have tokens or something of the sort.
