### ISSUE TITLE
fermata auto fullscreen possible ?

### ISSUE THREAD

**Issue by widescreen111** [AndreyPavlenko/Fermata#265]
Hi
Is it possible to fix fermata auto scale to fullscreen on bmw idrive 7 ?
Waze and Google maps are already working like that and it is really nice.

Many thanks in advance !
Wide

**Comment by AndreyPavlenko** [comment]
Seems the full screen functionality is only available for the navigation apps.

Duplicates #221

**Comment by widescreen111** [comment]
Hi again,

I had oppurtunity to have a new Golf Move as a rental car in Germany. 
As I connected my AA with all the apps to car, I found out to my surprise that Fermata Auto and Carplay was scaling to full screen with doubleclick on the screen !
 Of course pic quality will suffer, but a really nice to have feature.
Back  home I tried in Idrive 7 with high hopes,  but not working.
Do you same information and do you know what differs between car brands or connectivity or version of AA or something else as it now seems to be working on VW brand ?
BR
Leo

**Comment by AndreyPavlenko** [comment]
I think, it depends on the screen size. On small screens AA can scale apps to full screen.
