### ISSUE TITLE
Fermata Auto 1.9.2 stopped working on Android Auto

### ISSUE THREAD

**Issue by piotrklementowski** [AndreyPavlenko/Fermata#267]
I just updated both FA and AA and noticed AA doesn't list FA anymore. I use Pixel 6pro, FA 1.9.2 installed in AAD on AA 9.5. 
Any hints which app messed up? Any hint what set of apps with their versions is still working?
My 4 year old boy is devastated he cannot watch his favorite cartoons in the car :(

**Comment by YoURitTo** [comment]
Doesn't work. No more on Android auto... They probably patched it

**Comment by virol** [comment]
Same here,
Shows FA on aa apps, but when click on it, black screen on aa and freeze.
:.
logs from fermata-app shows  a chmod permission error in /data/data/google.gearhead.......... files when opening it from within aa
I am rooted, and some time ago it was working .
going back to 1.8.11 will not help, just the same problem

**Comment by AndreyPavlenko** [comment]
> logs from fermata-app shows a chmod permission error in

Is it Fermata log or logcat? The app does not use chmod.

 

> I am rooted, and some time ago it was working .

Have you tried LSPosed module for Magisk?

**Comment by virol** [comment]
,its logcat, where does this error come from then?

yes tried Xposed module( not the Zigisk LSPosed ,I am on Android 8)  and the AA unlocker module

FA shows as app in aa even without Xposed.
installed FA  with latest king installer and even renamed the fermata project name, nothing helps

**Comment by AndreyPavlenko** [comment]
> ,its logcat, where does this error come from then?

Definitely not from the app. You can search the code, there is no `chmod` anywhere.

**Comment by kgrames** [comment]
> I just updated both FA and AA and noticed AA doesn't list FA anymore. I use Pixel 6pro, FA 1.9.2 installed in AAD on AA 9.5. Any hints which app messed up? Any hint what set of apps with their versions is still working? My 4 year old boy is devastated he cannot watch his favorite cartoons in the car :(

Having the same issue. I even tried downgrading android audio as well. Still not working.

**Comment by collectablessports** [comment]
Been looking everyday hoping this has been resolved. I've had the same problem since early June. Anything I can send to help resolve? Thank you

**Comment by faifer13** [comment]
Maybe this contribution from the discussions section can work:

Can you try to install this package installer version and then try again to reinstall from scratch fermata auto using kinginstaller?

https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-13-8768315-release/package-installer-13-8768315-android-apk-download/

I have a P6P but I have not been able to test, I still have 1.8.1 functional

**Comment by virol** [comment]
Hello,
I Will come back to my problem to not working anymore versions above 1.9 on my phone (see above)
The problem was android version 8 itself, when it was upgraded tot LineaOs 19.1 or Android 10, Fermata was working again with all versions, including that latest version.
Just install it with the latest Kinginstaller APK and everthing is ok

Thx

**Comment by g9711566** [comment]
> Maybe this contribution from the discussions section can work:
> 
> Can you try to install this package installer version and then try again to reinstall from scratch fermata auto using kinginstaller?
> 
> https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-13-8768315-release/package-installer-13-8768315-android-apk-download/
> 
> I have a P6P but I have not been able to test, I still have 1.8.1 functional

This method actually works on my Pixel 6a and Pixel 7a. Thank you very much!!

**Comment by coverdale76** [comment]
> Maybe this contribution from the discussions section can work:
> 
> Can you try to install this package installer version and then try again to reinstall from scratch fermata auto using kinginstaller?
> 
> https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-13-8768315-release/package-installer-13-8768315-android-apk-download/
> 
> I have a P6P but I have not been able to test, I still have 1.8.1 functional

This works great!
Thank you for saving my phone😍

**Comment by ingenika** [comment]
https://androidautorepair.github.io/repair
