### ISSUE TITLE
Android 14 beta

### ISSUE THREAD

**Issue by DrUnKeNTiGeR** [AndreyPavlenko/Fermata#269]
Before beta I installed fermata auto 1.8.11 and it worked fine. Now none of the versions I install show to in aa

**Comment by fcaronte** [comment]
Can you try to install this package installer version and then try again to reinstall from scratch fermata auto using kinginstaller?

https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-14-release/package-installer-14-android-apk-download/

**Comment by DrUnKeNTiGeR** [comment]
It shows up now but this is what shows when in the app on aa

⁣Get BlueMail for Android ​

**Comment by fcaronte** [comment]
> It shows up now but this is what shows when in the app on aa
> 
> ⁣Get BlueMail for Android ​
> 
> On Jul 6, 2023, 8:07 AM, at 8:07 AM, fcaronte ***@***.***> wrote:
> >Can you try to install this package installer version and then try
> >again to reinstall from scratch fermata auto using kinginstaller?
> >
> >https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-14-release/package-installer-14-android-apk-download/
> >
> >-- 
> >Reply to this email directly or view it on GitHub:
> >https://github.com/AndreyPavlenko/Fermata/issues/269#issuecomment-1623567587
> >You are receiving this because you authored the thread.
> >
> >Message ID: ***@***.***>
> 

I think that app is not studied to work on android Auto, maybe you can use through screen2auto or get classic android auto notifications using "aanotifier" app

**Comment by ShelbyGT35** [comment]
Please work on the functions for Android 14!
Thank you.
