### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by Viktor1898** [AndreyPavlenko/Fermata#27]
Как правильно обновить приложение?
Установлено приложение через AAStore версия 1.7.7 - все работает
При установке файла 1.7.10 - AndroidAuto не видит его.
Спасибо за ответ.

**Comment by AndreyPavlenko** [comment]
Процесс установки описан вот здесь - https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/

**Comment by Viktor1898** [comment]
Привет..
Можно в личку подробную инструкцию установки приложения через ADB за
отдельную плату - но не через PAYPAL
С PAYPAL у меня проблемы на Украине.
Спасибо за ответ..

пн, 31 мая 2021 г. в 21:54, Andrey ***@***.***>:

**Comment by AndreyPavlenko** [comment]
Этот способ больше не работает на 11м андроиде и последних версиях АА. Возможно и на других версиях эту лазейку прикроют. Поэтому, лучше используйте рут.
