### ISSUE TITLE
Youtube plugin is not working

### ISSUE THREAD

**Issue by Gladstone2412** [AndreyPavlenko/Fermata#271]
Hi, in version 1.9.2, when I try to sign in to my google account (it doesnt mind if I try to sign in in youtube plugin or in browser plugin) it throws me this error. It only helps if I delete data of app and use youtube without account. (Sorry it is in czech, but Screenshot says "Web page is not available... Web page can not be loaded because of error...) 
![Screenshot_20230621_061049_Fermata Auto](https://github.com/AndreyPavlenko/Fermata/assets/69036020/0f637a63-8db6-45be-ab17-cccb18e04d22)

**Comment by AndreyPavlenko** [comment]
Sorry, but I'm unable to reproduce.

**Comment by dingusmcringus** [comment]
I have also been having this problem, I was able to reproduce with 3 phones . It is related to YouTube premium accounts. 

If I don't sign in I don't get the error, when signed in with a YouTube premium account it gives the error and won't go any further. 
![Screenshot_20230811_063459_Fermata Auto](https://github.com/AndreyPavlenko/Fermata/assets/141963178/5c7412fa-2d94-4eab-b730-305b3724c2f7)

**Comment by AndreyPavlenko** [comment]
Seems youtube redirects you to the youtube app. Have you tried to sign in using the chrome browser?

**Comment by dingusmcringus** [comment]
That's after signing in, signing it was fine with no errors but once login is complete.
The browser , desktop mode and the YouTube button gives me this error once signed in but without signing in its perfect
