### ISSUE TITLE
Request: ability to change TTS voice settings for ChatGPT

### ISSUE THREAD

**Issue by richaardvark** [AndreyPavlenko/Fermata#274]
Hello,

It would be really great if we were able to change the settings for the TTS spoken output from ChatGPT. The default voice isn't terrible and maybe it's just using the Android voice settings on my phone and I will have to check but it would be great if we could adjust the actual voice the Fermata app itself.

**Comment by AndreyPavlenko** [comment]
Right, it uses the default phone settings and you could change the defaults.
