### ISSUE TITLE
Request: Customizable UI Color Selection

### ISSUE THREAD

**Issue by richaardvark** [AndreyPavlenko/Fermata#275]
Hello,

During the daytime It is nearly impossible for me to see the majority of the buttons or icons on the Fermata UI interface despite my Pioneer head unit being on the brightest display setting. Especially unable to be seen is the floating button for activating ChatGPT voice input as well as the floating back button. It would be nice if the user was able to adjust the default UI colors in the Fermata settings menu, perhaps under the UI settings area.

**Comment by AndreyPavlenko** [comment]
Adjusting colors is not currently possible, but you could change the theme.
Btw, you may use the steering wheel next/prev buttons to activate the voice input. You need to enable this option in settings.

**Comment by richaardvark** [comment]
> Adjusting colors is not currently possible, but you could change the theme. Btw, you may use the steering wheel next/prev buttons to activate the voice input. You need to enable this option in settings.

Thank you very much for this information. I changed the theme and it looks much more viewable now.

However, I believe I have the double tap for voice input setting enabled but nothing is happening. I'm also confused because the voice settings area of the menu shows when I launch the player on my phone but does not show for some reason on the car interface. See photos below. I'm double tapping the next / back buttons and nothing is happening.

![Screenshot_2023-07-13-15-39-49-08_6fb5cbe9e860852d01e2e509ad6cd4f9](https://github.com/AndreyPavlenko/Fermata/assets/41244847/93a3a234-e52c-456f-8911-a441d055e9aa)

![IMG_20230713_154120](https://github.com/AndreyPavlenko/Fermata/assets/41244847/0d0c3323-f966-4a4d-9036-5edfff7bb919)

**Comment by AndreyPavlenko** [comment]
Do you have the Fermata Control app installed? It's required for the steering wheel control. Voice settings are not available in AA.

**Comment by richaardvark** [comment]
I do indeed have the Fermata Control app installed. And have selected/enabled the following voice control settings:

![Screenshot_2023-07-14-02-05-10-44_6fb5cbe9e860852d01e2e509ad6cd4f9](https://github.com/AndreyPavlenko/Fermata/assets/41244847/0ee04671-e0c8-4996-9c41-5431655dd6fe)

I don't know if it matters but I use a [PAC RP4-MZ11 ](https://catalog.pac-audio.com/catalog/radio-replacement/rp4-mz11) in my vehicle to retain factory steering wheel control with my upgraded radio head unit.

**Comment by AndreyPavlenko** [comment]
Does the media buttons work for you to switch to the next/prev track?

**Comment by richaardvark** [comment]
Hi there, yes - just confirmed and the steering wheel controls do work just fine to switch to the next/prev track. I have the double press for voice control feature activated in the settings as well but it's still not bringing up the speech input dialog for the ChatGPT tab or any tab.

**Comment by richaardvark** [comment]
Never mind, it's working now! I don't know why it wasn't a moment ago but I rebooted my cell phone and now it works just fine! Thank you again for your help!

**Comment by richaardvark** [comment]
I take this back - The double tap forward and backwards on my steering wheel controls is not activating ChatGPT voice input at the moment. There seems to be some sort of bug and it works intermittently. Sometimes the double press works and sometimes it does not. I just fresh rebooted my phone and restarted my car and it is not working at the moment even though the feature is enabled in the settings.

**Comment by AndreyPavlenko** [comment]
The steering wheel controls work via the Fermata Control app. Fermata needs to establish connection with the Control app and sometimes it's unable to connect until the Control app is started manually.
