### ISSUE TITLE
Turkish voice search problem 

### ISSUE THREAD

**Issue by bicer79** [AndreyPavlenko/Fermata#276]
Hello. In the last 2 versions, youtube voice search is searching in English.

How can I set it to Turkish?

**Comment by AndreyPavlenko** [comment]
You can change the voice control language in settings.

**Comment by bicer79** [comment]
I changed the language. But it's not getting better

**Comment by AndreyPavlenko** [comment]
Have you changed the interface or the voice control language?

**Comment by bicer79** [comment]
It's not a big problem, your app is great.


I just wanted to let you know

Thanks

**Comment by AndreyPavlenko** [comment]
I've just tested on my device - changed the voice control language to Turkish and it works.
Try restarting the app - kill the app or restart the phone.
