### ISSUE TITLE
Fermata não reconhece link iptv

### ISSUE THREAD

**Issue by Meca3008** [AndreyPavlenko/Fermata#277]
Olá 
Após atualização do fermata auto, a lista de iptv deixou de ser reconhecida aparece 0 canais. Já desinstalei tudo e voltei a instalar mas continua igual. Penso que estarei a fazer tudo correto....
Obrigado

**Comment by AndreyPavlenko** [comment]
Hm, there were no any IPTV related changed in the latest version. How do you add the source, is it a file or url?

**Comment by Meca3008** [comment]
É url.

**Comment by AndreyPavlenko** [comment]
Make sure the url is still valid. Try to open it in a web browser and download the playlist. Make sure the downloaded playlist is not empty.

**Comment by Meca3008** [comment]
Sim o url está válido porque está a trabalhar numa box Android. Na web o link não trabalha porque é de um servidor. Eu acho que na instalação é só colocar o link m3u e fica a funcionar ou tenho que ir ao menu fazer alguma alteração? Será que dá para fazer donwgrade para a versão 1.9.1?

**Comment by AndreyPavlenko** [comment]
Yes, you can download the 1.9.1 version here - https://github.com/AndreyPavlenko/Fermata/releases.
Use this installer to install the app - https://github.com/fcaronte/KingInstaller/releases/
