### ISSUE TITLE
Fermata TV problem 

### ISSUE THREAD

**Issue by matius86** [AndreyPavlenko/Fermata#279]
is: problem with playing TV channels from m3u list. switches to the next channel after 10 seconds. what could be the reason?

**Comment by AndreyPavlenko** [comment]
Most probably, the reason is that the stream is closed by the server. In this case, Fermata switches to the next channel.

**Comment by matius86** [comment]
but on the laptop everything works fine on the same m3u list

**Comment by AndreyPavlenko** [comment]
Have you tested with VLC?

**Comment by matius86** [comment]
Yes, on my laptop, I tested with VLC

**Comment by AndreyPavlenko** [comment]
Are your phone and laptop connected to the same network?

**Comment by matius86** [comment]
I tried on the same internet as well as on the corner. on a laptop it always works on a phone after 10 seconds

**Comment by CBETLOST** [comment]
Аналогичная проблема. При использовании fermata в машине tv постоянно переключается на следующий канал, а то и на несколько. Просто при просмотре с телефона таких проблем нет. Всё тоже самое что и у Mathis86.

**Comment by joaopauloiv** [comment]
I have the same problem, it happens with any .m3u list, it keeps skipping channels every 10 seconds, could you help me?

**Comment by AndreyPavlenko** [comment]
> I have the same problem, it happens with any .m3u list, it keeps skipping channels every 10 seconds, could you help me?

It skips to the next, when the stream is closed by the server. Perhaps, your provider allows access only from home network.
