### ISSUE TITLE
IPTV

### ISSUE THREAD

**Issue by Grafden** [AndreyPavlenko/Fermata#28]
Добрый день,установил версию 1.8,подскажите как включить IPTV? #

**Comment by AndreyPavlenko** [comment]
Добрый. Включить в настройках iptv, перейти на вкладку ТВ и добавить источник (ссылку на m3u).

**Comment by podimonanil** [comment]
Open Fermata Auto in Phone or in Car, Select TV from the bottom bar. in bottom right corner press on the + icon to add new channels. in the next screen type a name and in the location are type 
https://iptv-org.github.io/iptv/index.m3u
press enter and accept by pressing the tick mark on the top right.
you can add playlist by Category or Language or Country.
for more details visit     https://github.com/iptv-org/iptv

**Comment by AndreyPavlenko** [comment]
@podimonanil Thanks for detailed instruction.

**Comment by polinep72** [comment]
fermata не удалось добавить источник unsupported http version
