### ISSUE TITLE
WhatsApp stops Fermata

### ISSUE THREAD

**Issue by scheuerer** [AndreyPavlenko/Fermata#280]
Hallo….
Fermata is realy a perfect tool under AA tool listen to music videos.
Every time when watching a video and I get an incoming WhatsApp Message, it stops the Video Playing.
So far fine. 

BUT I cannot restart the play by pressing the “play button”…
Nothing happens. I need to press here and there, scroll forward and backward and then somehow it continues.
Any idea? This only happens a with getting a WhatsApp message…

**Comment by AndreyPavlenko** [comment]
What exactly stops playing, youtube?

**Comment by scheuerer** [comment]
I’m watching under AA any MP4 video on my mobile via Fermata. Then I get a WhatsApp and a popup comes up. When pressing the button to listen Fermata stop. I listen to the WhatsApp. Then I try to come back to Fermata and try to continue watching the video by clicking the play button under Fermata. Here the video will not continue to play…

I will try to make a movie and add the link here tomorrow when I’m in the car.

**Comment by krzysior78** [comment]
I'm not sure if it's similar issue, but when I'm watching YouTube and during that some kind of notification from car systems appears on screen, for example from proximity sensors, then notification disappears and video on YouTube is paused after that. I have to touch play/pause button twice to resume playing. Or use play/pause gesture (double tap) two times, which is 4 taps in a row. Is there option that video would resume automatically after car popups disapearence?

**Comment by scheuerer** [comment]
https://www.dropbox.com/s/zesnj39qoblkaeq/IMG_2740.MOV?dl=0

Here is the link to the Video which Shows you the issue...

**Comment by scheuerer** [comment]
I have now tryed again. Several pressing shortly, like 10 to 15 times the play/stop button will not help.
Pressing very fast the button for the next Titel bring Fermata and AA for crashing. NO reaction anymore from AA, need to reboot my mobile…

**Comment by AndreyPavlenko** [comment]
It should resume playing automatically. I just tested on my device and it works.
Could you send me the log file /sdcard/Android/data/me.aap.fermata.auto.dear.google.why/files/Fermata.log?

**Comment by scheuerer** [comment]
I just send you the logfiles I found…Mit freundlichen GrüßenJochen Scheuerer_________________________________Jochen ScheuererWaidmannstraße 3489233 Neu-Ulm / BurlafingenTel.: 0731 / 715244Fax.: 0731 / 71101328Mobil: 0173 / ***@***.***_________________________________Am 03.08.2023 um 22:02 schrieb Andrey Pavlenko ***@***.***>:﻿
It should resume playing automatically. I just tested on my device and it works.
Could you send me the log file /sdcard/Android/data/me.aap.fermata.auto.dear.google.why/files/Fermata.log?

**Comment by Alejandro2454** [comment]
Sospechosa la situación...
Yo no tengo problemas, cuando envío o cuando  leo y/o escucho un WhatsApp,
por supuesto que Fermata entra en pausa  sin embargo terminado el WhatsApp
Fermata continua desde donde quedo pausado y yo encuentro que eso es lo
correcto
Saludos
Alejandro

**Comment by krzysior78** [comment]
I did some tests today and it turned out that in case of YouTube playing, setting video speed other than 1.0 leeds to problem which I described earlier. On default speed video doesn't stop after car notification disappears from screen. So it looks like it's different issue than described in first post in that thread...

**Comment by scheuerer** [comment]
I made a test today. I was watching the Video on my mobile and called me from a other Phone. The Video stopped. I canceld the call und the notification disappered. After that the Video was not continue and I was Not Abel to wacht it. So it is not an WhatsApp or AA issue, it an issue alone from Fermata. After each Interrupt the Video will not continue...

**Comment by scheuerer** [comment]
I assume I found the root cause. The app has not have the notification privilage. I change that the app has now all privilage. And now it works. At least on the mobile. Will test it tomorrow under AA in the car......

**Comment by scheuerer** [comment]
Now… I have tested the new settings, but without success. So still the same issue under AA that it stops and never returned. Need to resetbthe mobile… without AA it works normal…
Please have a look Andrey….

**Comment by AndreyPavlenko** [comment]
@scheuerer  Have you tried the apk I send you by email?

**Comment by scheuerer** [comment]
I have not get a apk from you...

⁣Mit freundlichen Grüßen 
Jochen Scheuerer 
  
_________________________________
***@***.***
_________________________________
 ​

**Comment by scheuerer** [comment]
Please send to ***@***.***

Thanks

⁣Mit freundlichen Grüßen 
Jochen Scheuerer 
  
_________________________________
***@***.***
_________________________________
 ​

**Comment by AndreyPavlenko** [comment]
Please, try this version and send me the log - https://drive.google.com/file/d/1nnDFU6XMjhtsNB4qHYEwcWZ-a1f3XJly/view?usp=drive_link.

**Comment by scheuerer** [comment]
After changed now the video player from VLC to media-player it works without stoping the video. It seems that VLC is not compatible in this case.
