### ISSUE TITLE
Iptv Channels not loading

### ISSUE THREAD

**Issue by JohnnWick37** [AndreyPavlenko/Fermata#283]
Hello first thank you for your great software. My issue is about iptv. My url is; http://iptv3.tjurk.com:8000/get.php?username=……..&password=………….=m3u_plus&output=mpegts
But with this url the channels are not loading. 
I also tried like this; http://iptv3.tjurk.com:8000/get.php?username=…………&password=………=m3u_plus&output=ts

So the same thing please help.

**Comment by AndreyPavlenko** [comment]
Have you tried to open the link in a web browser? Does it download the playlist?

**Comment by JohnnWick37** [comment]
Yes i tried like that and it loaded channels. Thank you very much.
