### ISSUE TITLE
Bug: app crashes when filtering YouTube results

### ISSUE THREAD

**Issue by CodexHere** [AndreyPavlenko/Fermata#284]
First, love the app! Thank you for making road trips amazing!

Whenever clicking either of the two drop downs after performing a YouTube search, the app basically resets to the folder view.

I can't sort 😅

**Comment by AndreyPavlenko** [comment]
I'm unable to reproduce.

**Comment by CodexHere** [comment]
I should probably add it only happens on the android auto display, it works fine in the app on my phone.
