### ISSUE TITLE
unable to scroll

### ISSUE THREAD

**Issue by ahhl** [AndreyPavlenko/Fermata#29]
andrey, fermata auto is marvelous. i dont have to change my headunit in order to watch movies etc on my non touchscreen ntg5. 1 mercedes gla.

i got one issue at them moment. on some older version of fermata auto cant remember which one, the folder, favourite, music i was able to scroll up down more than one screen. now the latetest version, it wont able to scroll more than one screen, it just jump out of fermata menu and goes into android auto menu. pls fix this pleaseeese. because if i have list of 50s, i only to scroll down 5 list only (depend whether it text or icon list)

**Comment by ahhl** [comment]
except for youtube and browser manu, i can scroll down endless without being able to select anything.

**Comment by AndreyPavlenko** [comment]
I tried on emulator, but, unfortunately, I didn't find a way how to intercept rotary controller events.

**Comment by ahhl** [comment]
anyway that i can assist?

**Comment by ahhl** [comment]
on the rotary controller, on rotate right or left, it just move the cursor to end of line, it there another line below, the cursor move to the next line first position (either leftmost or rightmost) however if theres third line, the page suppose to move up so that the cursor can go to the rightmost or leftmost position of the third line. this is what happen.

**Comment by ahhl** [comment]
i have an idea. create many favorites menu. that will enable to access tv channels that beyond two line by saving the channel into different favorites

**Comment by AndreyPavlenko** [comment]
Could you pleases try the new version https://github.com/AndreyPavlenko/Fermata/releases/tag/v1.8.1b ?

**Comment by Alejandro2454** [comment]
Dear Andrey
 When watching any video and pressing "folder" this folder does not work.
Does not display content
 Watch for your comments
 Alexander

**Comment by AndreyPavlenko** [comment]
Sorry, I didn't get it, could you please clarify?

**Comment by ahhl** [comment]
andrey
1.8.1b now work with my merz rotary controller.
tqvm

**Comment by Alejandro2454** [comment]
Estimated,
 If you try to click on "Folders" it doesn't work.
 Greetings
 Alexander

**Comment by Alejandro2454** [comment]
Dear, I remind you that my screen is non-touch.

**Comment by AndreyPavlenko** [comment]
Thanks. To be fixed in the next version.
