### ISSUE TITLE
Fermata Auto No Longer Showing

### ISSUE THREAD

**Issue by SGKrueger** [AndreyPavlenko/Fermata#290]
Fermata Auto had been working perfectly. I updated to the latest release and it no longer shows in Android Auto.  Uninstalled and re-installed earlier version. Still not showing. Reinstalled with KingInstaller. Still not showing. Help?
Galaxy S23 Ultra, Android Version 14, Kernel Version 5.15.94

**Comment by AndreyPavlenko** [comment]
Did you use this version of KingInstaller https://github.com/fcaronte/KingInstaller/releases?

**Comment by SGKrueger** [comment]
> Did you use this version of KingInstaller https://github.com/fcaronte/KingInstaller/releases?

Yes. Just checked to make sure.

**Comment by AndreyPavlenko** [comment]
Try this https://github.com/AndreyPavlenko/Fermata/issues/269#issuecomment-1623567587

**Comment by SGKrueger** [comment]
> Try this [#269 (comment)](https://github.com/AndreyPavlenko/Fermata/issues/269#issuecomment-1623567587)

Still no luck.

**Comment by Carlos1988rm** [comment]
no sirve eso xa nada en pixel 8 pro. NO FUNCIONA NADA DE KINGINSTALLER !!!

**Comment by jmckeejr** [comment]
For some reason aamirror is now showing up but not Fermata Auto. Must be something can be adjusted to make it show since it's working with other app. Will keep an eye out here for any updates. Thanks so much for your work

**Comment by AndreyPavlenko** [comment]
> For some reason aamirror is now showing up but not Fermata Auto.

Have you installed aamirror before the update to A14?

**Comment by jmckeejr** [comment]
> > For some reason aamirror is now showing up but not Fermata Auto.
> 
> Have you installed aamirror before the update to A14?

I had both installed prior to the update and have updated both apps after the system update (because both were not showing). I'm currently on a slightly older version of Android Auto in hopes to get this working (10.8...). Aamirror is currently working but I much prefer Fermata as I don't need my screen on on phone.

**Comment by Majeed91** [comment]
> Did you use this version of KingInstaller https://github.com/fcaronte/KingInstaller/releases?

What about not rooted devices
I had the app working fine before the update
