### ISSUE TITLE
Next button on YT wrong function 

### ISSUE THREAD

**Issue by DavidVlk** [AndreyPavlenko/Fermata#291]
On YouTube homescreen next button plays next video. However in Library, when playing from playlist, next switches off fullscreen to a smaller window, previous does nothing. I have the last app version and tried uninstalling the app.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/301#issuecomment-1751321287

**Comment by AndreyPavlenko** [comment]
Try this build - https://github.com/AndreyPavlenko/Fermata/pull/316#issuecomment-1802630566
