### ISSUE TITLE
Access Folders In Android Data Path

### ISSUE THREAD

**Issue by FastenM** [AndreyPavlenko/Fermata#292]
I'd like to add folders like telegram that are stored in the android/data/ path 

A lot of 3rd party file explorers found a way to access the android data path for android 13 and above 

Was wondering if you can look into how they implemented it, and if you can add it to your app as well.

**Comment by AndreyPavlenko** [comment]
If you use the Fermata Auto version installed from Github, then the app should request the "manage all files" permission and, if granted, you should have access to all files.

**Comment by FastenM** [comment]
Yeah so even after granting all files access I'm still not able to add folders from the android data path

**Comment by AndreyPavlenko** [comment]
Do you use Fermata Auto installed from this repository?

**Comment by FastenM** [comment]
> Do you use Fermata Auto installed from this repository?

Yes
