### ISSUE TITLE
no longer shwon in AA Launcher

### ISSUE THREAD

**Issue by HGlab01** [AndreyPavlenko/Fermata#293]
First of all: thanks for this great app!

On my old device (Xiaomi Mi A3) it worked finde
Now I switched to Pixel 7a (Android 13) and I was able to install the app via Kinginstaller withoit any issues.
I can open the app in the phone, but der is no icon on the AA launcher.

I tried the install with latest (1.9.4) and 1.8.11 with Kinginstaller latest (1.4)

What is intereseting in my point of view, is, that it is even listed in the AA app
![image](https://github.com/AndreyPavlenko/Fermata/assets/54232526/edade5fa-d854-42b1-8eaf-5ace5849ef30)

Phone figures
![image](https://github.com/AndreyPavlenko/Fermata/assets/54232526/98abcbb5-451c-4738-90c2-e88b9c2622b0)

Is there any chance to get is running again?
Thanks in advance for your support!

**Comment by AndreyPavlenko** [comment]
Try this https://github.com/AndreyPavlenko/Fermata/discussions/268#discussioncomment-6373435

**Comment by HGlab01** [comment]
Thanks it works! From my understanding it will affect more and more people if newer package installers are not supported :-(
