### ISSUE TITLE
Android 14 beta

### ISSUE THREAD

**Issue by tarasov503** [AndreyPavlenko/Fermata#298]
For anyone experiencing problems with Fermata after installing the Android 14 beta:

I'm using a Google Pixel 6a, and I recently upgraded to the A14 beta early this morning. Since the update, everything has been functioning correctly except for Fermata. Here's what I did to resolve the issue:

1. I opened the Fermata app on my phone and checked the settings to ensure that the developer settings hadn't changed, and that it still allowed third-party apps, which were the same as before.

2. Next, I went to the app's info page and cleared the cache and memory.

3. After that, I noticed that all the app permissions were turned off (microphone, files, notifications, calls, etc.). I individually enabled each permission, one by one.

After following these steps, Fermata started working again for me. I hope this solution helps anyone else experiencing similar issues!

**Comment by aross6** [comment]
> For anyone experiencing problems with Fermata after installing the Android 14 beta:
> 
> I'm using a Google Pixel 6a, and I recently upgraded to the A14 beta early this morning. Since the update, everything has been functioning correctly except for Fermata. Here's what I did to resolve the issue:
> 
> 1. I opened the Fermata app on my phone and checked the settings to ensure that the developer settings hadn't changed, and that it still allowed third-party apps, which were the same as before.
> 2. Next, I went to the app's info page and cleared the cache and memory.
> 3. After that, I noticed that all the app permissions were turned off (microphone, files, notifications, calls, etc.). I individually enabled each permission, one by one.
> 
> After following these steps, Fermata started working again for me. I hope this solution helps anyone else experiencing similar issues!

This worked perfect for me to get Fermata Auto working on AA Auto again on Android 14. Thank you!!!

**Comment by aamaamilan** [comment]
Not healping here unfortunately (P6P), even with Fermata fresh installiation, can you please provide your AA version.
