### ISSUE TITLE
Android 6.5.612134 fermata auto not working

### ISSUE THREAD

**Issue by seqkart** [AndreyPavlenko/Fermata#30]
Hi, as I was running fermata auto on android 6.3 perfectly but now android 6.3 has to be upgraded to latest version being not supportive. So kindly help and upgrade or do something for the new update

**Comment by AndreyPavlenko** [comment]
Unfortunately, the only solution for Android 11 is root.

**Comment by seqkart** [comment]
Hi Andrey

I don't want to root my phone is there any other way?

Please let me know

Thanks
Rohit Aggarwal

**Comment by AndreyPavlenko** [comment]
Android 10 still works with the latest version of AA.
