### ISSUE TITLE
IPTV no longer works on 1.9

### ISSUE THREAD

**Issue by Dazou0** [AndreyPavlenko/Fermata#300]
Hello, thank you for the app. 
However, since the new version, IPTV no longer works.
It's impossible to understand anything before just with my http link everything was working correctly. 
But now for it to work I have to put the .m3u file. 

On the other hand, it does not work with the new version of Fermata, I have to go through version 1.8.10.

Why does it no longer work with the http link?  
My list works perfectly on all my other apps (smarter player, ipcartv, smart iptv)

Thank you for your help

**Comment by Dazou0** [comment]
Thanks for the help, if I understood correctly I need to write Google in User-Agent?  Like on the photo ? 

If so I tried in the latest version but I still don't have any list.
![Screenshot_2023-10-03-17-33-02-340-edit_me aap fermata auto dear google why](https://github.com/AndreyPavlenko/Fermata/assets/146764693/af09cef4-e615-4e37-8d6d-373b7b975c39)

**Comment by AndreyPavlenko** [comment]
Correct. If you open the link in a web browser on your phone, could you download the playlist?

**Comment by Dazou0** [comment]
Yes it downloads, but it takes time before starting the download. My .m3u file weighs 94 MB

**Comment by AndreyPavlenko** [comment]
Probably, it fails to download due to timeout. You could see in the log if this is the case.

**Comment by Dazou0** [comment]
Yes this is due to the response time (Request timeout). 

But I don't understand that's why my .m3u file works on version 1.8.11 and from 1.9 there is nothing left (no more channel found)

**Comment by AndreyPavlenko** [comment]
Probably, in 1.8.11 a different timeout was used. I'll add an option for increasing the timeout.

**Comment by AndreyPavlenko** [comment]
Try this version - https://drive.google.com/file/d/1lYr5T7Hu5DfCvfV3wepajrvRsmjw57d5/view?usp=sharing . I've added the timeout configuration to the connection settings.

**Comment by Dazou0** [comment]
I'm sorry but it still doesn't work, no channel with the .m3u file and with the http link "request timeout"

But anyway thank you for trying to find the solution

**Comment by AndreyPavlenko** [comment]
I thought it works with the file, as you mentioned in the first message.

**Comment by BilalHalayqa** [comment]
I have the same issue. Any update?

![Image](https://github.com/user-attachments/assets/02cec5c6-8eab-42e3-acfc-28d1b1b30de2)

**Comment by BilalHalayqa** [comment]
I just fixed it by replacing m3u_plus with m3u.

Keeping this to help others as it took me a year to find it :).
