### ISSUE TITLE
Skip / previous on youtube

### ISSUE THREAD

**Issue by Aagge82** [AndreyPavlenko/Fermata#301]
when i click on the steering wheel, i can't skip to next song or previous song on youtube.
It doesn't work when i click the screen either. 
I tried reinstall, also with kinginstaller.
It worked before i upgraded to new version of Fermata auto and fermata control

**Comment by AndreyPavlenko** [comment]
Reinstallation will not fix the problem. Something has changed in the Youtube web interface.

**Comment by iphone8gb** [comment]
Is there any fix for this issue? This was a very good app and working perfectly before. Thanks.

**Comment by AndreyPavlenko** [comment]
This functionality works on the main page, but not in Library. Youtube, built into this app, is the original youtube web interface. When you press the prev/next buttons, the app finds the corresponding buttons in the youtube web interface and clicks on it. Seems, the buttons have been removed from the web interface. Open youtube in a mobile web browser, go to Library, start playing and click on the video. There are no any buttons, except a single pause button in the middle.

**Comment by awais-amjed** [comment]
@AndreyPavlenko I see that the next/previous buttons are gone for libraries in the web interface. Can you maybe try to read the next and previous songs from the playlist and click them? 
Something like this

![image](https://github.com/AndreyPavlenko/Fermata/assets/73714615/e0876a41-ca2d-42fe-88a5-f303ce16fa56)

I am not much familiar with android development and the limitations of Web View (if you are using that), so Not sure if this is possible.

**Comment by AndreyPavlenko** [comment]
@awais-amjed I think, it's possible. The app uses JS code injection to emulate the button clicks - https://github.com/AndreyPavlenko/Fermata/blob/master/modules/web/src/main/java/me/aap/fermata/addon/web/yt/YoutubeWebView.java#L136 .

**Comment by awais-amjed** [comment]
Yessss looks possible, and a workaround for the playlist needing to stay open could be that once the page loads, just extract all the links from the playlist into an array and iterate over them (based on next/prev) by updating the URL, since at least for now the youtube page isn't dynamic and the URL changes when you switch to next song or previous song.
When the list reaches the end, youtube loads more songs, and at that point, the list can be updated.
