### ISSUE TITLE
[Huawei harmonyOS] fermata not showing bug like Oppo and realme 

### ISSUE THREAD

**Issue by Kandaraa** [AndreyPavlenko/Fermata#307]
Hello

I have a honor magic 2 with harmonyOS 3.0, Android auto 9.4.6, fermata auto 1.9.1. the app was working fine suddenly it's stop show up in Android auto. I've tried:
- reinstalling the app with king installer 1.3 and 1.4
- using the king installer option for oneplus and realme
- reinstalling the app with AAAD
- downgrade the version of fermata and Android auto even trying the last version 1.9.5
- trying other alternatives (such as carstream cartube it figure out but shows no message during this drive)

Maybe it's a bug like with Oppo and realme because None of the attempt above helped me to show the app in Android auto.
Did you have please any suggestions to solve my issue. 
Thanks

**Comment by fcaronte** [comment]
Try to install Google PackageInstaller, probably your phone use another one, if give error to install it will be a problem and probably can't fix without root , if will install and then you have two packages installer, so then you can use kinginstaller and select the new package installer when go to install an app

**Comment by Kandaraa** [comment]
Actually trying to install google package installer 14 shows error. How can in resolve this. I don't want to root my phone. Is there any other costum pckage installer that can do the job.
Thanks

**Comment by fcaronte** [comment]
> Actually trying to install google package installer 14 shows error. How can in resolve this. I don't want to root my phone. Is there any other costum pckage installer that can do the job.
> Thanks

I don't know if can work, but Google package installer you need to try to get the same version of your android base version, I don't think you phone is based on A14 so probably you need to try version 13 or 12 but is not sure will work, Huawei have problems with Google things and sincerely I was thinking they haven't android auto at all
