### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by sanor2002** [AndreyPavlenko/Fermata#31]
Hi
I have fermata 1.8 on Android auto 6.3.
Don't work anymore.
Thanks

**Comment by Alejandro2454** [comment]
Dear Andrey
 When connecting the usb to the car android auto forces to update to
version 6.5.612 that does not allow to use fermata auto
 Please, I ask you to solve this serious problem.
 Greetings
 Alexander

**Comment by denhik1301** [comment]
Не работает

**Comment by AndreyPavlenko** [comment]
Unfortunately, the only solution is to use root.

**Comment by Alejandro2454** [comment]
Dear Andrey
 I have always used root

**Comment by Alejandro2454** [comment]
Dear Andrey: Receive my apologies.  I can access fermata without problems
with the latest version of android auto

**Comment by AndreyPavlenko** [comment]
> Dear Andrey: Receive my apologies. I can access fermata without problems with the latest version of android auto

Thanks for confirmation.
