### ISSUE TITLE
Iptv not working with 1.95

### ISSUE THREAD

**Issue by LinkT3** [AndreyPavlenko/Fermata#312]
Soon as I updated my iptv isn't working through tv section. It only works through m3u playlist. I've tried changing user agent and increasing timeout to no avail.

**Comment by DIMA761116** [comment]
My TV section doesn't work either
![Screenshot_2023-11-20-12-56-28-613_me aap fermata auto dear google why](https://github.com/AndreyPavlenko/Fermata/assets/104160972/34313a70-176e-46b4-b9c5-b8ff3917205e)

**Comment by AndreyPavlenko** [comment]
Is there some error in the log /sdcard/Android/data/me.aap.fermata.auto.dear.google.why/files/Fermata.log?

**Comment by DIMA761116** [comment]
sdcard there are no errors, if I install version 1,9,4 everything works fine

**Comment by DIMA761116** [comment]
There was probably a problem with the update, I deleted 195, installed 194, updated 195 and everything worked
