### ISSUE TITLE
Зависает при запуске на телефоне

### ISSUE THREAD

**Issue by hrom-code** [AndreyPavlenko/Fermata#32]
Телефон POCO X3. Miu12, Android 10. Magisk. При запуске открывается фиолетовый экран и на этом все. 
Fermata player из плей маркета работает норм. 
![Screenshot_2021-06-28-08-59-43-854_me aap fermata auto](https://user-images.githubusercontent.com/86617321/123667073-fd6be280-d863-11eb-9f9c-5ce9d0d12f34.jpg)

**Comment by AndreyPavlenko** [comment]
Какая версия? Как и откуда установлена.

**Comment by hrom-code** [comment]
Качал с гитхаба. 
Пробовал версии fermata-1.8.0-auto-universal-arm.apk, fermata-1.7.10-auto-universal-arm.apk - зависают обе версии. 
fermata-1.0.1-auto-release.apk (нашел на 4pda) запустилась на телефоне. Root не просило. При просмотре видео, не могу вернуться в основной экран.

**Comment by AndreyPavlenko** [comment]
Пришлите, пожалуйста, лог - /sdcard/Android/data/me.aap.fermata.auto/files/Fermata.log

**Comment by hrom-code** [comment]
В этой папке пусто. В папке cache тоже. 
--
Отправлено из Mail.ru для Android вторник, 29 июня 2021г., 00:29 +07:00 от Andrey  ***@***.*** :

**Comment by AndreyPavlenko** [comment]
В POCO X3 64-битный процессор. Попробуйте установить fermata-1.8.0-auto-universal-arm64.apk .

**Comment by hrom-code** [comment]
Удалил. Перезагрузил. Установил - результат тот же. Пустой фиолетовый экран. В папке тоже пусто.

**Comment by hrom-code** [comment]
Из root explorer все норм поставилрсь и зарустилось. До этого ставил из штатного проводника MIUI. Не знаю с чем связано :-(

**Comment by hrom-code** [comment]
Сорри за беспокойство
