### ISSUE TITLE
Full screen is blank

### ISSUE THREAD

**Issue by Frennic** [AndreyPavlenko/Fermata#321]
Just updated to this latest version. Now when I full screen web or videos, the screen is just blank. It's worked fine in all previous versions. S22 ultra

**Comment by Muly31** [comment]
Same here on galaxy 21 ultra

**Comment by Androjs** [comment]
The same on S23

**Comment by AndreyPavlenko** [comment]
Try this build - https://drive.google.com/file/d/1ozLjrB8dH-Nrc-rT9acx7ttumHdKJ1B1/view?usp=sharing

**Comment by Muly31** [comment]
Hi
I installed the APK but now I don't see fermata auto on Android auto...

**Comment by AndreyPavlenko** [comment]
Have you used KingInstaller?
Hope, your Android version is not 14.

**Comment by Muly31** [comment]
Hi
I just installed android 14 a week ago.
