### ISSUE TITLE
Voice search/command on phone or Vehicle stops streaming.

### ISSUE THREAD

**Issue by Gullzway** [AndreyPavlenko/Fermata#322]
When streaming an m3u link, if I use the voice search on my phone, or push the Voice command button on my steering wheel(ie. to Open my Garage with Google commands,) the stream in Fermata instantly stops and goes back to the Folder/TV view.

Is there a way to prevent this?

**Comment by AndreyPavlenko** [comment]
Try this build - https://drive.google.com/file/d/1ozLjrB8dH-Nrc-rT9acx7ttumHdKJ1B1/view?usp=sharing

**Comment by Gullzway** [comment]
Awesome! Thanks, that fixed it.
Appreciate the great app.
