### ISSUE TITLE
YouTube flicker

### ISSUE THREAD

**Issue by borygo77** [AndreyPavlenko/Fermata#323]
Hi Andrey! Thank you for your great fermata! Brill job done here!
I do have strange youtube bookmark flicker and no idea why. Is that refresh feature or what? It's unusable when it always coming back to top of the list.

Here is short video how it looks like.
[]()https://youtube.com/shorts/ws2wJb8DrTA?si=8Cm7ATwIEw7GYVg8[]()

**Comment by AndreyPavlenko** [comment]
Seems like it's trying to play something. Try long pressing the play/pause button to stop the playback.

**Comment by borygo77** [comment]
It's not plugged in to a car. Just playing with setup on the phone itself. Pressing pause button doesn't resolve issue.

**Comment by AndreyPavlenko** [comment]
On long press, the control panel should disappear.

**Comment by borygo77** [comment]
This is actually not happening when connected to a car. Looks like it picks video in focus and trying to play it.

**Comment by fcaronte** [comment]
Maybe is similar to my problem, I discovered that on YouTube you need to go on top right corner (your profile) go to YouTube settings and disable all auto play  features and then for me start to work correctly without
