### ISSUE TITLE
Subtitles automatically turn off when unpausing

### ISSUE THREAD

**Issue by phly95** [AndreyPavlenko/Fermata#326]
When watching anime, the subtitles go away if you pause and unpause the video.

**Comment by AndreyPavlenko** [comment]
Could you share a video to reproduce the issue?

**Comment by phly95** [comment]
This happens both on phone screen and car screen. Here's a screen recording of it happening on the phone screen.

https://github.com/AndreyPavlenko/Fermata/assets/3526540/0642c650-5344-4b8a-8284-4d0780aae0f8

**Comment by AndreyPavlenko** [comment]
Thanks, I found the problem. You could get the fixed version here - https://drive.google.com/file/d/1ER89nOt52FqQDJhrHlaHnw7mdoIR3w5v/view?usp=drive_link

**Comment by phly95** [comment]
The doesn't seem to work

**Comment by AndreyPavlenko** [comment]
Updated the link.

**Comment by phly95** [comment]
Thanks. Seems to work properly now.
