### ISSUE TITLE
Question regarding updating samsung s23 FE

### ISSUE THREAD

**Issue by tarasov1503** [AndreyPavlenko/Fermata#340]
I just got a new samsung s23 FE and am afraid to update my phone , forcing it to lose the fermata app. For some reason I can't figure out how to find the place to stop automatic updates, but can onlypostpone it for now. Does anyone know if this particular software update os safe to do without losing fermata auto? Attached a screenshot:
![Screenshot_20231221_164231_Software update](https://github.com/AndreyPavlenko/Fermata/assets/154566547/0e34d60d-b26a-4024-92ec-a6dd3fed78f7)

**Comment by mchupp** [comment]
Don't update

**Comment by jmckeejr** [comment]
If you use Google search you can disable the update app via ADB commands until you are ready to update. Here's what I found at first glance. 

https://xdaforums.com/t/disable-system-update.4223781/post-84367233
