### ISSUE TITLE
the car fermata does not work  AA: 10.9.634644-release

### ISSUE THREAD

**Issue by SalerPL** [AndreyPavlenko/Fermata#341]
Fermata Auto: 1.9.6 does not work
 AndroidAuto: 10.9.634644-release.  android version 14 One UI 6.0 on samsung galaxy s22.  I have already tried various options and unfortunately in AA only fermata control is visible.  please help

**Comment by damche86** [comment]
Any solution?

**Comment by maripic69** [comment]
И аз чакам!На Android 13 работеше перфектно

**Comment by AndreyPavlenko** [comment]
See https://github.com/AndreyPavlenko/Fermata/issues/327
