### ISSUE TITLE
Hi, does this help with android 14?

### ISSUE THREAD

**Issue by Majeed91** [AndreyPavlenko/Fermata#345]
https://github.com/AndreyPavlenko/Fermata/discussions/315#discussioncomment-7663582

**Comment by AndreyPavlenko** [comment]
No, it doesn't.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1890143200

**Comment by AndreyPavlenko** [comment]
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327
