### ISSUE TITLE
Export/Import missing from Settings menu on Google TV

### ISSUE THREAD

**Issue by richaardvark** [AndreyPavlenko/Fermata#349]
Hello,

Even though I'm running the same version of Fermata (1.9.6 (233)) on both my Android phone as well as on my Google TV (Android TV) the Export and Import many choices are not appearing under the "Other" area of the Settings menu on my television. I have a bunch of bookmarks created on my phone and I want to be able to import these bookmarks as well as other settings to my smart TV which is running the same version of Fermata without any issues otherwise. Why is it missing from the TV instance?

**Comment by AndreyPavlenko** [comment]
Most probably, because there is no file picker on ATV devices, the app uses it to pick files/folders.

**Comment by AndreyPavlenko** [comment]
Should be fixed in the version 234, wait for the google play update.
