### ISSUE TITLE
1.9.7 YouTube Playlist Randomizer does not really work.

### ISSUE THREAD

**Issue by dreimer1986** [AndreyPavlenko/Fermata#359]
When I select a Playlist and then instead of Play all choose Random next to it it sometimes starts some song close to the start of the playlist and then seems to go on in row. No random playback is possible right now.

**Comment by AndreyPavlenko** [comment]
YouTube, built into this app, is just a web page, almost the same as you see in a mobile browser. There is no any "YouTube Playlist Randomizer" implementation in this app.

**Comment by dreimer1986** [comment]
I agree, but I wondered if the next track fix used for the mobile site could make problems here. https://github.com/AndreyPavlenko/Fermata/pull/343
If not then this is clearly a bug for YT and can indeed be closed here.

**Comment by AndreyPavlenko** [comment]
Have you tried to reproduce the issue in a mobile browser? If there is the same issue, then this is a YT issue.

**Comment by dreimer1986** [comment]
I did as you said on the same phone and was just shocked... The randomizer is a joke and my sometimes not starting video (grey rectangle instead) is there, too. So I close this report and from now on I will first compare with the YT mobile page and then write a report if there is really a problem on yur side and not on YT itself.
