### ISSUE TITLE
Web browser no audio on Plex (AAC 5.1 audio format)

### ISSUE THREAD

**Issue by dumpadoor** [AndreyPavlenko/Fermata#36]
I think the issue is Chrome not supporting this audio format. I tried with the phone's chrome browser and did not have sound but there is sound on the same file on Firefox.

I tried to change the agent but don't think it did anything (or maybe I did it wrong.)

Youtube audio is working perfectly fine too.

**Comment by AndreyPavlenko** [comment]
Unfortunately, I can do nothing with it, if the audio format is not supported by chrome.

**Comment by dumpadoor** [comment]
> Unfortunately, I can do nothing with it, if the audio format is not supported by chrome.

Is there any way to change the agent to Firefox?

**Comment by AndreyPavlenko** [comment]
You can change the User-Agent in the settings. Open this https://www.whatismybrowser.com/detect/what-is-my-user-agent url in Firefox and copy the User Agent string.

**Comment by ektorasdj** [comment]
Hello
Did you manage to fix it?
I tried changing the user agent but i still do not have sound. ( At least i get around to it by transcoding to a lower resolution. I suppose the sound gets transcoded to a compatible format)
