### ISSUE TITLE
Fermata Auto 1.9.7 does not work on my Pixel 6a with Android 14

### ISSUE THREAD

**Issue by pelado66** [AndreyPavlenko/Fermata#365]
I installed fermata auto 1.9.7 with kingstaller 1.4 with all permissions and the icon does not appear in AA. I have pixel 6a with A14. I've tried everything I can and nothing. Any ideas?

**Comment by Gullzway** [comment]
You'll have to root the phone.

Install Magisk
Magisk => Settings => Magisk => Check Zygisk
Install LSPosed (Zygisk) + Shamiko
Install the Android-Auto-XLauncher-Unlocked app with KingInstaller
LSPosed => Modules => Check Enable module + Check Android Auto
Reboot

Install Fermata with KingInstaller

**Comment by Saicopate** [comment]
So Fermata Auto is only on rooted devices now?

**Comment by AndreyPavlenko** [comment]
For non rooted you may use AAwireless. For more details - https://github.com/AndreyPavlenko/Fermata/issues/327.

**Comment by AndreyPavlenko** [comment]
Closing as duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327
