### ISSUE TITLE
Update no working

### ISSUE THREAD

**Issue by TITICUBA** [AndreyPavlenko/Fermata#366]
Since the fermata auto update it is not recognized by the screen of my vehicle

**Comment by cosminmocan** [comment]
Read the other issues please

**Comment by AndreyPavlenko** [comment]
Android 14?

**Comment by TITICUBA** [comment]
Yes. S23 Ultra

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/327

**Comment by TITICUBA** [comment]
Excuse me, but are you telling me that my solution is to learn to program?🥲

**Comment by AndreyPavlenko** [comment]
No. Currently, the only solution is either root or AAwireless.
Android Auto only supports apps installed from google play.

**Comment by TITICUBA** [comment]
I understand. Well, the solution I gave is to use another phone with an old
version and connect it with an access point. I will wait until there is
another solution for the average user. 😅Thank you for your response.
