### ISSUE TITLE
It seems like Fremata Auto isn't appearing on the navigation screen, possibly because it's not showing up in the launcher customization settings

### ISSUE THREAD

**Issue by jaemyeong2** [AndreyPavlenko/Fermata#374]
I'm sorry for asking frequently, but I'm using Fremata Auto, and it's not appearing in the Android Auto > Launcher Customization settings, so I can't see it in the navigation. What should I do? I'm on One UI version 6.0, Android 14, and using an AA machine

**Comment by szafir51** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/327

**Comment by AndreyPavlenko** [comment]
Simple solution - https://www.aawireless.io.
Probably, a temporary solution with screen mirroring - Android 14 #327 (comment)
Root.
