### ISSUE TITLE
Fermata Auto en Android 14

### ISSUE THREAD

**Issue by Carlos1988rm** [AndreyPavlenko/Fermata#375]
Fermata auto no me funciona ni con AAAD ni con Kinginstaller en Pixel 8 pro con Android 14. Alguna solución? Gracias

**Comment by dreimer1986** [comment]
There are more than 10 issues for that topic. Why do you open a 11th one?

**Comment by Carlos1988rm** [comment]
porque mucho escrito pero ninguna solución hasta el momento q me sirva, una pena. En mi caso no vengo de Android 13...

**Comment by AndreyPavlenko** [comment]
1. Simple solution - https://www.aawireless.io.
2. Probably, a temporary solution with screen mirroring - https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1915058419
3. Root.
