### ISSUE TITLE
Fermata Auto 1.9.8, Xiaomi HiperOS 1.0.2.0, Android 14

### ISSUE THREAD

**Issue by petersonti** [AndreyPavlenko/Fermata#376]
I have a Poco X5 Pro, and after I updated my phone to version Xiaomi HyperOS 1.0.2.0.UMSMIXM, Android 14 UKQ1.231003.002 and Fermata Auto stopped working.
I uninstalled and reinstalled it, and the icon disappeared.
I tried this method #327 by fcaronte but it didn't work either. 
The Fermata Control works, but Fermata Auto doesn't appear on Android Auto.
Will there be any solution? I'm thinking about downgrading to Android 13.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/375#issuecomment-1918913110

**Comment by mrudnik** [comment]
Hello,
Having the exact same issue. After upgrading to the Xiaomi Hyper OS - my Fermata stopped working and after I have upgraded it to the latest (apparently it was not updated), it didn't appear anymore on my Android auto screen (it does appear on the mobile itself). Please share the solution. I am very frustrated... 🙏

**Comment by 13031976** [comment]
Ho lo stesso problema il mio Xiaomi si e aggiornato con HyperOS e fermata auto nn funziona più

**Comment by enricopillon** [comment]
Hello,
I have the same issue. Is there no solution yet? if not root

**Comment by LeoSCL** [comment]
Yo también tengo rl mismo problema con un móvil Xiaomi 11T Pro con HyperOS 1.0.4...
Por favor alguna solución.
Gracias
