### ISSUE TITLE
Fermata Auto used to work 

### ISSUE THREAD

**Issue by Asem230** [AndreyPavlenko/Fermata#38]
Hello 
Fermata auto used to be show on AA on my car but after installing Fermata media player from Google player Suddenly only Fermata control is showing on my AA car screen 
No matter who many time uninstall all Fermata player and Fermata auto and fermata control and installing only latest version of Fermata auto 1.8 and fermata control 
Only the control is showing on my screen 
My phone is not rooted and my AA version is 
![Screenshot_20210901_091609_com google android projection gearhead](https://user-images.githubusercontent.com/89900318/131628754-c9042a91-b836-4a17-9d2a-a4a1cf590361.jpg)

**Comment by AndreyPavlenko** [comment]
Hello. What is your Android version? How have you installed Fermata Auto?

**Comment by Asem230** [comment]
Hello
My Android ver 10
Yes I installed latest version 1.8.0 from your GitHub page
Even tried to install older version
But it show in my phone and work perfectly on my phone
I used it manly for IPtv with M3u list and it work on my phone
The Fermata control is showing on my car AA and when i press it it open
Fermata but the it show Fermata control as the application name
And the M3u is there but all the channels work only Audio only and it can
be working on my phone video and Audio in the same time


BR
Asem Osman
+201227244217

**Comment by AndreyPavlenko** [comment]
Did you follow this installation instruction https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/ ?

**Comment by Asem230** [comment]
This is my AA app list
Although i installed Fermata Auto on my phone
Only Fermata (download from play store) and Fermata control is showing on
my AA apps list as attached photo

BR
Asem Osman
+201227244217
