### ISSUE TITLE
Fermata Auto v1.9.8 not showing up in AA anymore 

### ISSUE THREAD

**Issue by Cr4z33** [AndreyPavlenko/Fermata#380]
Both with my S22 Ultra and my S24 Ultra there's no way.

Tried both normal installation and Kinginstaller.

Is there any block made by latest Android/OneUI? 😞

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/327

**Comment by Maler215** [comment]
Habra quizas alguna forma de hacerlo funcionar con una maquina virtual digamos el vmos, ya que no quiero degradar la version de ui 6.1 de mi samsung
