### ISSUE TITLE
Croatian language?

### ISSUE THREAD

**Issue by idjundje** [AndreyPavlenko/Fermata#384]
Hy
I would like translate application into Croatian language, so I'm interested how can I do that?

**Comment by AndreyPavlenko** [comment]
Hello,

You need to translate these 2 files:
https://github.com/AndreyPavlenko/Fermata/blob/master/fermata/src/main/res/values/strings.xml
https://github.com/AndreyPavlenko/Fermata/blob/master/fermata/src/main/res/values/voice_cmd.xml

Here is a PR example - https://github.com/AndreyPavlenko/Fermata/pull/118

**Comment by geranium743** [comment]
[voice_cmd.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14270998/voice_cmd.xml.txt)
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14270999/strings.xml.txt)

**Comment by geranium743** [comment]
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14271025/strings.xml.txt)

**Comment by geranium743** [comment]
[voice_cmd.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14271027/voice_cmd.xml.txt)

**Comment by AndreyPavlenko** [comment]
Added, please check - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs .

**Comment by geranium743** [comment]
update
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14318630/strings.xml.txt)

**Comment by AndreyPavlenko** [comment]
Please check https://github.com/AndreyPavlenko/Fermata/tree/master/fermata/src/main/res/values-hr

**Comment by idjundje** [comment]
That is not translated into accurate Croatian language, this my files are correct Croatian language that I have translated.
[strings.txt](https://github.com/AndreyPavlenko/Fermata/files/14402582/strings.txt)
[voice_cmd.txt](https://github.com/AndreyPavlenko/Fermata/files/14402583/voice_cmd.txt)

**Comment by AndreyPavlenko** [comment]
Thanks, updataed.
Please check - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs .

**Comment by idjundje** [comment]
I checked, and it was necessary to correct some text in grammar, so now here are completely correct files with the Croatian language, so Fermata can now be updated with Croatian language.
[strings.txt](https://github.com/AndreyPavlenko/Fermata/files/14470205/strings.txt)
[voice_cmd.txt](https://github.com/AndreyPavlenko/Fermata/files/14470206/voice_cmd.txt)

**Comment by AndreyPavlenko** [comment]
Thanks. I'll merge strings, but voice_cmd is not valid. You replaced XML entities, for example &action_find; with &Pronađi;. &action_find; is a reference to the string defined in DOCTYPE resources:
```
<!ENTITY action_find "traži">
```

&Pronađi; is not a valid reference. You need to either change the entity or replace with a plain text:
```
<string name="vcmd_action_find">Pronađi</string>
``` 

I understand, the format is a bit complicated. This file contains regular expressions matching the voice commands. For example:
```
    <string name="vcmd_find_play_open">(?&lt;A&gt;\\b(&action_find;)|(&action_play;)|(&action_open;)\\b)? ?((in )?(?&lt;L&gt;\\b(&location_folders;)|(&location_favorites;)|(&location_playlists;)|(&location_tv;)|(&location_youtube;)|(&location_browser;)\\b))? ?(?&lt;Q&gt;.+)</string>
``` 
matches a set of phrases:
find in youtube ...
play in folders ...
open in browser ...
...

**Comment by idjundje** [comment]
I think I fix it now...

[voice_cmd.txt](https://github.com/AndreyPavlenko/Fermata/files/14472756/voice_cmd.txt)

**Comment by AndreyPavlenko** [comment]
Updated - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs
