### ISSUE TITLE
Issue with Fermata Auto v1.9.8 on Samsung S22 Ultra - Android 14, One UI 6.0

### ISSUE THREAD

**Issue by Dinrongroj** [AndreyPavlenko/Fermata#385]
Hi Developer and all 

I'm experiencing a critical issue with Fermata Auto version 1.9.8 on my Samsung S22 Ultra running Android 14, One UI 6.0. Upon launching the app, I encounter an error, as detailed in the attached file. This issue prevents me from using the app as intended. 

Is there a solution available that does not require downgrading my device to Android 5.1? 

![Screenshot_20240208_223414_Gallery](https://github.com/AndreyPavlenko/Fermata/assets/11937968/e7fc2d6c-cb31-428e-869f-3dcdfa41f375)
Your assistance in resolving this matter would be greatly appreciated.

**Comment by AndreyPavlenko** [comment]
Here is a detailed instruction - https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1934257166
