### ISSUE TITLE
Issue with Fermata Auto v1.9.8 on Samsung S22 Ultra - Android 14, One UI 6.0

### ISSUE THREAD

**Issue by Dinrongroj** [AndreyPavlenko/Fermata#386]
Hi Developer and All,

I'm experiencing a critical issue with Fermata Auto version 1.9.8 on my Samsung S22 Ultra running Android 14, One UI 6.0. Upon launching the app, I encounter an error, as detailed in the attached file. This issue prevents me from using the app as intended. Is there a solution available that does not require downgrading my device to Android 5.1? 
![Screenshot_20240208_223414_Gallery](https://github.com/AndreyPavlenko/Fermata/assets/11937968/ca4f12e6-b726-417e-b1fb-1fb7395dfd32)

Your assistance in resolving this matter would be greatly appreciated.

**Comment by Dinrongroj** [comment]
Pleas help.

**Comment by AndreyPavlenko** [comment]
Please read this instruction - https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1934257166

**Comment by Dinrongroj** [comment]
Thanks but method 1 didn't work for me, so I have only Method 2 with the AAWireless dongle.
