### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by geranium743** [AndreyPavlenko/Fermata#388]
Hy
I would like translate application into Polish language, so I'm interested how can I do that?

**Comment by AndreyPavlenko** [comment]
Hello. Answered the same question a few days ago - https://github.com/AndreyPavlenko/Fermata/issues/384#issuecomment-1927832198

**Comment by geranium743** [comment]
I don't know if I sent the translated files correctly?

**Comment by AndreyPavlenko** [comment]
No, you had to add a new file fermata/src/main/res/values-pl/strings.xml instead of modifying the existing one. If you can fix your PR, please do it. If not, I can do it, it's not a problem.

**Comment by AndreyPavlenko** [comment]
Added, please check - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs .

**Comment by geranium743** [comment]
update + fixing found errors
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14472810/strings.xml.txt)

**Comment by AndreyPavlenko** [comment]
Updated - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs
