### ISSUE TITLE
Web browser 

### ISSUE THREAD

**Issue by Donp2275** [AndreyPavlenko/Fermata#39]
Using the web browser, I don't see the tabs to switch between each open tab.

**Comment by AndreyPavlenko** [comment]
The browser does not support tabs. It's not a web browser app.

**Comment by Donp2275** [comment]
Can I can the browser type? Or can you suggest a different browser?
Also how can I go back to previous page

**Comment by AndreyPavlenko** [comment]
No, I don't know any web browser for AA.
To go back there is a button in the top left corner, or the floating button.
