### ISSUE TITLE
Japanese language support!

### ISSUE THREAD

**Issue by kodenma** [AndreyPavlenko/Fermata#390]
Hy.
This app is the best. I will help with the Japanese translation.
Please merge.
[voice_cmd.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14235415/voice_cmd.xml.txt)
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14235416/strings.xml.txt)

**Comment by AndreyPavlenko** [comment]
Thank you very much! To be added in the next release.

**Comment by AndreyPavlenko** [comment]
Added, please check - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs .

**Comment by kodenma** [comment]
Thank you for merging.
As a result of checking, there were some corrections, so I would appreciate it if you could merge them again.
thank you.
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14299052/strings.xml.txt)

**Comment by AndreyPavlenko** [comment]
Thanks, updated - https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs

**Comment by kodenma** [comment]
Thank you for merging the revised version.  
We have confirmed that there is no problem with the app, so there is no problem in publishing it.  
We will continue to support Fermata!

**Comment by AndreyPavlenko** [comment]
Thanks!
