### ISSUE TITLE
Problem with icon not showing on Android Auto launcher screen in Android 14 one UI6.0 fermata auto 1.98

### ISSUE THREAD

**Issue by sangtong79** [AndreyPavlenko/Fermata#393]
Problem with fermata auto icon not showing on Android Auto launcher screen in Android 14 one UI6.0, fermata auto 1.98
The fermata control icon is visible, but the fermata auto icon is not visible on the Android Auto launcher screen.
I tried reinstalling, clearing the cache, and lowering the Android Auto version, but it doesn't work.
I looked into it in several places, but is there any other way other than downgrading to Android 13?

![KakaoTalk_20240215_190044203_01](https://github.com/AndreyPavlenko/Fermata/assets/160119471/f4d3eeab-dc8d-4de3-a96b-5b3b7a448068)
![KakaoTalk_20240215_190044203](https://github.com/AndreyPavlenko/Fermata/assets/160119471/ce6606da-c89d-446a-9eeb-05879a71e132)

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1934257166
