### ISSUE TITLE
Traditional Chinese Language Support

### ISSUE THREAD

**Issue by g9711566** [AndreyPavlenko/Fermata#395]
It's happy to see that this app is getting better and better. I spent some time in the past 2 days and came up with a Traditional Chinese Support. Would be great if you can help to merge it and I can test if it is workable. Thanks!
[Fermata_zh-tw.zip](https://github.com/AndreyPavlenko/Fermata/files/14311676/Fermata_zh-tw.zip)

**Comment by AndreyPavlenko** [comment]
Thank you very much!
Please check - https://github.com/AndreyPavlenko/Fermata/tree/master/fermata/src/main/res/values-zh-rTW
https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs

**Comment by g9711566** [comment]
I have checked and the functions worked fine! I have made some slight changes in the translation.
Would be great if you can help to merge again. Thank you!
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14321270/strings.xml.txt)

**Comment by AndreyPavlenko** [comment]
Please check - https://github.com/AndreyPavlenko/Fermata/tree/master/fermata/src/main/res/values-zh-rTW
https://app.box.com/s/ns86n7vc3ssaltli0mmibrydnyvbr6bs

**Comment by g9711566** [comment]
Everything's perfect now! Thank you! It's great to contribute to this app.
