### ISSUE TITLE
Great work Working fine with AA5.2

### ISSUE THREAD

**Issue by podimonanil** [AndreyPavlenko/Fermata#4]
video player working fine with Android Auto 5.2, steering controls not working, I've downloaded Fermata auto control 1.5.5, it is not showing in apps list. Its is showing in AA Phenotype patcher and i tried patching  Fermata auto control with it, Still Steering controls not working. Help Me.

**Comment by AndreyPavlenko** [comment]
Do you have the same version 1.5.5 of both Fermata and control? The control app does not require any patching. Please check the list of enabled applications in the AA settings, perhaps the control app is not enabled.

**Comment by podimonanil** [comment]
**THANK YOU SIR**, I've uninstalled and Reinstalled both fermata auto 1.5.5 and fermata control1.5.5. ans ptached Fermata Auto alone with AA Phenotype Patcher, Now My Steering controls are working.
I've unrooted my phone and tried.
Now video playback with fermata auto is still working great BUT steering controls not working after unroot.
can you integrate both apps together, 
THANK YOU for your great WORK

**Comment by AndreyPavlenko** [comment]
Unfortunately I can't. The control app is a workaround to enable the steering controls in AA.

**Comment by podimonanil** [comment]
Another Good news.
With fermata auto, my steering controls were a bit fuzzy, it works at times and at times not. And after unrooting steering controls were gone 
For me
Everything works great with
THIS TRICK.
I've converted 'Fermata Auto' and 'Fermata Control' apps as
System Apps.
Now steering controls are working even after UNROOTING my phone.
Thanks a LOT.
