### ISSUE TITLE
Korean language support!

### ISSUE THREAD

**Issue by JeenwooKim** [AndreyPavlenko/Fermata#400]
Hello. I lately relized this Fermata Auto while using the AAwireless. I also want to support you for the Korean translations. 

[Korean_Translations.zip](https://github.com/AndreyPavlenko/Fermata/files/14344388/Korean_Translations.zip)

Once the Korean language updated, I will check and modify my translations, if needed.

Thank you for your hard work and this wonderful application!!

**Comment by AndreyPavlenko** [comment]
Thank you very much! To be added in the next version.

**Comment by AndreyPavlenko** [comment]
Please check https://github.com/AndreyPavlenko/Fermata/tree/1.9.9/fermata/src/main/res/values-ko

**Comment by JeenwooKim** [comment]
[strings.xml.txt](https://github.com/AndreyPavlenko/Fermata/files/14399485/strings.xml.txt)

Thank you for the update! I installed the newest version and fixed few missing translations and grammatical problems. They are very minor so can be updated in the next version, if needed.

If the app updates and needs more Korean translations, I will keep support! (Shall I update the translation in the new issue? or can I just update in this closed issue?)

Thank you!

**Comment by AndreyPavlenko** [comment]
The preferred way is to use github pool requests, but if it's inconvenient, you can just send the updates in this issue, I'll merge manually.

**Comment by JeenwooKim** [comment]
Ok. I actually learned how to do the pool request. I will try update through the pool request next time.
Thank you for the wonderful app and efforts!
