### ISSUE TITLE
Fermata auto 

### ISSUE THREAD

**Issue by Napoli1977** [AndreyPavlenko/Fermata#409]
Salve, ho installato l'applicazione fermata auto l'ultima versione dal vostro sito, su smartphone samsung con android 14, collegando lo smartphone ad android auto l'applicazione fermata auto asce che mi fa ascoltare solo in audio e non in video. Come potrei fare?grazie.

**Comment by Zetakidida** [comment]
Not yet a solution for A14.

**Comment by AndreyPavlenko** [comment]
Duplicate of https://github.com/AndreyPavlenko/Fermata/issues/327
