### ISSUE TITLE
Fermata auto not showing video, only sound

### ISSUE THREAD

**Issue by marshall509324** [AndreyPavlenko/Fermata#413]
in the beginning it was ok for coupleo of days and then suddenly video stop but sound continues. what i should do?

**Comment by AndreyPavlenko** [comment]
Android 14?

**Comment by marshall509324** [comment]
yes

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/327#issuecomment-1934257166

**Comment by marshall509324** [comment]
yes how I can fix that?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by AndreyPavlenko** [comment]
The easiest way, use this device - https://www.aawireless.io/
