### ISSUE TITLE
Auto channels switch

### ISSUE THREAD

**Issue by senior-pol** [AndreyPavlenko/Fermata#42]
The channels on the m3u list switch every 5 seconds.  I tried to change the shuffle option but it did nothing.  Android 10, AA 6.9, Galaxy S9.  Installation from Github.  How to solve the problem?

**Comment by AndreyPavlenko** [comment]
Could you please send me the playlist?

**Comment by senior-pol** [comment]
https://gratisiptv.com/m3u/pl-gratisiptvm3u-2021-09-09-8.m3u


Best regards,
Konrad

pon., 13 wrz 2021, 20:39 użytkownik Andrey ***@***.***>
napisał:

**Comment by AndreyPavlenko** [comment]
Have you tried this playlist with other players? I'm getting the same behavior on PC players - all channels are playing ~10 seconds.

**Comment by senior-pol** [comment]
I tried a few different playlists but the effect was the same.  I also
installed the google play version on the phone and the effect is the same.

pon., 13 wrz 2021, 20:44 użytkownik Andrey ***@***.***>
napisał:

**Comment by AndreyPavlenko** [comment]
Have you tried a different player?
I've tried it on a PC version of VLC player - effect is the same. Thus, the problem is in the playlist.

**Comment by senior-pol** [comment]
Ok i will be looking for a different playlist.

pon., 13 wrz 2021, 20:59 użytkownik Andrey ***@***.***>
napisał:
