### ISSUE TITLE
Black screen while playing videos in mirror mode

### ISSUE THREAD

**Issue by grantgrm** [AndreyPavlenko/Fermata#428]
Hello.

I am having an issue with the mirror mode in version 1.9.9 on Android 13 Oneplus phone. Everything works as expected (by the way, great work), but in mirror mode wether normal or full screen, when I try to play a video (Netflix, Disney, HBO, etc) the image goes black. Everything else works OK, I can hear audio and even see subtitles, but the video image is all black. ¿Any ideas or suggestion to find a solution?

Thank you very much.

**Comment by AndreyPavlenko** [comment]
Probably these apps have some protection against video recording.

**Comment by grantgrm** [comment]
Yes. It seems you are right. Its because of DRM and copyrights. I guess a workaround is not posible. ¿Is it?

**Comment by Alejandro2454** [comment]
@grantgrm
Estimado, con FERMATA MIRROR usted si puede ver videos Netflix, solo debe
instalar y usar en AA la app RAVE
Saludos
Ale
