### ISSUE TITLE
Fermata auto not detected

### ISSUE THREAD

**Issue by DjCristianquezQuez** [AndreyPavlenko/Fermata#43]
After installing version 1.8.0 my AA does not detect the application. xiaomi redmi note 10 miui 12.5.1 the previous version detects it without problems

**Comment by AndreyPavlenko** [comment]
How have you installed the app?

**Comment by DjCristianquezQuez** [comment]
good again sorry I wanted to thank you for the great work you do with this application for me it is an essential app in my car system so I would like to always have the latest version if you need some kind of test I will be happy to help you

I instal de app from this repository

**Comment by AndreyPavlenko** [comment]
Did you follow this installation instruction https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/ ?

**Comment by DjCristianquezQuez** [comment]
Thank IS operative
