### ISSUE TITLE
Fermata shows but no video works or youtube does not show up

### ISSUE THREAD

**Issue by sk9972252270** [AndreyPavlenko/Fermata#435]
I followed all the instructions, the option shows on AA and it shows on car screen as well. However, the screen shows only folders and Playlist as the tabs... every tab and add-ons are enabled on mobile app. But youtube does not show, web browser does not show. So I added a video on folder and tried to play,  only audio works and video does not work.
Car Model: XUV700 AX7L (INDIA)
Android Version: 14
Android Auto: 11.2.640434-release
Fermata: 1.9.9

![20240310_122103](https://github.com/AndreyPavlenko/Fermata/assets/79166380/e4d01ebd-6e02-4bcb-bf95-628a007ffb7a)
![20240310_120700](https://github.com/AndreyPavlenko/Fermata/assets/79166380/0b01daa4-1332-4fa1-8b7a-da07a7b6b3c6)

**Comment by sk9972252270** [comment]
Software info:
![Screenshot_20240310_131449_Settings](https://github.com/AndreyPavlenko/Fermata/assets/79166380/9698a69d-d8ab-4531-bc09-4c6873889503)
![Screenshot_20240310_131446_Settings](https://github.com/AndreyPavlenko/Fermata/assets/79166380/aaf165a5-5984-4d19-aabe-2a12b6a007aa)
![Screenshot_20240310_131525_Android Auto](https://github.com/AndreyPavlenko/Fermata/assets/79166380/2fbf46e0-6fbd-48df-8552-a5ae1af5c3c0)

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by sk9972252270** [comment]
My phone is not rooted .. is it must I should root the device to use this function?

**Comment by AndreyPavlenko** [comment]
Options for non-rooted devices are also described there.

**Comment by Roscopct** [comment]
Buongiorno sig. Pavlenko e grazie per il suo lavoro.. ho seguito le istruzioni di cui al commento 432.. il mio telefono non ha root... ora in android auto sul cellulare vedo fermata auto e questa funziona.. collego il cellulare all'auto.. autoradio skoda non android e sebbene veda l'applicazione fermata auto questa si apre ma non visualizza il classico menu e non funziona... cosa sbaglio?? Grz per l'aiuto..

**Comment by AndreyPavlenko** [comment]
For Android 14 just use [AAWireless](https://www.aawireless.io/). This is the easiest solution at the moment.

**Comment by AndreyPavlenko** [comment]
With DHU you can enable the screen mirroring.

**Comment by Roscopct** [comment]
Ma solo con autoradio android o qualsiasi???

Il Mar 12 Mar 2024, 18:10 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
You need to connect your phone to [DHU](https://developer.android.com/training/cars/testing/dhu) and start the FS Fermata Mirror. Aster that, it should work in the car.

**Comment by Roscopct** [comment]
Ci provo grz

Il Mar 12 Mar 2024, 18:30 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by Roscopct** [comment]
Ho provato ma non compaiono più.. vedo le app su AA del cellulare poi avvio
AA sull'autoradio dell'auto e non le vedo più tranne fermata media center..
mi perdo qualcosa..

Il Mar 12 Mar 2024, 18:30 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
Right, this is expected. You can see the icons, when connected to DHU, but not car. All you need - connect to DHU and start FS Mirror. Next time, when you connect to the car, it will be started automatically.

**Comment by Roscopct** [comment]
Sig. Pavlenko buongiorno..
Fermata S mirror funziona.. e a questo punto penso che troverete la
soluzione anche per fermata auto.. l'unica cosa nell'angolo in basso a
destra dello schermo compare il rettangolino nero con delle indicazioni
software e non scompare coprendo parte del video dell'auto.. si può
nascondere?? E i due tasti funzione in altro si possono spostare?? Grz mille


Il Mer 13 Mar 2024, 20:46 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
Unfortunately, you can't move the top right buttons.

**Comment by Roscopct** [comment]
E il riquadro in basso a destra con informazioni relative alla versione
software ecc.. scritte che sbrilluccicano.. e lampeggiano leggermente..

Il Gio 14 Mar 2024, 14:46 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
I have no idea what is that. Do you have a screenshot?

**Comment by Roscopct** [comment]
Ecco la foto

Il Gio 14 Mar 2024, 15:05 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
I don't see any picture. Have you attached it?

**Comment by Roscopct** [comment]
Eccola

Il Gio 14 Mar 2024, 16:28 Andrey Pavlenko ***@***.***> ha
scritto:

**Comment by AndreyPavlenko** [comment]
You send it by email and it's not attached. Go here https://github.com/AndreyPavlenko/Fermata/issues/435 and attach to the message.

**Comment by AndreyPavlenko** [comment]
This is definitely not Fermata. Seems you have enables dome dev feature. Do you see this on your phone screen or the car screen only? Go to the AA settings and disable all dev options.

**Comment by Roscopct** [comment]
Allego ulteriori foto
![IMG-20240314-WA0008](https://github.com/AndreyPavlenko/Fermata/assets/163155521/07709525-2744-491a-957d-951e082f1aef)
Menu su radio

![IMG-20240314-WA0009](https://github.com/AndreyPavlenko/Fermata/assets/163155521/668cae8e-e83a-406b-b991-24a0ba38ae2d)
Schermo radio

![IMG-20240314-WA0010](https://github.com/AndreyPavlenko/Fermata/assets/163155521/ba9a2748-1da2-4507-b33e-6f14428af416)
Schermo cellulare

![IMG-20240314-WA0011](https://github.com/AndreyPavlenko/Fermata/assets/163155521/26f6b26a-449b-4dcf-8b7f-99017e5309dd)
Schermo entrambi..

Sulla radio rimane visibile il rettangolo in basso a dx con informazione step........ ecc

**Comment by Roscopct** [comment]
Sig. Pavlenko mi conferma che quel rettangolino nero con scritte verdi in basso a dx non si può nascondere??

**Comment by AndreyPavlenko** [comment]
This is not from Fermata. I never seen it before.

**Comment by sk9972252270** [comment]
It worked... but it automatically stops within 3 minutes. First the screen gets frozen and then it stops working..
Second problem, if you touch the app icon or other default menu in console... the fermata stops automatically

**Comment by Roscopct** [comment]
> Questo non è di Fermata. Non l'ho mai visto prima.

Ho scoperto quale era il problema del rettangolino.. togliendo la spunta sulle opzioni sviluppatore "attiva overlay di debug" sparisce..
