### ISSUE TITLE
Problem on android automotive

### ISSUE THREAD

**Issue by Giustino76** [AndreyPavlenko/Fermata#436]
I installed fermata 1.9.9 on my Renault Austral e-tech with android automotive. With some channels I can listen only the audio and no image shown. The same channels on my smartphone with android 14 are ok.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by Giustino76** [comment]
I don't understood why you close my issue by linking anathoer argoment.

**Comment by AndreyPavlenko** [comment]
Because your issue is related to Android 14. There is a separate discussion thread.

**Comment by Giustino76** [comment]
My issue Is not related to android 14 but android automotive (and not android auto). They are 2 different things.

**Comment by AndreyPavlenko** [comment]
Ah, sory. I thought this is another A14 issue, that are opened almost every day.
Have you enabled the VLC engine in the app settings? Try changing the engine for the channels that do not work - long press and select a different engine.

**Comment by Giustino76** [comment]
Yes I tried.l but with some resulta. But the stranger thing Is the some Channel on smartphone I can listen audio and show picture but on android automotive I can listen only the audio.

**Comment by Giustino76** [comment]
I hope you can work towards improving compatibility with android automotive too.

**Comment by AndreyPavlenko** [comment]
Have you tried the VLC player? Does it work for the same channel?

**Comment by Giustino76** [comment]
It was the first player I tried because it is the default one.

**Comment by AndreyPavlenko** [comment]
Does it work for the same channel?

**Comment by Giustino76** [comment]
Yes It is

**Comment by AndreyPavlenko** [comment]
Then, probably, the video codec is not supported by the device.
