### ISSUE TITLE
1.9.9 working on A13 - Updated to A14 - Shows Icon in AA but doesn't Start - Black Screen

### ISSUE THREAD

**Issue by grantgrm** [AndreyPavlenko/Fermata#443]
I have a Oneplus 8T with stock firmware, non rooted. I had Fermata 1.9.9 working fine in A13. Since there were a lot of people who had it working in A14 I updated and now Fermata shows up in AA but whenever I launch tha main app or Fermata Mirror nothing happens. I get only a black screen, with the side app still showing, i.e. Spotify. ¿Any ideas on how to proceed? I tried reinstalling with King but nothing changed. Thank you.

**Comment by Pssaaa** [comment]
Having similar issue om crdroid 10 (android 14) for oneplus7pro. However screen mirror works

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by Pssaaa** [comment]
Fermata auto does showup in android auto..it just shows blck screen while opening it..please note fsmirror works perfectly

**Comment by AndreyPavlenko** [comment]
Is there a stack trace below this error?

**Comment by Pssaaa** [comment]
[2024-04-21-18-31-12.txt](https://github.com/AndreyPavlenko/Fermata/files/15052013/2024-04-21-18-31-12.txt)
 Attaching log filr

**Comment by AndreyPavlenko** [comment]
This error goes from the google services and, as you can see in the log, not only for Fermata, there are also other apps with the same error.
