### ISSUE TITLE
Fermata Auto 1.9.9 and 

### ISSUE THREAD

**Issue by Adeas77** [AndreyPavlenko/Fermata#444]
Hi! I have a  Samsung S23plus with Android Auto 11.1.640234-release. 
Android Auto can't see Fermata Auto 1.9.9 even if it seems supported - how can I resolve?

**Comment by Adeas77** [comment]
Sorry - I have missed a couple of relevant info: One UI version 6.0 and Android Version 14. Thanks Andrea

**Comment by Adeas77** [comment]
Dear Andrey, sorry but I'm not e developer and I'm not able to follow the instruction. I have installed DHU on my pc and I have connected my phone with USB BUT I can't understand how to run the command "./desktop-head-unit --usb". Thanks Andrea

**Comment by AndreyPavlenko** [comment]
If you have Windows, you need to start desktop-head-unit.exe: https://developer.android.com/training/cars/testing/dhu

**Comment by Adeas77** [comment]
It's start working but it disappears in few seconds

[image: image.png]

Il giorno mar 26 mar 2024 alle ore 14:19 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
Have you enabled the head unit server as described here - https://developer.android.com/training/cars/testing/dhu#connection-adb ?

**Comment by Adeas77** [comment]
Yes because I saw the tutorial

https://www.youtube.com/watch?v=8Tzfd2G1ub8

Now I can see fermata auto on my PC with DHU BUT I can't see fermata auto
on my car

Many thanks for your support

Andrea

Il giorno mar 26 mar 2024 alle ore 15:59 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
You will not see it on the car. This strick allows to start the Fermata FS Mirror on pc, after that it will be started automatically in the car.

**Comment by Adeas77** [comment]
ok but it isn't started automatically in the car -

I'll try again the whole procedure



Il giorno mar 26 mar 2024 alle ore 16:49 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by Adeas77** [comment]
I don't have Fermata FS Mirror, it's not on AAAD

where I can find?

thanks

Andrea

Il giorno mar 26 mar 2024 alle ore 16:54 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
It's all in one apk. You will see it on DHU.

**Comment by Adeas77** [comment]
Dear Andrey

I'm very close to the solution.....now I can see on m DHU

[image: image.png]

and DHU asks for granting permissions

[image: image.png]

but on my phone I can't see Fermata FS mirroring

[image: image.png]


maybe some errors here?

[image: image.png]



Il giorno mar 26 mar 2024 alle ore 16:54 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by Adeas77** [comment]
Maybe the problem is that that Fermata Auto is disabled

[image: image.png]

And I can't enabled because I need to allow limitated authorization in
Other option for specific applications in Settings > Application

[image: image.png]

But I don't know how...

Many thanks

Andrea

Il giorno mar 26 mar 2024 alle ore 17:47 Andrea De Asmundis <
***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
I son't see the screenshots. The images sent by email are not attached here.

**Comment by Adeas77** [comment]
Dear Andrey

yesterday evening I've worked on my phone and finally I can see in my auto
Fermata Control and Fermata Media Services - I can't see yet Fermata Auto
(but in DHU I can see it)

However using in my auto Fermata Media Services I can hear the audio of my
mp4 BUT I can't see the video as video are not reproduced - do you know how
I can unblock the video reproducing?

Many thanks and have a nice day

Andrea

Il giorno mar 26 mar 2024 alle ore 19:11 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by Adeas77** [comment]
forgotten the photo of my car

thanks

Il giorno mer 27 mar 2024 alle ore 09:41 Andrea De Asmundis <
***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
Fermata Auto is not available when you connect to the car head unit, but it's available when connected to DHU. So, the trick is to connect to DHU, start the FS mirror, then connect to the car and the mirror will be started automatically.

**Comment by Adeas77** [comment]
thank Andrey

so the steps are

1) connect my phone to my pc by DHU and start FS mirror
2) disconnect my phone from the pc and conntect my phone to my car by usb
cable?

Every time I want Fermata Auto available on my car screen?

Have you any app available in the car head unit for video?

Thanks

Andrea

Il giorno mer 27 mar 2024 alle ore 14:38 Andrey Pavlenko <
***@***.***> ha scritto:

**Comment by AndreyPavlenko** [comment]
Not every time, but you should not start any other AA apps, otherwise, you will need to repeat the trick with DHU. If you do not start other AA apps, Fermata FS will be started automatically on each connection.
