### ISSUE TITLE
Issue with the music player on AA

### ISSUE THREAD

**Issue by DanKill99** [AndreyPavlenko/Fermata#45]
I have a problem with the music player on android auto. When I put in a 200 mp3 playlist everything is fine but when I put 1400 mp3 (15 gb), either the player freezes after 5 seconds of playback or android auto crashes. Sometimes my smartphone freezes completely.

When I put the same playlist (1400 mp3) on another player (like Poweramp) I don't have this bug.

Fermata Media Player 1.8.0 (116)
Android Auto 6.8.613354
Android 10 (on phone Oneplus 6T)

Thank you for the support

**Comment by AndreyPavlenko** [comment]
Does it freeze in AA only? Does it freeze if you run the app on phone?

**Comment by DanKill99** [comment]
It was also freezing on the phone but I have the app updated to version 1.8.2 and it no longer freezes on the phone. I have some tests with version 1.8.2 and the app freezes only on AA with a playlist of more than 1000 mp3 (AA disconnects from the car). I tested with a 750 mp3 playlist and it works fine.
