### ISSUE TITLE
Video not scaleing, and flicking static around border when playing video stream on Android TV

### ISSUE THREAD

**Issue by nabeelr** [AndreyPavlenko/Fermata#459]
When playing a stream, the video is displayed 1:1 on the screen in the top left corner of the TV and the rest of the display is filled with either static, or a green box. The UI elements scale properly, however the video refuses to scale. This is irrespective of the video scaling setting inside of Fermata.

Here's a video demonstrating the issue: https://youtu.be/MSnUEImEHxk

Fermata Version: v1.9.9 (239)
Android Version: Android TV 10
Android Kernel version: 4.9.180
Device: Inspur IPBS9510 for start.ca

**Comment by AndreyPavlenko** [comment]
Seems like a video codec issue. Try one of the following:
1. Long press on the video and change the media engine.
2. Long press and disable the hardware acceleration.

**Comment by nabeelr** [comment]
I did try disabling hardware acceleration, but the option was not selectable. The menu would stop just above or below the item when navigating with the remote.

I had forgotten  where the option was to change the media engine, so I wasn't able to try that (I thought it was in the same menu as to change aspect ratios when playing), but now that you've reminded me, I'll give it a shot and report back.

**Comment by AndreyPavlenko** [comment]
Try updating the app, the menu should be fixed now.

**Comment by nabeelr** [comment]
The hardware option has disappeared entirely now, but I suspect that's because hardware decode isn't available?

As for the video playback, it's working normally so long as I don't use VLC for playback, so it must be an issue with VLC decode.

I guess I can close the ticket now?

**Comment by AndreyPavlenko** [comment]
Thanks for reporting the issue.
