### ISSUE TITLE
Resolution on youtube screen

### ISSUE THREAD

**Issue by juloryx** [AndreyPavlenko/Fermata#46]
Hi there Andrey.

Can't seems to adjust the resolution of the YouTube page on F.A. incredibly large on banners ans text.
Next to impossible to search videos this way.
Using 1.8 version 

Web browser seems okay (google image)
Video playing resolution works fine too.

![20210917_230637](https://user-images.githubusercontent.com/90971499/133890995-d91f4fe6-de04-44ac-a927-a9bccc4e04bb.jpg)
![20210917_230644](https://user-images.githubusercontent.com/90971499/133890997-2b9988ee-933d-446e-9d8d-71240c2f319b.jpg)
![20210917_230712](https://user-images.githubusercontent.com/90971499/133890999-ebe4294d-3fa7-46d2-967f-cd87ef6cf580.jpg)
![20210917_230739](https://user-images.githubusercontent.com/90971499/133891002-d081bf93-0c85-4a2e-9229-911e13dace5f.jpg)

**Comment by AndreyPavlenko** [comment]
Try this - https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/post-84522591

**Comment by Markorea** [comment]
> Hi there Andrey.
> 
> Can't seems to adjust the resolution of the YouTube page on F.A. incredibly large on banners ans text. Next to impossible to search videos this way. Using 1.8 version
> 
> Web browser seems okay (google image) Video playing resolution works fine too.
> 
> ![20210917_230637](https://user-images.githubusercontent.com/90971499/133890995-d91f4fe6-de04-44ac-a927-a9bccc4e04bb.jpg) ![20210917_230644](https://user-images.githubusercontent.com/90971499/133890997-2b9988ee-933d-446e-9d8d-71240c2f319b.jpg) ![20210917_230712](https://user-images.githubusercontent.com/90971499/133890999-ebe4294d-3fa7-46d2-967f-cd87ef6cf580.jpg) ![20210917_230739](https://user-images.githubusercontent.com/90971499/133891002-d081bf93-0c85-4a2e-9229-911e13dace5f.jpg)

Hi, have you settled that resolution issues? Now im getting in trouble with the same issue. headache...
If you have any solution, please let us know. thanks
