### ISSUE TITLE
New update lock your app.

### ISSUE THREAD

**Issue by NaschuoFonta** [AndreyPavlenko/Fermata#460]
Hello Andrey Pavlenko, I am writing to you because the last update of the Samsung Galaxy S23 Ultra blocked all the additional functions of your application, only leaving FERMATA MEDIA SERVICE working.  It's a shame since its application is better than Android Auto itself.  I wanted to inform you, I don't know if the same thing happened to others.

**Comment by AndreyPavlenko** [comment]
Thanks, this is a known issue and it's reported by users almost every day.
See here for the possible solutions - https://github.com/AndreyPavlenko/Fermata/discussions/432
