### ISSUE TITLE
Andrey dacci qualche speranza..

### ISSUE THREAD

**Issue by Roscopct** [AndreyPavlenko/Fermata#461]
Andrey buonasera..
Digitando su internet "fermata auto Android 14".. ne escono di tutti i colori.. ognuno dice la propria.. tante promesse e sopratutto bugie... purtroppo abbiamo ben capito qual'è il problema e speriamo davvero che tu riesca a trovare soluzione.. a questo punto riesci in qualche modo ad alimentare le nostre speranze.. hai qualche novità?? Buon lavoro Andrey.. e un grazie per ora...

**Comment by AndreyPavlenko** [comment]
Unfortunately, no news. I'll update this https://github.com/AndreyPavlenko/Fermata/discussions/432 thread in case of any news.
