### ISSUE TITLE
Fermata Auto not showing up in Android Auto

### ISSUE THREAD

**Issue by hoongss** [AndreyPavlenko/Fermata#463]
Hello Andrey,

Issue: Fermata Auto no longer showing in Android Auto. Please Advise.

Phone:  Samsung Galaxy S22 Ultra
One UI Version: 6.0
Android Version: 14
Android Auto Version: 11.5.641024-release
Fermata Auto Version: 1.9.9 (237)

Thank you for the app. One of the best app ever.

**Comment by AndreyPavlenko** [comment]
Please, read here - https://github.com/AndreyPavlenko/Fermata/discussions/432 .
