### ISSUE TITLE
1.9.9 FS Mirror or Video not showing

### ISSUE THREAD

**Issue by jackie-chan** [AndreyPavlenko/Fermata#467]
Hi,
I've read a bunch of the issues related to not seeing any video but only audio on AA and I'm experiencing the same. I've had success using the DHU to get FS Mirror to start on connection but if you open a main app like Waze, it goes away and there's no way to start it again without going through DHU.
I might be missing something from older issues but is there either a way to start FS Mirror again besides going to DHU each time or is there a reason why doing through the Fermata app in AA, none of the video is showing up?

Using a Pixel 6 on Android 14 (non-rooted)
Thanks!

**Comment by jackie-chan** [comment]
@AndreyPavlenko thanks! That's what I figured for the FS Mirror. But if not using FS Mirror, the regular Fermata app won't show video on the screen, just audio. Is that the limitation of a non-rooted phone?
Sorry for the silly question

**Comment by jackie-chan** [comment]
Thanks! So everyone showing screens of Fermata on their screens is bc they're either on Android 13, or was on 13 with it working and moved to 14?

**Comment by AndreyPavlenko** [comment]
or have a rooted device or use AA Wireless - https://github.com/AndreyPavlenko/Fermata/discussions/432
