### ISSUE TITLE
Webpages becoming unknown while using Fermata 

### ISSUE THREAD

**Issue by Mindless-dust** [AndreyPavlenko/Fermata#468]
Hi mate Thanks for the work you do

I have been using webpages on fermata for a while with A13 with wireless adapter for about a year. Some of the webpages are starting to close down and are unable to access them, after being using them for a while. 
Web Page Not available.
The web page at intent://ak.asferaligatron;scheme=4/6765106?var=6301227&intnt_r=true&bs=bf665552-d46f-4f1b-8007dc8f320e389f#intent;scheme=https;package=com.android.chrome;end   could not be loaded because 

net ::ERR_UNKNOWN_URL_SCHEME

why are the pages not loading anymore when they were working yesterday , ive tried to uninstall fermata from source, even factory reset my samsung s20fe but the problem keeps existing. is there a way i can access these webpages again, or are they forever blocked

**Comment by AndreyPavlenko** [comment]
The urls like `intent://...` mean, that the web page redirects you to some android app. Try switching to the desktop mode.

**Comment by Mindless-dust** [comment]
I dont know how to do that mate on fermata i just copy and paste the page from desktop onto the tool bar on fermata can you tell me how to switch to desktop mode ?

**Comment by AndreyPavlenko** [comment]
Menu > Desktop version
