### ISSUE TITLE
Settings for IPTV

### ISSUE THREAD

**Issue by Ptfd139** [AndreyPavlenko/Fermata#47]
I have a IPTV account and a address for them. How do I get this to work in the TV connection?

**Comment by AndreyPavlenko** [comment]
Go to the TV tab and press Add button in the bottom right corner.

**Comment by Ptfd139** [comment]
I can add the IPTV address but nothing comes up when I then try to open,
get blank screen. Is this similar to a smarter program? Apologies day one
on finding your app

**Comment by AndreyPavlenko** [comment]
Is it M3U address? Only M3U playlists are supported.

**Comment by Ptfd139** [comment]
Thank you I had to get that from provider!!! Great app.. donation coming!!!!
