### ISSUE TITLE
v1.9.9 has completely broken Fermata for me

### ISSUE THREAD

**Issue by CodexHere** [AndreyPavlenko/Fermata#487]
I was running 1.9.4 for a while, refusing to update. Finally I decided to update like I have in the past, and ever since the app no longer works on Android Auto.

I've tried to revert to 1.9.4 installing in the latest KingInstaller, but now that won't even work.

Literally the only change to my phone is the updated Fermata, and it's completely stopped working. I've been running android 14 for over a year now without issue, and AA hasn't updated in a few weeks for me, so it shouldn't be either of those. I have only been using Fermata Auto for ~4 months, so AFAIK it is still fully compatible with my setup.

I've tried reading the changelogs to understand what to expect/do, but they're poorly written and there is no valuable documentation to be found. 

Could you please provide instructions to get this installed and working to date?

----

AA Version: 11.7.641454-release (no updates available)
Device: One Plus 8T, running OOS14
Android Version: 14

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432
