### ISSUE TITLE
Steering wheel controls don't work in 1.9.9 without Fermata Controls App

### ISSUE THREAD

**Issue by as8o** [AndreyPavlenko/Fermata#489]
Following description of release 1.9.9 I've uninstalled Fermata Controls 1.9.8 and installed an update 1.9.9 using King Installer. 

When watching Youtube using Android Auto in the car, FF RW Buttons didn't work. No response when pressing the key.

Installed again 1.9.8 versions of Controls app and it works with 1.9.9 version of Fermata app.

I run Fermata on Android 14 Samsung S21 connected to the car via AA wireless device.

**Comment by AndreyPavlenko** [comment]
Start the Fermata Media Service app.

**Comment by as8o** [comment]
Thank you, it does work after starting Fermata Media Service.

**Comment by as8o** [comment]
Thank you, it does work after starting Fermata Media Service.

**Comment by r4z5** [comment]
All the programmes dont work
