### ISSUE TITLE
Without Control now I miss the YouTube option 

### ISSUE THREAD

**Issue by magnolima** [AndreyPavlenko/Fermata#495]
With 1.9.9 the Control was removed, opening the Fermata on the phone I have the option to YouTube, but now it's missing for the android auto. Any tip?

**Comment by AndreyPavlenko** [comment]
You need to open Fermata Auto in AA. If you don't have it, then it's not properly installed.

**Comment by Tipo-graf** [comment]
Добрый день. Каким образом единственно правильно установить фермата авто, чтобы галочка с фермата авто отображалась в настройках андроид авто? Все ПО естественно обновлено до последних релизов. Спасибо.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by magnolima** [comment]
When you said "You need to open Fermata Auto in AA. If you don't have it, then it's not properly installed.", what exactly you meant? I've opened it in Android Auto on my car unit, it only shows the favorite and media folder, not the YT icon. I will try the other options for it.

**Comment by AndreyPavlenko** [comment]
Because it's not Fermata Auto, but Fermata Media Service.

**Comment by magnolima** [comment]
> Because it's not Fermata Auto, but Fermata Media Service.

Ohhhh now I see! Well, I thought that installing Fermata would install Fermata Auto.
