### ISSUE TITLE
Poco F4 Android 14 HyperOS

### ISSUE THREAD

**Issue by AsVitaly** [AndreyPavlenko/Fermata#496]
Hello.  Tell me how can I connect Poco F4 Android 14 global firmware Xiaomi HyperOS root to Fermata auto?  When installing according to the instructions from the 4PDA forum, the latest Fermata 1.9.9 in AA only the Fermata Media Service icon is visible.  Although when you click on the AA number it says Fermata Auto and Fermata Media Service.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by AsVitaly** [comment]
> #432

Thanks
