### ISSUE TITLE
Fermata Auto in AA does not work on Samsung s23+.

### ISSUE THREAD

**Issue by Romchik-ka** [AndreyPavlenko/Fermata#497]
Dear developer!   Please tell me when your Fermata Auto application will work on Android 14 with Android Auto 11.9.641824.   In the "Versions" list in Android Auto there is Fermata, but when you launch it in the car there is no icon.

**Comment by Alberto-Morgado** [comment]
it's not working on the S23 ultra as well...

Fermata Auto: 1.9.9 (237)
Fermata Control: 1.9.8
Android Auto: 11.9.641834-release (119641834)

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432
