### ISSUE TITLE
Fermata Auto not working on S23 Ultra

### ISSUE THREAD

**Issue by Alberto-Morgado** [AndreyPavlenko/Fermata#498]
hey. it's not working on the S23 ultra.
it's up to date. v1.9.9, but it won't appear on the android auto.
the car is a Peugeot 3008 (2020).
my daughter miss watching YouTube on our way to school. hehehehehe thank you!

**Comment by Alberto-Morgado** [comment]
Fermata Auto: 1.9.9 (237)
Fermata Control: 1.9.8
Android Auto: 11.9.641834-release (119641834)

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432
