### ISSUE TITLE
Current Release 1.9.9 - armeabi-v7a Version?

### ISSUE THREAD

**Issue by richaardvark** [AndreyPavlenko/Fermata#500]
Hello,

I love using Fermata on my Android phone with Android Auto in my car but I also have it installed on my Google TV smart TV and use it every single day. I'm trying to update my television's version to the latest 1.9.9 but my television is an arm V7 and not 64-bit but I don't see the apk file for armeabi-v7a included with the release files. Is there any way to have this created?

**Comment by AndreyPavlenko** [comment]
The app is available on Google Play for Android TV.

**Comment by richaardvark** [comment]
> The app is available on Google Play for Android TV.

Thank you.  The Play Store version doesn't seem to want to import my settings/files from the standard Android version.  I went ahead and built an arm-7 version using the command line and it worked but instead of updating the exiting installation it installed a second copy of Fermata with a different apk/app name.  I'll try to read more about gradle or whatever it's called...

**Comment by AndreyPavlenko** [comment]
You will not be able to build and install over the prev installation with the same package name, because it will have a different signature. Please, find the arm-7 version here - https://app.box.com/s/uw9m8s0c2fpetsarv5xan4uwlef4tfbj

**Comment by richaardvark** [comment]
> You will not be able to build and install over the prev installation with the same package name, because it will have a different signature. Please, find the arm-7 version here - https://app.box.com/s/uw9m8s0c2fpetsarv5xan4uwlef4tfbj

You are so so so kind to have done this for me - thank you very much! :)  I will send you a coffee on PayPal through the app.  Appreciate your help very much!

**Comment by richaardvark** [comment]
I should have tested everything before closing the issue, sorry 🙈
Unfortunately the apk file you provided at the link above installs just like the one I build myself using the command line and gradle.  It installs a duplicate version of Fermata with the apk ID name of 'me.app.fermata.auto.dear.google.why' instead of the usual 'me.app.fermata.auto'   :-/

**Comment by AndreyPavlenko** [comment]
The name `me.app.fermata.auto.dear.google.why` is used for a long time. Is you old version `me.app.fermata.auto`? Where have you install it from? I can build apk with this name either, if your need, but I'd recommend to use the playstore version. What's the issue with your settings import?

**Comment by richaardvark** [comment]
I had version 1.9.8 installed from here on GitHub but it looks like I accidentally deleted it.  I now apparently have two 1.9.9 versions installed, one with `dear.google.why` and one without. I either got it from here or it could be the one I built myself from the command line. 

In either version however when I select "import preferences from file" under the 'Other' setting menu section when I browse to my folder where I have multiple "Fermata_prefs" .zip files located but Fermata isn't recognizing them at all. I have all app file permissions enabled.

**Comment by AndreyPavlenko** [comment]
This is probably due to Android TV. There is no standard android file picker. The app uses the built-in, but it may not have file permissions. Try moving the prefs file into the Downloads dir, perhaps it could help. What's your system version?

**Comment by AndreyPavlenko** [comment]
Here is the build with the `me.app.fermata.auto` package name https://app.box.com/s/5iqqgy41opydm2eorcqoxopu4od4d9kt

**Comment by sebomaster** [comment]
I have the same problem

**Comment by sebomaster** [comment]
My phone not have arm64 .. this Redmi 7a .. please send me file to install 1.9.9

**Comment by AndreyPavlenko** [comment]
Uploaded here - https://github.com/AndreyPavlenko/Fermata/releases/tag/1.9.9
