### ISSUE TITLE
Fermata auto 1.9.9 on bmw

### ISSUE THREAD

**Issue by Bogmehedintu** [AndreyPavlenko/Fermata#502]
Hello
I am new on fermata auto. 
So please help me
I have a bmw idrive 7 and android auto. 
But fermata auto doesn t work.
Can you help me please 
Thank you

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by Bogmehedintu** [comment]
Sorry but i can t manage.
I tried what you write but i can t find Magisk Manager, go to Modules and install the module.....
Do you please have detailed information/ steps....
Thank you

**Comment by AndreyPavlenko** [comment]
This is for rooted devices. If you don't have root, skip this part. The easiest way - AAWireless.

**Comment by Bogmehedintu** [comment]
Don t works in bmw i drive 7
I have aawireless in a honda car and is working perfectly.
For bmw.....anything?
Thank you

**Comment by AndreyPavlenko** [comment]
Then, either root or the screen mirroring trick with a head unit emulator. Unfortunately, no other choices for A14.
