### ISSUE TITLE
 Fermata Auto 1.9.9 on Motorola Edge 20 lite not appear app into android auto but is listed in packets 

### ISSUE THREAD

**Issue by coolshark** [AndreyPavlenko/Fermata#506]
-Fermata Auto version: 1.9.9
-Device: Motorola Edge 20 lite 
-Android version: 12
-Vehicle: Dacia

Problems:

1.Fermata Auto Application

-Connection to vehicle: Fermata Auto application does not appear, 

![WhatsApp Image 2024-06-27 at 12 14 52](https://github.com/AndreyPavlenko/Fermata/assets/293121/394c44f9-5818-441c-a885-c8c7666e2c80)
![WhatsApp Image 2024-06-27 at 12 14 51](https://github.com/AndreyPavlenko/Fermata/assets/293121/a691c51a-ddc1-4bf7-aa3b-65aa39a7ded9)

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by coolshark** [comment]
hi Andrey, the android version is 12 not 14 ... and my device isnt'rooted ... i can try only install the app with kinginstaller ...

**Comment by AndreyPavlenko** [comment]
For Android 12 KingInstaller should work.
