### ISSUE TITLE
Redmi note 13 pro+ with Hyper OS fermata auto not working

### ISSUE THREAD

**Issue by Crumanos** [AndreyPavlenko/Fermata#508]
Greetings,

Yesterday my phone updated to the new Hyper OS. I have the Xiaomi redmi note 13 Pro+. The app Fermata auto stoped....
Nothing work at all... Can we have any solution or update?
Thanks in advanced.

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/discussions/432

**Comment by Crumanos** [comment]
I know this and doesn't work.

**Comment by AndreyPavlenko** [comment]
These are the only solutions at the moment - either AAWireless or root.

**Comment by Crumanos** [comment]
Thanks for the information

**Comment by Crumanos** [comment]
Is there any way Fermata to work properly with Xiaomi HyperOS?

**Comment by AndreyPavlenko** [comment]
AAWireless does not work?

**Comment by Crumanos** [comment]
AAWireless doesn't work. I throw 50€. Doesn't Show Fermata Auto. I put it on Dev also and nothing...
I really want Fermata Auto. It's the app that i am doing everything. After the update of Xiaomi the Hyper OS can't make it to work....

**Comment by AndreyPavlenko** [comment]
Have you tried a head unit emulator? If you see the app in the emulator, then there is a chance to get it working with AAWireless.

**Comment by Crumanos** [comment]
I don't know what is the " Head unit emulator ". Can you help me please? Also is there any chance to make Fermata Auto to work properly with Xiaomi HyperOs?

**Comment by Crumanos** [comment]
Also I would like to thank you for the assistance.

**Comment by AndreyPavlenko** [comment]
> I don't know what is the " Head unit emulator ". Can you help me please?

This is either Headunit Reloaded Emulator HUR or https://developer.android.com/training/cars/testing/dhu

**Comment by Crumanos** [comment]
I test it but nothing....

**Comment by Crumanos** [comment]
Fermata work on my old phone but crashing all the time because its an old phone.
