### ISSUE TITLE
Why I could play only the audio from the video files?

### ISSUE THREAD

**Issue by Barrakuda1** [AndreyPavlenko/Fermata#51]
Android auto 6.9
Fermata: newest version.

The connection worked finally, but only the audio was played from the video files. What can be the reason?

**Comment by AndreyPavlenko** [comment]
Uninstall the application and install it using KingInstaller (see instruction). Manual apk installation does not work.

**Comment by Alejandro2454** [comment]
Estimado Andrey,
Me podrías por favor enviar el link para descargar Kinginstaller
Saludos
Alejandro

**Comment by Barrakuda1** [comment]
I have experienced an issue which may help to find the root cause of the problem:
When I have installed the new Fermata version it appeared on the AA application list (on the phone), but
when I connected the mobile to the car than the Fermata disappeared from the appliciation list. Only the google play version was visible.

**Comment by Barrakuda1** [comment]
Do you have any idea why this happened? If phone sees the application in Android Auto than the installation is correct and the sw is compatible, just something happens during car connection what blocks the sw.

**Comment by AndreyPavlenko** [comment]
Unfortunately, no. If you can reproduce this behavior, try to capture logcat when connecting the phone. Perhaps we will find some info in the log.

**Comment by Barrakuda1** [comment]
I think it happens each time. The sw appears on the phone again when car connection is ended. How can I capture logcat?

**Comment by AndreyPavlenko** [comment]
First link from google https://www.youtube.com/watch?v=W6iDw76UpQw&t=113s
