### ISSUE TITLE
Con fermata auto  i comandi al volante non funzionano 

### ISSUE THREAD

**Issue by Rosinella1960** [AndreyPavlenko/Fermata#554]
Quando sono su fermata auto  al volante funziona solo la regolazione del volume, se voglio cambiare il canale o video su youtube non vá
 Si puo risolvere?

**Comment by AndreyPavlenko** [comment]
Have you tried to launch Fermata Media Service manually?

**Comment by Rosinella1960** [comment]
Fatto funziona correttamente.. 
Graziemilla
