### ISSUE TITLE
The programm disappeared at android auto

### ISSUE THREAD

**Issue by Respect911** [AndreyPavlenko/Fermata#556]
I  have a samsung ultra 23 phone with Android 14. Before that I had Android 13. Everything worked perfectly. Now after the update, in my car's Android Auto, there's no longer fermata auto . It's simply not there. It's on the phone, but not in the car. I enabled developer options in Android Auto but it didn't help. What should I do? I use this program a lot and would appreciate help. I'd even happily buy the author three coffees.

**Comment by AndreyPavlenko** [comment]
Unfortunately, there is no simple solution for A14. The easiest is AAWireless - https://github.com/AndreyPavlenko/Fermata/discussions/432
