### ISSUE TITLE
ftp support

### ISSUE THREAD

**Issue by magusone** [AndreyPavlenko/Fermata#61]
hello,
any chance of adding ftp (port 21) support not only sftp (port 22). 

thx for help.

**Comment by AndreyPavlenko** [comment]
Hello. I don't have in plans adding support for FTP. This is an outdated and insecure protocol.

**Comment by magusone** [comment]
I know but my router (rt-ac86u) has only FTP and FTP works best for my local LAN usage.

**Comment by AndreyPavlenko** [comment]
SFTP stands for SSH File Transfer Protocol. Try to enable SSH on your router.
