### ISSUE TITLE
Control app not working in 1.8.8

### ISSUE THREAD

**Issue by dineshkumardm** [AndreyPavlenko/Fermata#75]
Hi i have updated the both fermata auto and control to 1.8.8

Still control is not working.

**Comment by fcaronte** [comment]
Umh, i have full black screen on control app too. But I'm using a self compiled version so maybe I make some mistake 🤔

**Comment by fcaronte** [comment]
Edit. I delete data for control app and now work correctly 💪🏻

**Comment by AndreyPavlenko** [comment]
Try to start Fermata Auto first and start some playback. It should establish connection with control and, after that, control should work.

**Comment by podimonanil** [comment]
If control app not working, try this trick which worked for me.
Settings > Apps>Auto start
Enable autostart for fermata control.
