### ISSUE TITLE
Infinite loading icon upon opening App

### ISSUE THREAD

**Issue by Painas** [AndreyPavlenko/Fermata#8]
Hi,

Basically when I open the app on android auto, as soon as I enter a folder with videos, all thumbnails appear with a loading icon. I have tried to force stop app on the phone and sometimes the icons appear but it only plays 8/12 seconds of video, then the screen goes black, it goes back to folder selection, if you try any file a second time, the video plays for either the same time or a bit less and repeats the problem, black screen and back to video selection but this time, all icons are now again with the loading spinning wheel again. I have tried changing the media engine and sometimes it works, sometimes it crashes AA in totalitty. Is it necessary to have the official Fermata Media Player installed? In order to use VLC media engine, does having VLC installed on the device influences the performance? 

Using Android Auto 5.3, AA-Phenotype-Patcher 0.85 and Fermata Auto 1.7.3.

**Comment by AndreyPavlenko** [comment]
Try to change the media scanner to VLC (Settings>Media Engine>Preferred Media Scanner). Also use VLC as the preferred media engine for video.

**Comment by Painas** [comment]
Hi, thanks for the sugestion. It did indeed work, well partially. Everytime I reboot the phone or I turn off the car I need to manually force stop the app so that the loading icons dissappear. Although it is not critital for it to work, it is somewhat inconvenient everytime that you want to watch it, you have to manually force stop and restart app. Is there any solution for this?

**Comment by AndreyPavlenko** [comment]
The loading icon should disappear when the media is scanned and the metadata is retriever. Perhaps you have some corrupted file in the list. Try to identify and remove this file. Anyway, it seems like a bug and should be fixed. I'll try to reproduce the issue.
