### ISSUE TITLE
my app freezes

### ISSUE THREAD

**Issue by Giazzo78** [AndreyPavlenko/Fermata#84]
### Discussed in https://github.com/AndreyPavlenko/Fermata/discussions/81

<div type='discussions-op-text'>

<sup>Originally posted by **Giazzo78** November 19, 2021</sup>
my app freezes after 5 minutes of use, how can I fix. Thank you</div>

**Comment by AndreyPavlenko** [comment]
When does it freeze?

**Comment by thiagojabur** [comment]
On My Android 11 its Also Freeze. It happens randomly and i cant go to the android auto menu home anymore. I have to unplug the phone and put it back in again

**Comment by AndreyPavlenko** [comment]
Does it happen when you watch video?

**Comment by thiagojabur** [comment]
Yes @AndreyPavlenko! I downloaded the videos using TubeMate App and put them in Fermata player. In approximately 5 minutes the video freezes and everything is locked, even the home button on Android Auto.

**Comment by AndreyPavlenko** [comment]
So, this is a local video, on sdcard, not a stream?
How did you add the folder with video to Fermata? Did you use File system of Content option?

**Comment by thiagojabur** [comment]
Local video on smartphone primary memory.  Not SDCard. I used "File System" option.

**Comment by AndreyPavlenko** [comment]
Try changing the media engine - long click on the folder > Media engine. Or change globally in settings.

**Comment by thiagojabur** [comment]
I disabled ExoPlayer and VLC and the problem remains.

**Comment by AndreyPavlenko** [comment]
Please, send me the log /mnt/sdcard/Android/data/me.aap.fermata.auto.dear.google.please.dont.block/files/Fermata.log

**Comment by AndreyPavlenko** [comment]
Thanks, but, unfortunately, nothing there.
Does it hang only in AA?

**Comment by thiagojabur** [comment]
Only in Android Auto. I made a video, see, and also a new log. It's shared https://ufcatalao-my.sharepoint.com/:f:/g/personal/thiagojabur_ufcat_edu_br/Ek9e83izseNOry9vgPNIEsUBrllaCBVZn-VbvtVnoRa90g?e=MlOadN 
In the video I have the car stopped, the cell phone's GPS turned off and he is in airplane mode.

**Comment by thiagojabur** [comment]
Perhaps the error is this: 
[03-11-21 13:52:46][ERROR][main][me.aap.utils.ui.activity.ActivityDelegate.getActivityDelegate(ActivityDelegate.java:12)] Activity delegate not found. contextToDelegate = null
java.lang.IllegalArgumentException: Unsupported context: android.app.ContextImpl@b157873
	at me.aap.utils.ui.activity.ActivityDelegate.getActivityDelegate(ActivityDelegate.java:11)
	at me.aap.fermata.ui.activity.MainActivityDelegate.getActivityDelegate(MainActivityDelegate.java:1)

**Comment by thiagojabur** [comment]
[Fermata.log](https://github.com/AndreyPavlenko/Fermata/files/7651296/Fermata.log)

**Comment by AndreyPavlenko** [comment]
This error happens on shutdown.
