### ISSUE TITLE
Add Bookmark as shortcut

### ISSUE THREAD

**Issue by fcaronte** [AndreyPavlenko/Fermata#85]
Is possible to choose a saved bookmark and use as a shortcut. example i would to add whatsapp web and have a directly button to open it from nav bar and maybe save if "desktop mode" or not for the single bookmark (whatsapp required to use desktop mode)

**Comment by AndreyPavlenko** [comment]
You may use voice commands to open bookmarks. Setting desktop mode property for bookmarks is not currently supported, but I agree, it's a good feature to add.
