### ISSUE TITLE
can't add m3u url since 1.7.7

### ISSUE THREAD

**Issue by Romeo26222** [AndreyPavlenko/Fermata#86]
Hello,
I have an m3u paid playlist url file, I was able to add and watch contents on 1.7.7
since this version when I add new m3u playlist and enter the url and info nothing happens, just empty m3u folder with no content.
the url is valid as it downloads the m3u file when I open it on any browser,
what's wrong I am doing!
regards.

**Comment by AndreyPavlenko** [comment]
Have you tried to download playlist and enter file path instead of url?

**Comment by Romeo26222** [comment]
> Have you tried to download playlist and enter file path instead of url?

Yes, and this way it loads and works, but by using lical file I can't see new updates on the playlist and I have to repeat the steps of downloading the m3u file everytime new content is added.
this function was working well on version 1.7.7 but since then it is broken on all higher versions.

**Comment by AndreyPavlenko** [comment]
I don't think this functionality has changed since 1.7.7. Did you changed user agent in 1.7.7? Your provider's server may reject requests due to unsupported UA.

**Comment by EdmiltonJr** [comment]
The same happens to me. The list dont load. I need to download it in a browser on the outside and indicate the file already downloaded. Can you tell me how to make it work?

**Comment by AndreyPavlenko** [comment]
I think, the problem is in User-Agent. Your server just returns some html page instead of m3u playlist.
I'll add an option to change UA while downloading the playlist.

**Comment by roydestroy** [comment]
Can you explain how to change the User Agent? I have tried Mozilla/5.0, I have tried Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

and many more, and every time it does nothing, plus when I go back to edit the playlist, the user agent is switched back to Fermata/1.8.9

**Comment by AndreyPavlenko** [comment]
Add playlist > Connection settings > User-Agent

**Comment by roydestroy** [comment]
Yes I have done that and as I told you I used these user agents that I have written above and every time it reverts on its own back to Fermata/1.8.9 and nothing changes
