### ISSUE TITLE
Android auto 7 sürümünden sonra fermata auto çalışmıyor.

### ISSUE THREAD

**Issue by Sezar3131** [AndreyPavlenko/Fermata#87]
Android auto başlangıcı özelleştirme kısmında da fermata auto görünmüyor

**Comment by AndreyPavlenko** [comment]
You need to install version 1.8.8. Please, follow this instruction:
https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/

**Comment by Sezar3131** [comment]
Teşekkürler 1.8.8 uygulama yükleyince sorun bitti.

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin
________________________________
