### ISSUE TITLE
When I open a custom debug version of the app on Android Auto I get a blank screen but in the Emulator works perfect

### ISSUE THREAD

**Issue by stevendevit** [AndreyPavlenko/Fermata#88]
Hi, I have cloned the repo to add some features for personal use to share later. I'm developing using an Emulator I run the app and it works fine. I have enabled Android Auto Developer Mode. 

Then I want to try in a real device I install the app with Android Studio (the debug build) on my Phone and then I go to my car and link it to Android Auto. However when I open the app I get a blank screen and nothing happens, no tabs are shown (folders, tv, favs,...) Only a text that contains "no new messages during this drive".  Any idea why is this happening? Thanks in advance

**Comment by AndreyPavlenko** [comment]
Try to delete this line - https://github.com/AndreyPavlenko/Fermata/blob/2b1472582c59643fb2f711a10f0000d98cbfc13a/fermata/src/auto/res/xml/automotive_app_desc.xml#L9

**Comment by stevendevit** [comment]
Hi @AndreyPavlenko thanks for your fast response. When I delete that line the app is not listed anymore by Android Auto :(.

**Comment by stevendevit** [comment]
Hi @AndreyPavlenko  this is what I see when I open the app  I installed with Android Studio on Android Auto
![20211123_231006](https://user-images.githubusercontent.com/20980018/143140560-15ee5f68-4d6f-48c3-b425-c295afd1f000.jpg)

**Comment by AndreyPavlenko** [comment]
You need to install the app with KingInstaller and enable unknown sources in AA settings.
https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/

**Comment by stevendevit** [comment]
Hi @AndreyPavlenko that was the step I  was missing! Now it works fine thank you so much!!
