### ISSUE TITLE
Not working since AA update

### ISSUE THREAD

**Issue by DMaxfield256** [AndreyPavlenko/Fermata#89]
I haven't been able to get this to work since Android Auto updated a couple weeks ago. Is there a solution to get it working again?

**Comment by AndreyPavlenko** [comment]
https://github.com/AndreyPavlenko/Fermata/issues/67

**Comment by cyrilpreiss** [comment]
same issue here :-(

**Comment by mathaytus** [comment]
mine worked until " i guess " this week. now app works on phone but NOT in car / android auto. keeps crashing

**Comment by ThanosGr1980** [comment]
Me to
