### ISSUE TITLE
GMT Time Zone difference on streams 

### ISSUE THREAD

**Issue by malebuffy** [AndreyPavlenko/Fermata#9]
I have a m3u file which has some live streams. One of the channels is a Greek channel and I live in Switzerland. So the time difference is -1 Hour. On one channel, not on all fermata auto plays the stream 1 hour back. So instead of streaming live it streams it with -1 hour.

Using the same file and stream in VLC directly,  plays the channel live.

Anyone know why?

Here is the stream:

http://skai-live.siliconweb.com/media/cambria4/index_bitrate1200K.m3u8

**Comment by AndreyPavlenko** [comment]
This link is not a stream. It always plays the same short video.

**Comment by malebuffy** [comment]
It's part of a m3u link so it changes. New one is here:

https://skai-live-back.siliconweb.com/media/cambria4/index.m3u8

**Comment by AndreyPavlenko** [comment]
Change the user agent to vlc

**Comment by malebuffy** [comment]
Worked

**Comment by iptvnikolas** [comment]
Tfvekeksn.net/koproskyla/skai/.m3u?
