### ISSUE TITLE
Fermata auto not working last update

### ISSUE THREAD

**Issue by Fla75** [AndreyPavlenko/Fermata#96]
hello everyone ... even for me after the last update stop auto no longer appears on android auto you only see fermata control .... solutions?
![Screenshot_20211204-143041_Android Auto](https://user-images.githubusercontent.com/95533370/144711517-af1798c5-b11d-4dc3-b495-dc6bf45f1fcc.jpg)

**Comment by AndreyPavlenko** [comment]
Duplicate of #92
