### ISSUE TITLE
Не отбражается fermata avto в андроид авто

### ISSUE THREAD

**Issue by Patriot26rus** [AndreyPavlenko/Fermata#97]
Добрый день Андрей! Сегодня 04.12.2021 перестала отображатся в андроид авто fermata avto, при чем Fermata control отображается. Версия андроид 11, Android Auto: 7.0.614134-release. Fermata Auto: 1.8.9, но исчезла на версии 1.8.7. Андроид авто не обновлял. Что делать? Удалял все приложения фермата, очищал кэш, перегружал телефон, откатывался до версии 1.8.7 которая после обновления андроид авто работала, тоже не работает  ничего не помогает, отображается только android control(((((

**Comment by AndreyPavlenko** [comment]
Гугл заблокировал приложение.
Duplicate of #92

**Comment by Patriot26rus** [comment]
А решения есть?
