### ISSUE TITLE
Android Audio Audio Layout

### ISSUE THREAD

**Issue by yaminb** [AndreyPavlenko/Fermata#99]
This is the layout on my 7 inch screen.
Could we alter this to make it more usable.

1. Fast foward/rewind should be easily accessible. Rewind is there, but fast forward is hidden in the ...
2. Add a standard horizontal bar to show/select song progress.Right now, song progress is shown in the circle around the pause button, but you can't interact with it

I'd suggest making the fermata logo smaller and the song title smaller.
This should make room for the above elements.

![fermata_screen](https://user-images.githubusercontent.com/11525425/145102482-4e51dbd6-275c-477b-81e5-fa5f5c7ee017.jpg)

**Comment by AndreyPavlenko** [comment]
This is not Fermata. This is the standard Android Auto media player. Every media application, with support for AA, has the same (or very similar interface). Media apps just provide content and play. The interface is provided by AA.

**Comment by yaminb** [comment]
I understand. Is there any options you can play with or options you can provide?
It really doesn't look like there are many options.

Maybe providing smaller icons/track pictures.
To customize button layouts, apply build-time overlays to play_pause_stop_button_layout.xml (https://source.android.com/devices/automotive/hmi/media/customization)

If not, we can close this.

**Comment by AndreyPavlenko** [comment]
The link you provided is about Android Automotive, but not android auto. See the difference - https://source.android.com/devices/automotive/start/what_automotive#android-automotive-android-auto.

If you need a different interface, try [Fermata Auto](https://forum.xda-developers.com/t/fermata-media-player-audio-and-video-player-for-android-auto.4079519/)

**Comment by yaminb** [comment]
ah gotcha. I installed fermata auto now. Hopefully should be good.
